## MovieLens Data Analysis-Genre_A

---

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

---

## Data Load

In [3]:
data = pd.read_csv("C:/Users/LWH/PycharmProjects/MovieLensDataAnalysis/u.data", sep='\t',
                   names=["user id", "movie id", "rating", "timestamp"], header=None)

In [4]:
data

       user id  movie id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [5]:
item = pd.read_csv("C:/Users/LWH/PycharmProjects/MovieLensDataAnalysis/u.item", sep='|',
                   names=["movie id", "movie title", "release date", "video release date", "IMDb URL",
                          "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime", "Documentary", "Drama",
                          "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"],
                   header=None, encoding='latin1')

In [6]:
item

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
user = pd.read_csv("C:/Users/LWH/PycharmProjects/MovieLensDataAnalysis/u.user", sep='|',
                   names=["user id", "age", "gender", "occupation", "zip code"], header=None)

In [8]:
user

     user id  age gender     occupation zip code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

---

## Calculate the ratings by the genre (descending order)

---

### A_1) number of ratings by each genre for all users

In [9]:
all_1 = data[["movie id", "rating"]]
all_1 = all_1["rating"].groupby(all_1["movie id"]).count()
all_1 = all_1.sort_values(ascending=False)

In [10]:
#all_1

In [11]:
unknown = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "unknown":item["unknown"]})
unknown = unknown[unknown["unknown"] == 1]

In [12]:
#unknown

In [13]:
unknown_rank = pd.merge(unknown, all_1, on="movie id", how="left")
unknown_rank = unknown_rank.sort_values(by="rating", ascending= False)
unknown_rank = unknown_rank.reset_index(drop=True)
unknown_rank = unknown_rank[["movie title"]]
unknown_rank.index += 1
unknown_rank = unknown_rank.rename_axis("Rank")

In [14]:
unknown_rank

              movie title
Rank
1                 unknown
2     Good Morning (1971)

In [15]:
Action = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Action":item["Action"]})
Action = Action[Action["Action"] == 1]

In [16]:
#Action

In [17]:
Action_rank = pd.merge(Action, all_1, on="movie id", how="left")
Action_rank = Action_rank.sort_values(by="rating", ascending= False)
Action_rank = Action_rank.reset_index(drop=True)
Action_rank = Action_rank[["movie title"]]
Action_rank.index += 1
Action_rank = Action_rank.rename_axis("Rank")

In [18]:
Action_rank

                         movie title
Rank
1                   Star Wars (1977)
2          Return of the Jedi (1983)
3               Air Force One (1997)
4      Independence Day (ID4) (1996)
5     Raiders of the Lost Ark (1981)
...                              ...
247             The Courtyard (1995)
248               Coldblooded (1995)
249              Bird of Prey (1996)
250                  Power 98 (1995)
251                    Mirage (1995)

[251 rows x 1 columns]

In [19]:
Adventure = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Adventure":item["Adventure"]})
Adventure = Adventure[Adventure["Adventure"] == 1]

In [20]:
#Adventure

In [21]:
Adventure_rank = pd.merge(Adventure, all_1, on="movie id", how="left")
Adventure_rank = Adventure_rank.sort_values(by="rating", ascending= False)
Adventure_rank = Adventure_rank.reset_index(drop=True)
Adventure_rank = Adventure_rank[["movie title"]]
Adventure_rank.index += 1
Adventure_rank = Adventure_rank.rename_axis("Rank")

In [22]:
Adventure_rank

                          movie title
Rank
1                    Star Wars (1977)
2           Return of the Jedi (1983)
3      Raiders of the Lost Ark (1981)
4                    Rock, The (1996)
5     Empire Strikes Back, The (1980)
...                               ...
131                   Star Kid (1997)
132            Golden Earrings (1947)
133      Good Man in Africa, A (1994)
134               Time Tracers (1995)
135           Wings of Courage (1995)

[135 rows x 1 columns]

In [23]:
Animation = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Animation":item["Animation"]})
Animation = Animation[Animation["Animation"] == 1]

In [24]:
#Animation

In [25]:
Animation_rank = pd.merge(Animation, all_1, on="movie id", how="left")
Animation_rank = Animation_rank.sort_values(by="rating", ascending= False)
Animation_rank = Animation_rank.reset_index(drop=True)
Animation_rank = Animation_rank[["movie title"]]
Animation_rank.index += 1
Animation_rank = Animation_rank.rename_axis("Rank")

In [26]:
Animation_rank

                                            movie title
Rank
1                                      Toy Story (1995)
2                                 Lion King, The (1994)
3                                        Aladdin (1992)
4                           Beauty and the Beast (1991)
5                                       Fantasia (1940)
6                Snow White and the Seven Dwarfs (1937)
7                Beavis and Butt-head Do America (1996)
8                                     Cinderella (1950)
9                   Hunchback of Notre Dame, The (1996)
10                     James and the Giant Peach (1996)
11                                         Dumbo (1941)
12                           Wrong Trousers, The (1993)
13                                Close Shave, A (1995)
14                                     Pinocchio (1940)
15                                     Space Jam (1996)
16                       Sword in the Stone, The (1963)
17                           Alice in Wonderland (1951)
18          Winnie the Pooh and the Blustery Day (1968)
19                                   Heavy Metal (1981)
20    Wallace & Gromit: The Best of Aardman Animatio...
21                                      Hercules (1997)
22                                     Anastasia (1997)
23                              Grand Day Out, A (1992)
24                        Fox and the Hound, The (1981)
25                               Aristocats, The (1970)
26                                    Pocahontas (1995)
27                                         Akira (1988)
28                                 Pete's Dragon (1977)
29                              Cats Don't Dance (1997)
30                  Transformers: The Movie, The (1986)
31               Aladdin and the King of Thieves (1996)
32           Ghost in the Shell (Kokaku kidotai) (1995)
33                         Three Caballeros, The (1945)
34                              Oliver & Company (1988)
35                                Goofy Movie, A (1995)
36                                         Balto (1995)
37                       All Dogs Go to Heaven 2 (1996)
38                               Pagemaster, The (1994)
39                            Swan Princess, The (1994)
40    Land Before Time III: The Time of the Great Gi...
41                                         Faust (1994)
42                              Gumby: The Movie (1995)

In [27]:
Children = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Children's":item["Children's"]})
Children = Children[Children["Children's"] == 1]

In [28]:
#Children

In [29]:
Children_rank = pd.merge(Children, all_1, on="movie id", how="left")
Children_rank = Children_rank.sort_values(by="rating", ascending= False)
Children_rank = Children_rank.reset_index(drop=True)
Children_rank = Children_rank[["movie title"]]
Children_rank.index += 1
Children_rank = Children_rank.rename_axis("Rank")

In [30]:
Children_rank

                                       movie title
Rank
1                                 Toy Story (1995)
2     Willy Wonka and the Chocolate Factory (1971)
3                E.T. the Extra-Terrestrial (1982)
4                         Wizard of Oz, The (1939)
5                            Lion King, The (1994)
...                                            ...
118                     So Dear to My Heart (1949)
119                                   Buddy (1997)
120                                Star Kid (1997)
121                          Simple Wish, A (1997)
122          Daniel Defoe's Robinson Crusoe (1996)

[122 rows x 1 columns]

In [31]:
Comedy = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Comedy":item["Comedy"]})
Comedy = Comedy[Comedy["Comedy"] == 1]

In [32]:
#Comedy

In [33]:
Comedy_rank = pd.merge(Comedy, all_1, on="movie id", how="left")
Comedy_rank = Comedy_rank.sort_values(by="rating", ascending= False)
Comedy_rank = Comedy_rank.reset_index(drop=True)
Comedy_rank = Comedy_rank[["movie title"]]
Comedy_rank.index += 1
Comedy_rank = Comedy_rank.rename_axis("Rank")

In [34]:
Comedy_rank

                                       movie title
Rank
1                                 Liar Liar (1997)
2                                 Toy Story (1995)
3                        Back to the Future (1985)
4     Willy Wonka and the Chocolate Factory (1971)
5                       Princess Bride, The (1987)
...                                            ...
501                               Sleepover (1995)
502                   Damsel in Distress, A (1937)
503                      Death in Brunswick (1991)
504                    Love Is All There Is (1996)
505                            You So Crazy (1994)

[505 rows x 1 columns]

In [35]:
Crime = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Crime":item["Crime"]})
Crime = Crime[Crime["Crime"] == 1]

In [36]:
#Crime

In [37]:
Crime_rank = pd.merge(Crime, all_1, on="movie id", how="left")
Crime_rank = Crime_rank.sort_values(by="rating", ascending= False)
Crime_rank = Crime_rank.reset_index(drop=True)
Crime_rank = Crime_rank[["movie title"]]
Crime_rank.index += 1
Crime_rank = Crime_rank.rename_axis("Rank")

In [38]:
Crime_rank

                             movie title
Rank
1                           Fargo (1996)
2                  Godfather, The (1972)
3                    Pulp Fiction (1994)
4               L.A. Confidential (1997)
5             Usual Suspects, The (1995)
...                                  ...
105   Killer: A Journal of Murder (1995)
106          Angel on My Shoulder (1946)
107          Big Bang Theory, The (1994)
108       They Made Me a Criminal (1939)
109             MURDER and murder (1996)

[109 rows x 1 columns]

In [39]:
Documentary = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Documentary":item["Documentary"]})
Documentary = Documentary[Documentary["Documentary"] == 1]

In [40]:
#Documentary

In [41]:
Documentary_rank = pd.merge(Documentary, all_1, on="movie id", how="left")
Documentary_rank = Documentary_rank.sort_values(by="rating", ascending= False)
Documentary_rank = Documentary_rank.reset_index(drop=True)
Documentary_rank = Documentary_rank[["movie title"]]
Documentary_rank.index += 1
Documentary_rank = Documentary_rank.rename_axis("Rank")

In [42]:
Documentary_rank

                                            movie title
Rank
1                                    Hoop Dreams (1994)
2                                          Crumb (1994)
3                          Celluloid Closet, The (1995)
4                            Looking for Richard (1996)
5                                  Koyaanisqatsi (1983)
6                             When We Were Kings (1996)
7                            Thin Blue Line, The (1988)
8                   Fast, Cheap & Out of Control (1997)
9                               Paris Is Burning (1990)
10             Microcosmos: Le peuple de l'herbe (1996)
11                         Anne Frank Remembered (1995)
12    Paradise Lost: The Child Murders at Robin Hood...
13      Thirty-Two Short Films About Glenn Gould (1993)
14                        Madonna: Truth or Dare (1991)
15      Haunted World of Edward D. Wood Jr., The (1995)
16                Heidi Fleiss: Hollywood Madam (1995)
17                                      Unzipped (1995)
18    Wonderful, Horrible Life of Leni Riefenstahl, ...
19                         Endless Summer 2, The (1994)
20                                    Wonderland (1997)
21                               Man of the Year (1995)
22                                 War Room, The (1993)
23                             Year of the Horse (1997)
24                     Ayn Rand: A Sense of Life (1997)
25                                Rhyme & Reason (1997)
26    Brother Minister: The Assassination of Malcolm...
27                        Across the Sea of Time (1995)
28                          Perfect Candidate, A (1996)
29                                 Grateful Dead (1995)
30               Maya Lin: A Strong Clear Vision (1994)
31    Last Klezmer: Leopold Kozlowski, His Life and ...
32                                       Catwalk (1995)
33        Carmen Miranda: Bananas Is My Business (1994)
34                                American Dream (1990)
35                 Line King: Al Hirschfeld, The (1996)
36                                       Everest (1998)
37                                     Nico Icon (1995)
38                                     Show, The (1995)
39         Eye of Vichy, The (Oeil de Vichy, L') (1993)
40           Tigrero: A Film That Was Never Made (1994)
41                                      Dadetown (1995)
42                             Paris Was a Woman (1995)
43                   Gate of Heavenly Peace, The (1995)
44            JLG/JLG - autoportrait de dÃ©cembre (1994)
45                              Leopard Son, The (1996)
46           Marlene Dietrich: Shadow and Light (1996)
47                                Jupiter's Wife (1994)
48                          Fire on the Mountain (1996)
49                        Great Day in Harlem, A (1994)
50                                  Big One, The (1997)

In [43]:
Drama = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Drama":item["Drama"]})
Drama = Drama[Drama["Drama"] == 1]

In [44]:
#Drama

In [45]:
Drama_rank = pd.merge(Drama, all_1, on="movie id", how="left")
Drama_rank = Drama_rank.sort_values(by="rating", ascending= False)
Drama_rank = Drama_rank.reset_index(drop=True)
Drama_rank = Drama_rank[["movie title"]]
Drama_rank.index += 1
Drama_rank = Drama_rank.rename_axis("Rank")

In [46]:
Drama_rank

                                     movie title
Rank
1                                 Contact (1997)
2                                   Fargo (1996)
3                    English Patient, The (1996)
4                          Godfather, The (1972)
5                            Pulp Fiction (1994)
...                                          ...
721                  To Cross the Rubicon (1991)
722   Tigrero: A Film That Was Never Made (1994)
723                    Hostile Intentions (1994)
724                           Yankee Zulu (1994)
725    Scream of Stone (Schrei aus Stein) (1991)

[725 rows x 1 columns]

In [47]:
Fantasy = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Fantasy":item["Fantasy"]})
Fantasy = Fantasy[Fantasy["Fantasy"] == 1]

In [48]:
#Fantasy

In [49]:
Fantasy_rank = pd.merge(Fantasy, all_1, on="movie id", how="left")
Fantasy_rank = Fantasy_rank.sort_values(by="rating", ascending= False)
Fantasy_rank = Fantasy_rank.reset_index(drop=True)
Fantasy_rank = Fantasy_rank[["movie title"]]
Fantasy_rank.index += 1
Fantasy_rank = Fantasy_rank.rename_axis("Rank")

In [50]:
Fantasy_rank

                               movie title
Rank
1        E.T. the Extra-Terrestrial (1982)
2              Nutty Professor, The (1996)
3                       Dragonheart (1996)
4                         Mask, The (1994)
5                           Jumanji (1995)
6                         Space Jam (1996)
7      20,000 Leagues Under the Sea (1954)
8                Heavenly Creatures (1994)
9                           Flubber (1997)
10      Indian in the Cupboard, The (1995)
11          FairyTale: A True Story (1997)
12         Escape to Witch Mountain (1975)
13                   Drop Dead Fred (1991)
14                            Bogus (1996)
15    Kid in King Arthur's Court, A (1995)
16                  Pagemaster, The (1994)
17       NeverEnding Story III, The (1994)
18                           Kazaam (1996)
19               Warriors of Virtue (1997)
20                   Simple Wish, A (1997)
21                         Star Kid (1997)
22          Hungarian Fairy Tale, A (1987)

In [51]:
FilmNoir = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Film-Noir":item["Film-Noir"]})
FilmNoir = FilmNoir[FilmNoir["Film-Noir"] == 1]

In [52]:
#FilmNoir

In [53]:
FilmNoir_rank = pd.merge(FilmNoir, all_1, on="movie id", how="left")
FilmNoir_rank = FilmNoir_rank.sort_values(by="rating", ascending= False)
FilmNoir_rank = FilmNoir_rank.reset_index(drop=True)
FilmNoir_rank = FilmNoir_rank[["movie title"]]
FilmNoir_rank.index += 1
FilmNoir_rank = FilmNoir_rank.rename_axis("Rank")

In [54]:
FilmNoir_rank

                           movie title
Rank
1             L.A. Confidential (1997)
2                  Blade Runner (1982)
3                     Chinatown (1974)
4           Maltese Falcon, The (1941)
5     Manchurian Candidate, The (1962)
6                 Grifters, The (1990)
7                     Cape Fear (1962)
8              Mulholland Falls (1996)
9                       Hoodlum (1997)
10               Big Sleep, The (1946)
11                 Sunset Blvd. (1950)
12        Devil in a Blue Dress (1995)
13                    Notorious (1946)
14                            M (1931)
15                        Laura (1944)
16                Touch of Evil (1958)
17                    Dark City (1998)
18                     Palmetto (1998)
19             Murder, My Sweet (1944)
20                    Crossfire (1947)
21                       Suture (1993)
22                     Raw Deal (1948)
23                        T-Men (1947)
24           He Walked by Night (1948)

In [55]:
Horror = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Horror":item["Horror"]})
Horror = Horror[Horror["Horror"] == 1]

In [56]:
#Horror

In [57]:
Horror_rank = pd.merge(Horror, all_1, on="movie id", how="left")
Horror_rank = Horror_rank.sort_values(by="rating", ascending= False)
Horror_rank = Horror_rank.reset_index(drop=True)
Horror_rank = Horror_rank[["movie title"]]
Horror_rank.index += 1
Horror_rank = Horror_rank.rename_axis("Rank")

In [58]:
Horror_rank

                                            movie title
Rank
1                                         Scream (1996)
2                                          Alien (1979)
3                                           Jaws (1975)
4                                         Psycho (1960)
5                                   Shining, The (1980)
...                                                 ...
88    Spirits of the Dead (Tre passi nel delirio) (1...
89                                 Beyond Bedlam (1993)
90                                  Machine, The (1994)
91                                     Fear, The (1995)
92                                    Nightwatch (1997)

[92 rows x 1 columns]

In [59]:
Musical = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Musical":item["Musical"]})
Musical = Musical[Musical["Musical"] == 1]

In [60]:
#Musical

In [61]:
Musical_rank = pd.merge(Musical, all_1, on="movie id", how="left")
Musical_rank = Musical_rank.sort_values(by="rating", ascending= False)
Musical_rank = Musical_rank.reset_index(drop=True)
Musical_rank = Musical_rank[["movie title"]]
Musical_rank.index += 1
Musical_rank = Musical_rank.rename_axis("Rank")

In [62]:
Musical_rank

                                            movie title
Rank
1                                          Evita (1996)
2                            Blues Brothers, The (1980)
3                              Wizard of Oz, The (1939)
4                            Sound of Music, The (1965)
5                                 Lion King, The (1994)
6                                        Aladdin (1992)
7                           Beauty and the Beast (1991)
8                             This Is Spinal Tap (1984)
9                                   Mary Poppins (1964)
10                                      Fantasia (1940)
11               Snow White and the Seven Dwarfs (1937)
12                                        Grease (1978)
13                      Everyone Says I Love You (1996)
14               Nightmare Before Christmas, The (1993)
15                           Singin' in the Rain (1952)
16                                    Cinderella (1950)
17                  Hunchback of Notre Dame, The (1996)
18                     James and the Giant Peach (1996)
19                                  My Fair Lady (1964)
20                                         Dumbo (1941)
21                         Pink Floyd - The Wall (1982)
22                                 Dirty Dancing (1987)
23                        Muppet Treasure Island (1996)
24                           Alice in Wonderland (1951)
25                               Victor/Victoria (1982)
26                                     Anastasia (1997)
27                                      Hercules (1997)
28                      Bedknobs and Broomsticks (1971)
29                                    Pocahontas (1995)
30                         American in Paris, An (1951)
31                                    Doors, The (1991)
32                               Joe's Apartment (1996)
33                                 Pete's Dragon (1977)
34                                          Gigi (1958)
35                                     Tank Girl (1995)
36                              Cats Don't Dance (1997)
37                               Great Race, The (1965)
38                          Meet Me in St. Louis (1944)
39                           Blues Brothers 2000 (1998)
40                                   Spice World (1997)
41                                      Grease 2 (1982)
42                         Three Caballeros, The (1945)
43                                    Funny Face (1957)
44                                       Top Hat (1935)
45                               MisÃ©rables, Les (1995)
46    Umbrellas of Cherbourg, The (Parapluies de Che...
47                                      Backbeat (1993)
48                        Inspector General, The (1949)
49                               Shall We Dance? (1937)
50                        Farinelli: il castrato (1994)
51                                        Selena (1997)
52                             Gay Divorcee, The (1934)
53                       All Dogs Go to Heaven 2 (1996)
54                               Band Wagon, The (1953)
55                              Madame Butterfly (1995)
56                         Damsel in Distress, A (1937)

In [63]:
Mystery = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Mystery":item["Mystery"]})
Mystery = Mystery[Mystery["Mystery"] == 1]

In [64]:
#Mystery

In [65]:
Mystery_rank = pd.merge(Mystery, all_1, on="movie id", how="left")
Mystery_rank = Mystery_rank.sort_values(by="rating", ascending= False)
Mystery_rank = Mystery_rank.reset_index(drop=True)
Mystery_rank = Mystery_rank[["movie title"]]
Mystery_rank.index += 1
Mystery_rank = Mystery_rank.rename_axis("Rank")

In [66]:
Mystery_rank

                        movie title
Rank
1        Mission: Impossible (1996)
2          L.A. Confidential (1997)
3          Conspiracy Theory (1997)
4                    Amadeus (1984)
5      2001: A Space Odyssey (1968)
...                             ...
57           Underneath, The (1995)
58    Woman in Question, The (1950)
59                  Power 98 (1995)
60         Lady of Burlesque (1943)
61         MURDER and murder (1996)

[61 rows x 1 columns]

In [67]:
Romance = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Romance":item["Romance"]})
Romance = Romance[Romance["Romance"] == 1]

In [68]:
#Romance

In [69]:
Romance_rank = pd.merge(Romance, all_1, on="movie id", how="left")
Romance_rank = Romance_rank.sort_values(by="rating", ascending= False)
Romance_rank = Romance_rank.reset_index(drop=True)
Romance_rank = Romance_rank[["movie title"]]
Romance_rank.index += 1
Romance_rank = Romance_rank.rename_axis("Rank")

In [70]:
Romance_rank

                          movie title
Rank
1                    Star Wars (1977)
2           Return of the Jedi (1983)
3         English Patient, The (1996)
4                Jerry Maguire (1996)
5     Empire Strikes Back, The (1980)
...                               ...
243      Damsel in Distress, A (1937)
244                 Favor, The (1994)
245           Crude Oasis, The (1995)
246                  B. Monkey (1998)
247              Sliding Doors (1998)

[247 rows x 1 columns]

In [71]:
SciFi = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Sci-Fi":item["Sci-Fi"]})
SciFi = SciFi[SciFi["Sci-Fi"] == 1]

In [72]:
#SciFi

In [73]:
SciFi_rank = pd.merge(SciFi, all_1, on="movie id", how="left")
SciFi_rank = SciFi_rank.sort_values(by="rating", ascending= False)
SciFi_rank = SciFi_rank.reset_index(drop=True)
SciFi_rank = SciFi_rank[["movie title"]]
SciFi_rank.index += 1
SciFi_rank = SciFi_rank.rename_axis("Rank")

In [74]:
SciFi_rank

                                movie title
Rank
1                          Star Wars (1977)
2                            Contact (1997)
3                 Return of the Jedi (1983)
4             Independence Day (ID4) (1996)
5                     Twelve Monkeys (1995)
...                                     ...
97                         No Escape (1994)
98                          Star Kid (1997)
99                      Time Tracers (1995)
100   Visitors, The (Visiteurs, Les) (1993)
101                Nemesis 2: Nebula (1995)

[101 rows x 1 columns]

In [75]:
Thriller = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Thriller":item["Thriller"]})
Thriller = Thriller[Thriller["Thriller"] == 1]

In [76]:
#Thriller

In [77]:
Thriller_rank = pd.merge(Thriller, all_1, on="movie id", how="left")
Thriller_rank = Thriller_rank.sort_values(by="rating", ascending= False)
Thriller_rank = Thriller_rank.reset_index(drop=True)
Thriller_rank = Thriller_rank[["movie title"]]
Thriller_rank.index += 1
Thriller_rank = Thriller_rank.rename_axis("Rank")

In [78]:
Thriller_rank

                           movie title
Rank
1                         Fargo (1996)
2                        Scream (1996)
3                 Air Force One (1997)
4     Silence of the Lambs, The (1991)
5                     Rock, The (1996)
...                                ...
247          Hostile Intentions (1994)
248               The Courtyard (1995)
249                    Power 98 (1995)
250           Bloody Child, The (1996)
251                   B. Monkey (1998)

[251 rows x 1 columns]

In [79]:
War = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "War":item["War"]})
War = War[War["War"] == 1]

In [80]:
#War

In [81]:
War_rank = pd.merge(War, all_1, on="movie id", how="left")
War_rank = War_rank.sort_values(by="rating", ascending= False)
War_rank = War_rank.reset_index(drop=True)
War_rank = War_rank[["movie title"]]
War_rank.index += 1
War_rank = War_rank.rename_axis("Rank")

In [82]:
War_rank

                                      movie title
Rank
1                                Star Wars (1977)
2                       Return of the Jedi (1983)
3                     English Patient, The (1996)
4                   Independence Day (ID4) (1996)
5                 Empire Strikes Back, The (1980)
...                                           ...
67                     Colonel Chabert, Le (1994)
68                          For the Moment (1994)
69                          Pharaoh's Army (1995)
70    Land and Freedom (Tierra y libertad) (1995)
71                        Nothing Personal (1995)

[71 rows x 1 columns]

In [83]:
Western = pd.DataFrame({"movie id":item["movie id"],
                       "movie title":item["movie title"],
                       "Western":item["Western"]})
Western = Western[Western["Western"] == 1]

In [84]:
#Western

In [85]:
Western_rank = pd.merge(Western, all_1, on="movie id", how="left")
Western_rank = Western_rank.sort_values(by="rating", ascending= False)
Western_rank = Western_rank.reset_index(drop=True)
Western_rank = Western_rank[["movie title"]]
Western_rank.index += 1
Western_rank = Western_rank.rename_axis("Rank")

In [86]:
Western_rank

                                            movie title
Rank
1                             Dances with Wolves (1990)
2             Butch Cassidy and the Sundance Kid (1969)
3                                     Unforgiven (1992)
4                Good, The Bad and The Ugly, The (1966)
5                                       Maverick (1994)
6                         Magnificent Seven, The (1954)
7                                      Tombstone (1993)
8                                     Young Guns (1988)
9                                      High Noon (1952)
10                           Legends of the Fall (1994)
11                             Last Man Standing (1996)
12                                    Wyatt Earp (1994)
13                       Quick and the Dead, The (1995)
14                                 Young Guns II (1990)
15    City Slickers II: The Legend of Curly's Gold (...
16                               Wild Bunch, The (1969)
17                  Once Upon a Time in the West (1969)
18                                      Dead Man (1995)
19                      Apple Dumpling Gang, The (1975)
20                                     Wild Bill (1995)
21      Davy Crockett, King of the Wild Frontier (1955)
22                                Lightning Jack (1994)
23                  Geronimo: An American Legend (1993)
24                                     Bad Girls (1994)
25                          Angel and the Badman (1947)
26                                   Outlaw, The (1943)
27                        Terror in a Texas Town (1958)

---

### A_2) number of ratings by each genre for genders

In [87]:
gender_1 = data[["user id", "movie id", "rating"]]

In [88]:
#gender_1

In [89]:
gender_2 = user[["user id", "gender"]]

In [90]:
#gender_2

In [91]:
gender_3 = pd.merge(gender_2, gender_1, on="user id", how="left")
gender_3 = gender_3.groupby(["gender", "movie id"], as_index=False)["rating"].count()

In [92]:
#gender_3

In [93]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(unknown, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [94]:
#man

In [95]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(unknown, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [96]:
#woman

In [97]:
unknown_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
unknown_gender_rank = unknown_gender_rank.reset_index(drop=True)
unknown_gender_rank.index += 1
unknown_gender_rank = unknown_gender_rank.rename_axis("Rank")
unknown_gender_rank

                     Male               Female
Rank
1                 unknown              unknown
2     Good Morning (1971)  Good Morning (1971)

In [98]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Action, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [99]:
#man

In [100]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Action, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [101]:
#woman

In [102]:
Action_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Action_gender_rank = Action_gender_rank.reset_index(drop=True)
Action_gender_rank.index += 1
Action_gender_rank = Action_gender_rank.rename_axis("Rank")
Action_gender_rank

                                Male                         Female
Rank
1                   Star Wars (1977)               Star Wars (1977)
2          Return of the Jedi (1983)           Air Force One (1997)
3     Raiders of the Lost Ark (1981)      Return of the Jedi (1983)
4      Independence Day (ID4) (1996)  Independence Day (ID4) (1996)
5              Godfather, The (1972)          Godfather, The (1972)
...                              ...                            ...
247              Men of Means (1998)       Nemesis 2: Nebula (1995)
248             The Courtyard (1995)          Romper Stomper (1992)
249        Hostile Intentions (1994)              Tokyo Fist (1995)
250            Lashou shentan (1992)        King of New York (1990)
251                    Mirage (1995)                  Target (1995)

[251 rows x 2 columns]

In [103]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Adventure, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [104]:
#man

In [105]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Adventure, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [106]:
#woman

In [107]:
Adventure_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Adventure_gender_rank = Adventure_gender_rank.reset_index(drop=True)
Adventure_gender_rank.index += 1
Adventure_gender_rank = Adventure_gender_rank.rename_axis("Rank")
Adventure_gender_rank

,Male,Female
Rank,,
1,Star Wars (1977),Star Wars (1977)
2,Return of the Jedi (1983),Return of the Jedi (1983)
3,Raiders of the Lost Ark (1981),Raiders of the Lost Ark (1981)
4,Star Trek: First Contact (1996),Willy Wonka and the Chocolate Factory (1971)
5,"Rock, The (1996)","Rock, The (1996)"
...,...,...
131,"Second Jungle Book: Mowgli & Baloo, The (1997)",Star Kid (1997)
132,Gold Diggers: The Secret of Bear Mountain (1995),Surviving the Game (1994)
133,"Good Man in Africa, A (1994)",Golden Earrings (1947)
134,Golden Earrings (1947),Wings of Courage (1995)
135,Wings of Courage (1995),"Good Man in Africa, A (1994)"

In [108]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Animation, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [109]:
#man

In [110]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Animation, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [111]:
#woman

In [112]:
Animation_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Animation_gender_rank = Animation_gender_rank.reset_index(drop=True)
Animation_gender_rank.index += 1
Animation_gender_rank = Animation_gender_rank.rename_axis("Rank")
Animation_gender_rank

,Male,Female
Rank,,
1,Toy Story (1995),Toy Story (1995)
2,Aladdin (1992),"Lion King, The (1994)"
3,"Lion King, The (1994)",Beauty and the Beast (1991)
4,Beauty and the Beast (1991),Aladdin (1992)
5,Beavis and Butt-head Do America (1996),Fantasia (1940)
6,Fantasia (1940),Snow White and the Seven Dwarfs (1937)
7,Snow White and the Seven Dwarfs (1937),Cinderella (1950)
8,"Close Shave, A (1995)","Hunchback of Notre Dame, The (1996)"
9,"Hunchback of Notre Dame, The (1996)",James and the Giant Peach (1996)
10,Dumbo (1941),Dumbo (1941)
11,"Wrong Trousers, The (1993)",Alice in Wonderland (1951)
12,James and the Giant Peach (1996),Beavis and Butt-head Do America (1996)
13,Cinderella (1950),Pinocchio (1940)
14,Space Jam (1996),"Wrong Trousers, The (1993)"
15,Pinocchio (1940),Anastasia (1997)
16,Heavy Metal (1981),Winnie the Pooh and the Blustery Day (1968)
17,"Sword in the Stone, The (1963)","Aristocats, The (1970)"
18,Wallace & Gromit: The Best of Aardman Animatio...,"Sword in the Stone, The (1963)"
19,Winnie the Pooh and the Blustery Day (1968),Hercules (1997)
20,Alice in Wonderland (1951),"Fox and the Hound, The (1981)"
21,"Grand Day Out, A (1992)","Close Shave, A (1995)"
22,Hercules (1997),Space Jam (1996)
23,Akira (1988),Pete's Dragon (1977)
24,"Fox and the Hound, The (1981)","Grand Day Out, A (1992)"
25,Anastasia (1997),Wallace & Gromit: The Best of Aardman Animatio...
26,Pocahontas (1995),Pocahontas (1995)
27,"Aristocats, The (1970)",Aladdin and the King of Thieves (1996)
28,"Transformers: The Movie, The (1986)",Heavy Metal (1981)
29,Pete's Dragon (1977),Cats Don't Dance (1997)
30,Cats Don't Dance (1997),Balto (1995)
31,Ghost in the Shell (Kokaku kidotai) (1995),Oliver & Company (1988)
32,"Three Caballeros, The (1945)",Akira (1988)
33,"Goofy Movie, A (1995)","Pagemaster, The (1994)"
34,Oliver & Company (1988),"Goofy Movie, A (1995)"
35,Aladdin and the King of Thieves (1996),Ghost in the Shell (Kokaku kidotai) (1995)
36,All Dogs Go to Heaven 2 (1996),"Swan Princess, The (1994)"
37,Balto (1995),"Three Caballeros, The (1945)"
38,"Pagemaster, The (1994)",All Dogs Go to Heaven 2 (1996)
39,Faust (1994),"Transformers: The Movie, The (1986)"
40,Land Before Time III: The Time of the Great Gi...,Land Before Time III: The Time of the Great Gi...
41,Gumby: The Movie (1995),Gumby: The Movie (1995)
42,"Swan Princess, The (1994)",Faust (1994)

In [113]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Children, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [114]:
#man

In [115]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Children, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [116]:
#woman

In [117]:
Children_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Children_gender_rank = Children_gender_rank.reset_index(drop=True)
Children_gender_rank.index += 1
Children_gender_rank = Children_gender_rank.rename_axis("Rank")
Children_gender_rank

,Male,Female
Rank,,
1,Toy Story (1995),Toy Story (1995)
2,Willy Wonka and the Chocolate Factory (1971),Willy Wonka and the Chocolate Factory (1971)
3,E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982)
4,"Wizard of Oz, The (1939)","Wizard of Oz, The (1939)"
5,Aladdin (1992),"Lion King, The (1994)"
...,...,...
118,Daniel Defoe's Robinson Crusoe (1996),So Dear to My Heart (1949)
119,Gold Diggers: The Secret of Bear Mountain (1995),"Secret Adventures of Tom Thumb, The (1993)"
120,"Second Jungle Book: Mowgli & Baloo, The (1997)",Buddy (1997)
121,"Simple Wish, A (1997)",Daniel Defoe's Robinson Crusoe (1996)
122,3 Ninjas: High Noon At Mega Mountain (1998),Star Kid (1997)

In [118]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Comedy, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [119]:
#man

In [120]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Comedy, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [121]:
#woman

In [122]:
Comedy_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Comedy_gender_rank = Comedy_gender_rank.reset_index(drop=True)
Comedy_gender_rank.index += 1
Comedy_gender_rank = Comedy_gender_rank.rename_axis("Rank")
Comedy_gender_rank

,Male,Female
Rank,,
1,Liar Liar (1997),Liar Liar (1997)
2,Toy Story (1995),Toy Story (1995)
3,Back to the Future (1985),"Full Monty, The (1997)"
4,Monty Python and the Holy Grail (1974),"Truth About Cats & Dogs, The (1996)"
5,Forrest Gump (1994),Willy Wonka and the Chocolate Factory (1971)
...,...,...
501,Sudden Manhattan (1996),"Wife, The (1995)"
502,Hana-bi (1997),Chairman of the Board (1998)
503,"Big One, The (1997)","Favor, The (1994)"
504,Wedding Bell Blues (1996),Getting Away With Murder (1996)
505,Tainted (1998),You So Crazy (1994)

In [123]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Crime, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [124]:
#man

In [125]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Crime, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [126]:
#woman

In [127]:
Crime_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Crime_gender_rank = Crime_gender_rank.reset_index(drop=True)
Crime_gender_rank.index += 1
Crime_gender_rank = Crime_gender_rank.rename_axis("Rank")
Crime_gender_rank

                            Male                              Female
Rank
1                   Fargo (1996)                        Fargo (1996)
2            Pulp Fiction (1994)               Godfather, The (1972)
3          Godfather, The (1972)                 Pulp Fiction (1994)
4       L.A. Confidential (1997)            L.A. Confidential (1997)
5     Usual Suspects, The (1995)                   Sting, The (1973)
...                          ...                                 ...
105        Lashou shentan (1992)         Angel on My Shoulder (1946)
106              Deceiver (1997)  Killer: A Journal of Murder (1995)
107           Normal Life (1996)                 Mad Dog Time (1996)
108               Hana-bi (1997)           He Walked by Night (1948)
109     MURDER and murder (1996)             King of New York (1990)

[109 rows x 2 columns]

In [128]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Documentary, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [129]:
#man

In [130]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Documentary, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [131]:
#woman

In [132]:
Documentary_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Documentary_gender_rank = Documentary_gender_rank.reset_index(drop=True)
Documentary_gender_rank.index += 1
Documentary_gender_rank = Documentary_gender_rank.rename_axis("Rank")
Documentary_gender_rank

,Male,Female
Rank,,
1,Hoop Dreams (1994),Hoop Dreams (1994)
2,Crumb (1994),Crumb (1994)
3,Koyaanisqatsi (1983),Looking for Richard (1996)
4,"Celluloid Closet, The (1995)","Celluloid Closet, The (1995)"
5,Looking for Richard (1996),When We Were Kings (1996)
6,When We Were Kings (1996),Paris Is Burning (1990)
7,"Thin Blue Line, The (1988)",Koyaanisqatsi (1983)
8,"Fast, Cheap & Out of Control (1997)",Anne Frank Remembered (1995)
9,Microcosmos: Le peuple de l'herbe (1996),"Fast, Cheap & Out of Control (1997)"
10,Paris Is Burning (1990),Paradise Lost: The Child Murders at Robin Hood...
11,Thirty-Two Short Films About Glenn Gould (1993),Madonna: Truth or Dare (1991)
12,Paradise Lost: The Child Murders at Robin Hood...,Unzipped (1995)
13,"Haunted World of Edward D. Wood Jr., The (1995)","Thin Blue Line, The (1988)"
14,Anne Frank Remembered (1995),Heidi Fleiss: Hollywood Madam (1995)
15,Madonna: Truth or Dare (1991),"War Room, The (1993)"
16,Wonderland (1997),Across the Sea of Time (1995)
17,Heidi Fleiss: Hollywood Madam (1995),Man of the Year (1995)
18,"Wonderful, Horrible Life of Leni Riefenstahl, ...",Thirty-Two Short Films About Glenn Gould (1993)
19,"Endless Summer 2, The (1994)","Haunted World of Edward D. Wood Jr., The (1995)"
20,"War Room, The (1993)",Rhyme & Reason (1997)
21,Year of the Horse (1997),"Endless Summer 2, The (1994)"
22,Ayn Rand: A Sense of Life (1997),American Dream (1990)
23,Man of the Year (1995),Nico Icon (1995)
24,Unzipped (1995),Brother Minister: The Assassination of Malcolm...
25,"Perfect Candidate, A (1996)",Microcosmos: Le peuple de l'herbe (1996)
26,Rhyme & Reason (1997),Grateful Dead (1995)
27,Maya Lin: A Strong Clear Vision (1994),"Wonderful, Horrible Life of Leni Riefenstahl, ..."
28,Brother Minister: The Assassination of Malcolm...,Jupiter's Wife (1994)
29,"Last Klezmer: Leopold Kozlowski, His Life and ...",Year of the Horse (1997)
30,Grateful Dead (1995),Ayn Rand: A Sense of Life (1997)
31,"Line King: Al Hirschfeld, The (1996)",Carmen Miranda: Bananas Is My Business (1994)
32,Catwalk (1995),Catwalk (1995)
33,"Leopard Son, The (1996)","Last Klezmer: Leopold Kozlowski, His Life and ..."
34,"Show, The (1995)",Maya Lin: A Strong Clear Vision (1994)
35,"Gate of Heavenly Peace, The (1995)","Show, The (1995)"
36,JLG/JLG - autoportrait de dÃ©cembre (1994),Tigrero: A Film That Was Never Made (1994)
37,Carmen Miranda: Bananas Is My Business (1994),"Eye of Vichy, The (Oeil de Vichy, L') (1993)"
38,Paris Was a Woman (1995),Everest (1998)
39,Marlene Dietrich: Shadow and Light (1996),Wonderland (1997)
40,Fire on the Mountain (1996),Dadetown (1995)
41,Across the Sea of Time (1995),"Big One, The (1997)"
42,"Great Day in Harlem, A (1994)",Fire on the Mountain (1996)
43,Everest (1998),"Great Day in Harlem, A (1994)"
44,Jupiter's Wife (1994),"Perfect Candidate, A (1996)"
45,Tigrero: A Film That Was Never Made (1994),Paris Was a Woman (1995)
46,"Eye of Vichy, The (Oeil de Vichy, L') (1993)",Marlene Dietrich: Shadow and Light (1996)
47,American Dream (1990),"Leopard Son, The (1996)"
48,Nico Icon (1995),JLG/JLG - autoportrait de dÃ©cembre (1994)
49,Dadetown (1995),"Gate of Heavenly Peace, The (1995)"
50,"Big One, The (1997)","Line King: Al Hirschfeld, The (1996)"

In [133]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Drama, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [134]:
#man

In [135]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Drama, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [136]:
#woman

In [137]:
Drama_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Drama_gender_rank = Drama_gender_rank.reset_index(drop=True)
Drama_gender_rank.index += 1
Drama_gender_rank = Drama_gender_rank.rename_axis("Rank")
Drama_gender_rank

                             Male                                     Female
Rank
1                    Fargo (1996)                English Patient, The (1996)
2                  Contact (1997)                             Contact (1997)
3     English Patient, The (1996)                               Fargo (1996)
4           Twelve Monkeys (1995)                       Jerry Maguire (1996)
5             Pulp Fiction (1994)                      Godfather, The (1972)
...                           ...                                        ...
721                   Ripe (1996)                      Sunchaser, The (1996)
722         Next Step, The (1995)                    War at Home, The (1996)
723      MURDER and murder (1996)                          Mat' i syn (1997)
724     Further Gesture, A (1996)                       Sliding Doors (1998)
725          Sweet Nothing (1995)  Scream of Stone (Schrei aus Stein) (1991)

[725 rows x 2 columns]

In [138]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Fantasy, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [139]:
#man

In [140]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Fantasy, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [141]:
#woman

In [142]:
Fantasy_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Fantasy_gender_rank = Fantasy_gender_rank.reset_index(drop=True)
Fantasy_gender_rank.index += 1
Fantasy_gender_rank = Fantasy_gender_rank.rename_axis("Rank")
Fantasy_gender_rank

,Male,Female
Rank,,
1,E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982)
2,"Nutty Professor, The (1996)","Nutty Professor, The (1996)"
3,Dragonheart (1996),Dragonheart (1996)
4,"Mask, The (1994)",Jumanji (1995)
5,Space Jam (1996),"Mask, The (1994)"
6,Jumanji (1995),Heavenly Creatures (1994)
7,"20,000 Leagues Under the Sea (1954)",Space Jam (1996)
8,Heavenly Creatures (1994),Flubber (1997)
9,Flubber (1997),"20,000 Leagues Under the Sea (1954)"
10,"Indian in the Cupboard, The (1995)",FairyTale: A True Story (1997)
11,Escape to Witch Mountain (1975),Drop Dead Fred (1991)
12,FairyTale: A True Story (1997),"Kid in King Arthur's Court, A (1995)"
13,Bogus (1996),"Indian in the Cupboard, The (1995)"
14,"Kid in King Arthur's Court, A (1995)",Escape to Witch Mountain (1975)
15,Drop Dead Fred (1991),Bogus (1996)
16,"NeverEnding Story III, The (1994)","Pagemaster, The (1994)"
17,Warriors of Virtue (1997),"NeverEnding Story III, The (1994)"
18,"Pagemaster, The (1994)",Kazaam (1996)
19,Kazaam (1996),Warriors of Virtue (1997)
20,Star Kid (1997),"Simple Wish, A (1997)"
21,"Simple Wish, A (1997)","Hungarian Fairy Tale, A (1987)"
22,"Hungarian Fairy Tale, A (1987)",Star Kid (1997)

In [143]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(FilmNoir, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [144]:
#man

In [145]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(FilmNoir, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [146]:
#woman

In [147]:
FilmNoir_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
FilmNoir_gender_rank = FilmNoir_gender_rank.reset_index(drop=True)
FilmNoir_gender_rank.index += 1
FilmNoir_gender_rank = FilmNoir_gender_rank.rename_axis("Rank")
FilmNoir_gender_rank

                                  Male                            Female
Rank
1                  Blade Runner (1982)          L.A. Confidential (1997)
2             L.A. Confidential (1997)               Blade Runner (1982)
3                     Chinatown (1974)        Maltese Falcon, The (1941)
4     Manchurian Candidate, The (1962)                  Chinatown (1974)
5           Maltese Falcon, The (1941)                  Cape Fear (1962)
6                 Grifters, The (1990)  Manchurian Candidate, The (1962)
7              Mulholland Falls (1996)               Sunset Blvd. (1950)
8                     Cape Fear (1962)             Big Sleep, The (1946)
9                       Hoodlum (1997)                    Hoodlum (1997)
10               Big Sleep, The (1946)              Grifters, The (1990)
11        Devil in a Blue Dress (1995)           Mulholland Falls (1996)
12                 Sunset Blvd. (1950)      Devil in a Blue Dress (1995)
13                    Notorious (1946)                      Laura (1944)
14                            M (1931)                  Notorious (1946)
15                        Laura (1944)                          M (1931)
16                Touch of Evil (1958)              Touch of Evil (1958)
17                    Dark City (1998)                  Dark City (1998)
18                     Palmetto (1998)                   Palmetto (1998)
19             Murder, My Sweet (1944)                     Suture (1993)
20                    Crossfire (1947)           Murder, My Sweet (1944)
21                       Suture (1993)                      T-Men (1947)
22                     Raw Deal (1948)                  Crossfire (1947)
23           He Walked by Night (1948)                   Raw Deal (1948)
24                        T-Men (1947)         He Walked by Night (1948)

In [148]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Horror, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [149]:
#man

In [150]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Horror, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [151]:
#woman

In [152]:
Horror_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Horror_gender_rank = Horror_gender_rank.reset_index(drop=True)
Horror_gender_rank.index += 1
Horror_gender_rank = Horror_gender_rank.rename_axis("Rank")
Horror_gender_rank

,Male,Female
Rank,,
1,Scream (1996),Scream (1996)
2,Alien (1979),Jaws (1975)
3,Jaws (1975),Psycho (1960)
4,Psycho (1960),Alien (1979)
5,Young Frankenstein (1974),"Devil's Advocate, The (1997)"
...,...,...
88,Beyond Bedlam (1993),Nightwatch (1997)
89,Nightwatch (1997),"Fear, The (1995)"
90,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...
91,Nightwatch (1997),"Machine, The (1994)"
92,"Fear, The (1995)",Nightwatch (1997)

In [153]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Musical, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [154]:
#man

In [155]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Musical, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [156]:
#woman

In [157]:
Musical_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Musical_gender_rank = Musical_gender_rank.reset_index(drop=True)
Musical_gender_rank.index += 1
Musical_gender_rank = Musical_gender_rank.rename_axis("Rank")
Musical_gender_rank

,Male,Female
Rank,,
1,"Blues Brothers, The (1980)",Evita (1996)
2,"Wizard of Oz, The (1939)","Sound of Music, The (1965)"
3,Evita (1996),"Wizard of Oz, The (1939)"
4,Aladdin (1992),"Lion King, The (1994)"
5,"Lion King, The (1994)",Beauty and the Beast (1991)
6,This Is Spinal Tap (1984),Aladdin (1992)
7,"Sound of Music, The (1965)",Grease (1978)
8,Beauty and the Beast (1991),Mary Poppins (1964)
9,Fantasia (1940),Everyone Says I Love You (1996)
10,Snow White and the Seven Dwarfs (1937),Fantasia (1940)
11,Mary Poppins (1964),Snow White and the Seven Dwarfs (1937)
12,Grease (1978),"Blues Brothers, The (1980)"
13,Everyone Says I Love You (1996),Cinderella (1950)
14,"Nightmare Before Christmas, The (1993)",My Fair Lady (1964)
15,Singin' in the Rain (1952),This Is Spinal Tap (1984)
16,"Hunchback of Notre Dame, The (1996)",Dirty Dancing (1987)
17,Dumbo (1941),Singin' in the Rain (1952)
18,James and the Giant Peach (1996),"Hunchback of Notre Dame, The (1996)"
19,Pink Floyd - The Wall (1982),James and the Giant Peach (1996)
20,Cinderella (1950),"Nightmare Before Christmas, The (1993)"
21,My Fair Lady (1964),Dumbo (1941)
22,Muppet Treasure Island (1996),Alice in Wonderland (1951)
23,Dirty Dancing (1987),Anastasia (1997)
24,Victor/Victoria (1982),Pink Floyd - The Wall (1982)
25,Alice in Wonderland (1951),Bedknobs and Broomsticks (1971)
26,Hercules (1997),Victor/Victoria (1982)
27,Anastasia (1997),Muppet Treasure Island (1996)
28,Pocahontas (1995),Hercules (1997)
29,Joe's Apartment (1996),Pete's Dragon (1977)
30,"American in Paris, An (1951)","American in Paris, An (1951)"
31,Tank Girl (1995),"Doors, The (1991)"
32,"Doors, The (1991)",Pocahontas (1995)
33,Bedknobs and Broomsticks (1971),Gigi (1958)
34,Gigi (1958),Grease 2 (1982)
35,Pete's Dragon (1977),Meet Me in St. Louis (1944)
36,"Great Race, The (1965)",Selena (1997)
37,Cats Don't Dance (1997),Blues Brothers 2000 (1998)
38,Meet Me in St. Louis (1944),Cats Don't Dance (1997)
39,Blues Brothers 2000 (1998),Joe's Apartment (1996)
40,"Three Caballeros, The (1945)",Spice World (1997)
41,Spice World (1997),Tank Girl (1995)
42,Top Hat (1935),"Great Race, The (1965)"
43,Backbeat (1993),Funny Face (1957)
44,"MisÃ©rables, Les (1995)","Umbrellas of Cherbourg, The (Parapluies de Che..."
45,"Umbrellas of Cherbourg, The (Parapluies de Che...",Top Hat (1935)
46,Farinelli: il castrato (1994),Shall We Dance? (1937)
47,"Inspector General, The (1949)","MisÃ©rables, Les (1995)"
48,Funny Face (1957),"Inspector General, The (1949)"
49,Grease 2 (1982),"Gay Divorcee, The (1934)"
50,"Gay Divorcee, The (1934)",Backbeat (1993)
51,All Dogs Go to Heaven 2 (1996),"Three Caballeros, The (1945)"
52,Shall We Dance? (1937),All Dogs Go to Heaven 2 (1996)
53,Selena (1997),Farinelli: il castrato (1994)
54,"Band Wagon, The (1953)","Band Wagon, The (1953)"
55,Madame Butterfly (1995),Madame Butterfly (1995)
56,"Damsel in Distress, A (1937)","Damsel in Distress, A (1937)"

In [158]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Mystery, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [159]:
#man

In [160]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Mystery, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [161]:
#woman

In [162]:
Mystery_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Mystery_gender_rank = Mystery_gender_rank.reset_index(drop=True)
Mystery_gender_rank.index += 1
Mystery_gender_rank = Mystery_gender_rank.rename_axis("Rank")
Mystery_gender_rank

                               Male                         Female
Rank
1        Mission: Impossible (1996)       Conspiracy Theory (1997)
2          L.A. Confidential (1997)     Mission: Impossible (1996)
3          Conspiracy Theory (1997)                 Amadeus (1984)
4      2001: A Space Odyssey (1968)       L.A. Confidential (1997)
5                    Amadeus (1984)          Murder at 1600 (1997)
...                             ...                            ...
57           Underneath, The (1995)  Woman in Question, The (1950)
58                  Power 98 (1995)       MURDER and murder (1996)
59         Lady of Burlesque (1943)    Hour of the Pig, The (1993)
60    Woman in Question, The (1950)                Power 98 (1995)
61         MURDER and murder (1996)       Lady of Burlesque (1943)

[61 rows x 2 columns]

In [163]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Romance, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [164]:
#man

In [165]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Romance, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [166]:
#woman

In [167]:
Romance_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Romance_gender_rank = Romance_gender_rank.reset_index(drop=True)
Romance_gender_rank.index += 1
Romance_gender_rank = Romance_gender_rank.rename_axis("Rank")
Romance_gender_rank

                                        Male                       Female
Rank
1                           Star Wars (1977)  English Patient, The (1996)
2                  Return of the Jedi (1983)             Star Wars (1977)
3                English Patient, The (1996)    Return of the Jedi (1983)
4            Empire Strikes Back, The (1980)         Jerry Maguire (1996)
5                       Jerry Maguire (1996)               Titanic (1997)
...                                      ...                          ...
243                         Mr. Jones (1993)               Witness (1985)
244                     Sliding Doors (1998)             Hugo Pool (1997)
245   Promise, The (Versprechen, Das) (1994)            Favor, The (1994)
246             Vermont Is For Lovers (1992)             B. Monkey (1998)
247                          Liebelei (1933)         Sliding Doors (1998)

[247 rows x 2 columns]

In [168]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(SciFi, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [169]:
#man

In [170]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(SciFi, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [171]:
#woman

In [172]:
SciFi_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
SciFi_gender_rank = SciFi_gender_rank.reset_index(drop=True)
SciFi_gender_rank.index += 1
SciFi_gender_rank = SciFi_gender_rank.rename_axis("Rank")
SciFi_gender_rank

,Male,Female
Rank,,
1,Star Wars (1977),Star Wars (1977)
2,Return of the Jedi (1983),Contact (1997)
3,Contact (1997),Return of the Jedi (1983)
4,Independence Day (ID4) (1996),Independence Day (ID4) (1996)
5,Twelve Monkeys (1995),"Empire Strikes Back, The (1980)"
...,...,...
97,No Escape (1994),"Visitors, The (Visiteurs, Les) (1993)"
98,Star Kid (1997),Time Tracers (1995)
99,Time Tracers (1995),Solo (1996)
100,"Visitors, The (Visiteurs, Les) (1993)",Star Kid (1997)
101,Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995)

In [173]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Thriller, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [174]:
#man

In [175]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Thriller, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [176]:
#woman

In [177]:
Thriller_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Thriller_gender_rank = Thriller_gender_rank.reset_index(drop=True)
Thriller_gender_rank.index += 1
Thriller_gender_rank = Thriller_gender_rank.rename_axis("Rank")
Thriller_gender_rank

                                  Male                            Female
Rank
1                         Fargo (1996)                     Scream (1996)
2                        Scream (1996)              Air Force One (1997)
3                 Air Force One (1997)                      Fargo (1996)
4     Silence of the Lambs, The (1991)  Silence of the Lambs, The (1991)
5                     Rock, The (1996)                  Rock, The (1996)
...                                ...                               ...
247          Hostile Intentions (1994)         He Walked by Night (1948)
248                 Baton Rouge (1988)             Butterfly Kiss (1995)
249       Spanish Prisoner, The (1997)                       Hush (1998)
250                     Tainted (1998)                 Nightwatch (1997)
251                      Mirage (1995)                  B. Monkey (1998)

[251 rows x 2 columns]

In [178]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(War, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [179]:
#man

In [180]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(War, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [181]:
#woman

In [182]:
War_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
War_gender_rank = War_gender_rank.reset_index(drop=True)
War_gender_rank.index += 1
War_gender_rank = War_gender_rank.rename_axis("Rank")
War_gender_rank

,Male,Female
Rank,,
1,Star Wars (1977),"English Patient, The (1996)"
2,Return of the Jedi (1983),Star Wars (1977)
3,"English Patient, The (1996)",Return of the Jedi (1983)
4,Independence Day (ID4) (1996),Independence Day (ID4) (1996)
5,"Empire Strikes Back, The (1980)","Empire Strikes Back, The (1980)"
...,...,...
67,Underground (1995),Prisoner of the Mountains (Kavkazsky Plennik) ...
68,For the Moment (1994),Pharaoh's Army (1995)
69,Pharaoh's Army (1995),Land and Freedom (Tierra y libertad) (1995)
70,Land and Freedom (Tierra y libertad) (1995),Nothing Personal (1995)
71,Nothing Personal (1995),"Colonel Chabert, Le (1994)"

In [183]:
man = gender_3.groupby("gender").get_group("M")
man = pd.merge(Western, man, on="movie id", how="left")
man = man.sort_values(by="rating", ascending= False)
man = man.reset_index(drop=True)

In [184]:
#man

In [185]:
woman = gender_3.groupby("gender").get_group("F")
woman = pd.merge(Western, woman, on="movie id", how="left")
woman = woman.sort_values(by="rating", ascending= False)
woman = woman.reset_index(drop=True)

In [186]:
#woman

In [187]:
Western_gender_rank = pd.DataFrame({"Male":man["movie title"],
                           "Female":woman["movie title"]})
Western_gender_rank = Western_gender_rank.reset_index(drop=True)
Western_gender_rank.index += 1
Western_gender_rank = Western_gender_rank.rename_axis("Rank")
Western_gender_rank

,Male,Female
Rank,,
1,Dances with Wolves (1990),Dances with Wolves (1990)
2,Butch Cassidy and the Sundance Kid (1969),Butch Cassidy and the Sundance Kid (1969)
3,Unforgiven (1992),Unforgiven (1992)
4,"Good, The Bad and The Ugly, The (1966)",Legends of the Fall (1994)
5,"Magnificent Seven, The (1954)",Maverick (1994)
6,Maverick (1994),Tombstone (1993)
7,Young Guns (1988),"Magnificent Seven, The (1954)"
8,Tombstone (1993),High Noon (1952)
9,High Noon (1952),"Good, The Bad and The Ugly, The (1966)"
10,Legends of the Fall (1994),Young Guns (1988)
11,Last Man Standing (1996),Wyatt Earp (1994)
12,"Quick and the Dead, The (1995)","Apple Dumpling Gang, The (1975)"
13,"Wild Bunch, The (1969)",Dead Man (1995)
14,Young Guns II (1990),City Slickers II: The Legend of Curly's Gold (...
15,Wyatt Earp (1994),Last Man Standing (1996)
16,City Slickers II: The Legend of Curly's Gold (...,"Quick and the Dead, The (1995)"
17,Once Upon a Time in the West (1969),Young Guns II (1990)
18,Dead Man (1995),Once Upon a Time in the West (1969)
19,"Apple Dumpling Gang, The (1975)",Geronimo: An American Legend (1993)
20,Wild Bill (1995),Bad Girls (1994)
21,"Davy Crockett, King of the Wild Frontier (1955)","Wild Bunch, The (1969)"
22,Lightning Jack (1994),"Davy Crockett, King of the Wild Frontier (1955)"
23,Geronimo: An American Legend (1993),Wild Bill (1995)
24,Angel and the Badman (1947),Lightning Jack (1994)
25,Bad Girls (1994),Angel and the Badman (1947)
26,"Outlaw, The (1943)",Terror in a Texas Town (1958)
27,Terror in a Texas Town (1958),"Outlaw, The (1943)"

---

### A_3) number of ratings by each genre for occupations

In [188]:
occu_1 = gender_1

In [189]:
#occu_1

In [190]:
occu_2 = user[["user id", "occupation"]]

In [191]:
#occu_2

In [192]:
occu_3 = pd.merge(occu_2, occu_1, on="user id", how="left")
occu_3 = occu_3.groupby(["occupation", "movie id"], as_index=False)["rating"].count()

In [193]:
#occu_3

In [194]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(unknown, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [195]:
#administrator

In [196]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(unknown, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [197]:
#artist

In [198]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(unknown, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [199]:
#doctor

In [200]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(unknown, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [201]:
#educator

In [202]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(unknown, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [203]:
#engineer

In [204]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(unknown, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [205]:
#entertainment

In [206]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(unknown, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [207]:
#executive

In [208]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(unknown, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [209]:
#healthcare

In [210]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(unknown, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [211]:
#homemaker

In [212]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(unknown, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [213]:
#lawyer

In [214]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(unknown, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [215]:
#librarian

In [216]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(unknown, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [217]:
#marketing

In [218]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(unknown, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [219]:
#none

In [220]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(unknown, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [221]:
#other

In [222]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(unknown, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [223]:
#programmer

In [224]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(unknown, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [225]:
#retired

In [226]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(unknown, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [227]:
#salesman

In [228]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(unknown, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [229]:
#scientist

In [230]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(unknown, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [231]:
#student

In [232]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(unknown, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [233]:
#technician

In [234]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(unknown, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [235]:
#writer

In [236]:
unknown_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
unknown_occupation_rank = unknown_occupation_rank.reset_index(drop=True)
unknown_occupation_rank.index += 1
unknown_occupation_rank = unknown_occupation_rank.rename_axis("Rank")
unknown_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,unknown,unknown,unknown,unknown,unknown,unknown,Good Morning (1971),unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),unknown,Good Morning (1971),Good Morning (1971),Good Morning (1971),...,Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971),Good Morning (1971)

In [237]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Action, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [238]:
#administrator

In [239]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Action, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [240]:
#artist

In [241]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Action, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [242]:
#doctor

In [243]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Action, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [244]:
#educator

In [245]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Action, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [246]:
#engineer

In [247]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Action, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [248]:
#entertainment

In [249]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Action, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [250]:
#executive

In [251]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Action, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [252]:
#healthcare

In [253]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Action, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [254]:
#homemaker

In [255]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Action, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [256]:
#lawyer

In [257]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Action, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [258]:
#librarian

In [259]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Action, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [260]:
#marketing

In [261]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Action, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [262]:
#none

In [263]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Action, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [264]:
#other

In [265]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Action, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [266]:
#programmer

In [267]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Action, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [268]:
#retired

In [269]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Action, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [270]:
#salesman

In [271]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Action, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [272]:
#scientist

In [273]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Action, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [274]:
#student

In [275]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Action, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [276]:
#technician

In [277]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Action, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [278]:
#writer

In [279]:
Action_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Action_occupation_rank = Action_occupation_rank.reset_index(drop=True)
Action_occupation_rank.index += 1
Action_occupation_rank = Action_occupation_rank.rename_axis("Rank")
Action_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Star Wars (1977),Star Wars (1977),Air Force One (1997),Star Wars (1977),Star Wars (1977),Air Force One (1997),Star Wars (1977),Air Force One (1997),Air Force One (1997),Star Wars (1977),...,Air Force One (1997),Air Force One (1997),Star Wars (1977),Star Wars (1977),"Godfather, The (1972)","Godfather, The (1972)",Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977)
2,Return of the Jedi (1983),Return of the Jedi (1983),Titanic (1997),"Godfather, The (1972)",Return of the Jedi (1983),Heat (1995),Independence Day (ID4) (1996),Star Wars (1977),"Saint, The (1997)",Raiders of the Lost Ark (1981),...,Star Wars (1977),Star Trek: First Contact (1996),Air Force One (1997),Return of the Jedi (1983),Star Wars (1977),Star Wars (1977),Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983)
3,Air Force One (1997),"Fugitive, The (1993)",Men in Black (1997),Return of the Jedi (1983),Raiders of the Lost Ark (1981),Star Wars (1977),"Saint, The (1997)",Return of the Jedi (1983),Conspiracy Theory (1997),Air Force One (1997),...,Conspiracy Theory (1997),"Rock, The (1996)",Return of the Jedi (1983),Raiders of the Lost Ark (1981),Titanic (1997),Titanic (1997),"Godfather, The (1972)",Independence Day (ID4) (1996),Independence Day (ID4) (1996),Raiders of the Lost Ark (1981)
4,Independence Day (ID4) (1996),Raiders of the Lost Ark (1981),Star Trek: First Contact (1996),Air Force One (1997),Independence Day (ID4) (1996),Return of the Jedi (1983),"Rock, The (1996)",Independence Day (ID4) (1996),Titanic (1997),Braveheart (1995),...,"Saint, The (1997)",Independence Day (ID4) (1996),"Godfather, The (1972)",Star Trek: First Contact (1996),Men in Black (1997),Men in Black (1997),Independence Day (ID4) (1996),"Rock, The (1996)",Raiders of the Lost Ark (1981),"Godfather, The (1972)"
5,"Godfather, The (1972)","Godfather, The (1972)","Rock, The (1996)",Independence Day (ID4) (1996),Star Trek: First Contact (1996),"Rock, The (1996)",Men in Black (1997),"Godfather, The (1972)",Twister (1996),Return of the Jedi (1983),...,Dante's Peak (1997),Star Wars (1977),"Saint, The (1997)","Empire Strikes Back, The (1980)",Independence Day (ID4) (1996),Independence Day (ID4) (1996),Raiders of the Lost Ark (1981),Mission: Impossible (1996),"Empire Strikes Back, The (1980)",Air Force One (1997)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,Tokyo Fist (1995),Tokyo Fist (1995),Warriors of Virtue (1997),Tokyo Fist (1995),Warriors of Virtue (1997),Warriors of Virtue (1997),Tokyo Fist (1995),"Truth or Consequences, N.M. (1997)",Warriors of Virtue (1997),Warriors of Virtue (1997),...,Warriors of Virtue (1997),Warriors of Virtue (1997),"Truth or Consequences, N.M. (1997)",Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Lashou shentan (1992),Warriors of Virtue (1997),Warriors of Virtue (1997)
248,King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),Warriors of Virtue (1997),Tokyo Fist (1995),King of New York (1990),King of New York (1990),...,King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),"Truth or Consequences, N.M. (1997)",King of New York (1990),King of New York (1990)
249,Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),King of New York (1990),King of New York (1990),Men With Guns (1997),Men With Guns (1997),...,Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Men With Guns (1997),Tokyo Fist (1995),Men With Guns (1997),Men With Guns (1997)
250,Target (1995),Target (1995),Target (1995),Target (1995),Target (1995),Target (1995),Men With Guns (1997),Target (1995),Target (1995),Target (1995),...,Target (1995),Target (1995),Target (1995),Target (1995),Target (1995),Target (1995),Target (1995),Men With Guns (1997),Target (1995),Target (1995)
251,Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Target (1995),Mirage (1995),Mirage (1995),Mirage (1995),...,Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995)

In [280]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Adventure, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [281]:
#administrator

In [282]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Adventure, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [283]:
#artist

In [284]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Adventure, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [285]:
#doctor

In [286]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Adventure, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [287]:
#educator

In [288]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Adventure, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [289]:
#engineer

In [290]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Adventure, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [291]:
#entertainment

In [292]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Adventure, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [293]:
#executive

In [294]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Adventure, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [295]:
#healthcare

In [296]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Adventure, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [297]:
#homemaker

In [298]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Adventure, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [299]:
#lawyer

In [300]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Adventure, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [301]:
#librarian

In [302]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Adventure, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [303]:
#marketing

In [304]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Adventure, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [305]:
#none

In [306]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Adventure, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [307]:
#other

In [308]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Adventure, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [309]:
#programmer

In [310]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Adventure, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [311]:
#retired

In [312]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Adventure, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [313]:
#salesman

In [314]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Adventure, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [315]:
#scientist

In [316]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Adventure, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [317]:
#student

In [318]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Adventure, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [319]:
#technician

In [320]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Adventure, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [321]:
#writer

In [322]:
Adventure_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Adventure_occupation_rank = Adventure_occupation_rank.reset_index(drop=True)
Adventure_occupation_rank.index += 1
Adventure_occupation_rank = Adventure_occupation_rank.rename_axis("Rank")
Adventure_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Star Wars (1977),Star Wars (1977),Men in Black (1997),Star Wars (1977),Star Wars (1977),"Rock, The (1996)",Star Wars (1977),Star Wars (1977),Spawn (1997),Star Wars (1977),...,Star Wars (1977),Star Trek: First Contact (1996),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977)
2,Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983),Starship Troopers (1997),"Rock, The (1996)",Return of the Jedi (1983),Mission: Impossible (1996),Raiders of the Lost Ark (1981),...,Return of the Jedi (1983),"Rock, The (1996)",Return of the Jedi (1983),Return of the Jedi (1983),Men in Black (1997),Men in Black (1997),Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983)
3,Raiders of the Lost Ark (1981),Raiders of the Lost Ark (1981),"Rock, The (1996)",Raiders of the Lost Ark (1981),Raiders of the Lost Ark (1981),Star Trek: First Contact (1996),Mission: Impossible (1996),Raiders of the Lost Ark (1981),Twister (1996),Return of the Jedi (1983),...,Raiders of the Lost Ark (1981),Star Wars (1977),Raiders of the Lost Ark (1981),Raiders of the Lost Ark (1981),Indiana Jones and the Last Crusade (1989),Indiana Jones and the Last Crusade (1989),Raiders of the Lost Ark (1981),"Rock, The (1996)",Raiders of the Lost Ark (1981),Raiders of the Lost Ark (1981)
4,"Empire Strikes Back, The (1980)",Willy Wonka and the Chocolate Factory (1971),Twister (1996),"Princess Bride, The (1987)",Star Trek: First Contact (1996),Return of the Jedi (1983),Willy Wonka and the Chocolate Factory (1971),"Rock, The (1996)","Ghost and the Darkness, The (1996)",Men in Black (1997),...,Jurassic Park (1993),Willy Wonka and the Chocolate Factory (1971),"Rock, The (1996)",Star Trek: First Contact (1996),"Rock, The (1996)","Rock, The (1996)",Willy Wonka and the Chocolate Factory (1971),Mission: Impossible (1996),Star Trek: First Contact (1996),Men in Black (1997)
5,Mission: Impossible (1996),"Princess Bride, The (1987)",Willy Wonka and the Chocolate Factory (1971),Star Trek: First Contact (1996),"Rock, The (1996)",Star Wars (1977),Men in Black (1997),Star Trek: First Contact (1996),Willy Wonka and the Chocolate Factory (1971),Starship Troopers (1997),...,Indiana Jones and the Last Crusade (1989),Return of the Jedi (1983),"Empire Strikes Back, The (1980)","Empire Strikes Back, The (1980)",Return of the Jedi (1983),Return of the Jedi (1983),Star Trek: First Contact (1996),"Empire Strikes Back, The (1980)","Empire Strikes Back, The (1980)","Princess Bride, The (1987)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,"Good Man in Africa, A (1994)",Gold Diggers: The Secret of Bear Mountain (1995),Far From Home: The Adventures of Yellow Dog (1...,Golden Earrings (1947),Far From Home: The Adventures of Yellow Dog (1...,Far From Home: The Adventures of Yellow Dog (1...,Far From Home: The Adventures of Yellow Dog (1...,Surviving the Game (1994),Far From Home: The Adventures of Yellow Dog (1...,"Good Man in Africa, A (1994)",...,"Good Man in Africa, A (1994)",Far From Home: The Adventures of Yellow Dog (1...,Gold Diggers: The Secret of Bear Mountain (1995),Gold Diggers: The Secret of Bear Mountain (1995),Far From Home: The Adventures of Yellow Dog (1...,Far From Home: The Adventures of Yellow Dog (1...,Wings of Courage (1995),Time Tracers (1995),Far From Home: The Adventures of Yellow Dog (1...,"Good Man in Africa, A (1994)"
132,Far From Home: The Adventures of Yellow Dog (1...,Wings of Courage (1995),"Amazing Panda Adventure, The (1995)",Wings of Courage (1995),"Amazing Panda Adventure, The (1995)","Amazing Panda Adventure, The (1995)","Amazing Panda Adventure, The (1995)",Golden Earrings (1947),"Amazing Panda Adventure, The (1995)",Far From Home: The Adventures of Yellow Dog (1...,...,Far From Home: The Adventures of Yellow Dog (1...,"Amazing Panda Adventure, The (1995)",Wings of Courage (1995),Wings of Courage (1995),"Amazing Panda Adventure, The (1995)","Amazing Panda Adventure, The (1995)","Good Man in Africa, A (1994)",Star Kid (1997),"Amazing Panda Adventure, The (1995)",Far From Home: The Adventures of Yellow Dog (1...
133,"Amazing Panda Adventure, The (1995)","Good Man in Africa, A (1994)","Secret Adventures of Tom Thumb, The (1993)","Good Man in Africa, A (1994)","Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)",Wings of Courage (1995),"Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)",...,"Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)","Good Man in Africa, A (1994)","Good Man in Africa, A (1994)","Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)",Far From Home: The Adventures of Yellow Dog (1...,Golden Earrings (1947),"Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)"
134,"Secret Adventures of Tom Thumb, The (1993)",Far From Home: The Adventures of Yellow Dog (1...,Buddy (1997),Far From Home: The Adventures of Yellow Dog (1...,Buddy (1997),Buddy (1997),Buddy (1997),"Good Man in Africa, A (1994)",Buddy (1997),Buddy (1997),...,Buddy (1997),Buddy (1997),"Secret Adventures of Tom Thumb, The (1993)","Amazing Panda Adventure, The (1995)",Buddy (1997),Buddy (1997),"Amazing Panda Adventure, The (1995)",Wings of Courage (1995),Buddy (1997),Buddy (1997)
135,Buddy (1997),"Secret Adventures of Tom Thumb, The (1993)",Warriors of Virtue (1997),"Secret Adventures of Tom Thumb, The (1993)",Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Buddy (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),...,Warriors of Virtue (1997),Warriors of Virtue (1997),Buddy (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Buddy (1997),Warriors of Virtue (1997),Warriors of Virtue (1997)

In [323]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Animation, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [324]:
#administrator

In [325]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Animation, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [326]:
#artist

In [327]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Animation, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [328]:
#doctor

In [329]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Animation, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [330]:
#educator

In [331]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Animation, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [332]:
#engineer

In [333]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Animation, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [334]:
#entertainment

In [335]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Animation, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [336]:
#executive

In [337]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Animation, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [338]:
#healthcare

In [339]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Animation, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [340]:
#homemaker

In [341]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Animation, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [342]:
#lawyer

In [343]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Animation, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [344]:
#librarian

In [345]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Animation, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [346]:
#marketing

In [347]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Animation, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [348]:
#none

In [349]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Animation, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [350]:
#other

In [351]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Animation, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [352]:
#programmer

In [353]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Animation, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [354]:
#retired

In [355]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Animation, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [356]:
#salesman

In [357]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Animation, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [358]:
#scientist

In [359]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Animation, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [360]:
#student

In [361]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Animation, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [362]:
#technician

In [363]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Animation, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [364]:
#writer

In [365]:
Animation_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Animation_occupation_rank = Animation_occupation_rank.reset_index(drop=True)
Animation_occupation_rank.index += 1
Animation_occupation_rank = Animation_occupation_rank.rename_axis("Rank")
Animation_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),...,Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995)
2,Fantasia (1940),Fantasia (1940),Cinderella (1950),"Lion King, The (1994)",Aladdin (1992),Beavis and Butt-head Do America (1996),Space Jam (1996),"Lion King, The (1994)",Aladdin (1992),Snow White and the Seven Dwarfs (1937),...,Anastasia (1997),James and the Giant Peach (1996),"Lion King, The (1994)",Aladdin (1992),"Hunchback of Notre Dame, The (1996)","Hunchback of Notre Dame, The (1996)",Fantasia (1940),Aladdin (1992),"Lion King, The (1994)",Beavis and Butt-head Do America (1996)
3,"Lion King, The (1994)",Beauty and the Beast (1991),Aladdin (1992),Beauty and the Beast (1991),"Lion King, The (1994)",Aladdin (1992),"Lion King, The (1994)",Pinocchio (1940),James and the Giant Peach (1996),Pinocchio (1940),...,Beauty and the Beast (1991),Beauty and the Beast (1991),Aladdin (1992),Fantasia (1940),Pinocchio (1940),Pinocchio (1940),Beavis and Butt-head Do America (1996),Beauty and the Beast (1991),Beavis and Butt-head Do America (1996),Snow White and the Seven Dwarfs (1937)
4,Beauty and the Beast (1991),Snow White and the Seven Dwarfs (1937),Snow White and the Seven Dwarfs (1937),Fantasia (1940),Fantasia (1940),Space Jam (1996),Beavis and Butt-head Do America (1996),Dumbo (1941),Anastasia (1997),Fantasia (1940),...,Snow White and the Seven Dwarfs (1937),Aladdin (1992),Beauty and the Beast (1991),Beauty and the Beast (1991),Dumbo (1941),Dumbo (1941),Snow White and the Seven Dwarfs (1937),"Lion King, The (1994)",Aladdin (1992),Beauty and the Beast (1991)
5,Snow White and the Seven Dwarfs (1937),James and the Giant Peach (1996),Heavy Metal (1981),Snow White and the Seven Dwarfs (1937),Beauty and the Beast (1991),"Lion King, The (1994)",Aladdin (1992),Snow White and the Seven Dwarfs (1937),Beauty and the Beast (1991),Aladdin (1992),...,"Close Shave, A (1995)","Lion King, The (1994)",Snow White and the Seven Dwarfs (1937),"Wrong Trousers, The (1993)",James and the Giant Peach (1996),James and the Giant Peach (1996),Beauty and the Beast (1991),Beavis and Butt-head Do America (1996),Snow White and the Seven Dwarfs (1937),"Lion King, The (1994)"
6,Cinderella (1950),Aladdin (1992),Wallace & Gromit: The Best of Aardman Animatio...,Aladdin (1992),Dumbo (1941),Cinderella (1950),James and the Giant Peach (1996),Beauty and the Beast (1991),"Hunchback of Notre Dame, The (1996)",Heavy Metal (1981),...,Dumbo (1941),Space Jam (1996),Cinderella (1950),"Lion King, The (1994)",Aladdin (1992),Aladdin (1992),Space Jam (1996),Snow White and the Seven Dwarfs (1937),Heavy Metal (1981),Fantasia (1940)
7,Aladdin (1992),"Lion King, The (1994)","Wrong Trousers, The (1993)",Cinderella (1950),Snow White and the Seven Dwarfs (1937),"Close Shave, A (1995)","Hunchback of Notre Dame, The (1996)",Aladdin (1992),Space Jam (1996),Beauty and the Beast (1991),...,"Lion King, The (1994)",Anastasia (1997),"Hunchback of Notre Dame, The (1996)",Dumbo (1941),Snow White and the Seven Dwarfs (1937),Snow White and the Seven Dwarfs (1937),"Lion King, The (1994)",Fantasia (1940),Beauty and the Beast (1991),Aladdin (1992)
8,Pinocchio (1940),Cinderella (1950),Beavis and Butt-head Do America (1996),Dumbo (1941),"Wrong Trousers, The (1993)",Hercules (1997),Beauty and the Beast (1991),James and the Giant Peach (1996),Hercules (1997),James and the Giant Peach (1996),...,Fantasia (1940),Snow White and the Seven Dwarfs (1937),Fantasia (1940),"Close Shave, A (1995)","Wrong Trousers, The (1993)","Wrong Trousers, The (1993)",Heavy Metal (1981),"Hunchback of Notre Dame, The (1996)",Winnie the Pooh and the Blustery Day (1968),Alice in Wonderland (1951)
9,Dumbo (1941),Dumbo (1941),"Close Shave, A (1995)","Hunchback of Notre Dame, The (1996)","Close Shave, A (1995)",Dumbo (1941),Fantasia (1940),Fantasia (1940),"Lion King, The (1994)",Oliver & Company (1988),...,Cinderella (1950),Dumbo (1941),Beavis and Butt-head Do America (1996),Snow White and the Seven Dwarfs (1937),Beauty and the Beast (1991),Beauty and the Beast (1991),Wallace & Gromit: The Best of Aardman Animatio...,Cinderella (1950),"Wrong Trousers, The (1993)","Close Shave, A (1995)"
10,James and the Giant Peach (1996),"Hunchback of Notre Dame, The (1996)","Lion King, The (1994)","Wrong Trousers, The (1993)",Beavis and Butt-head Do America (1996),James and the Giant Peach (1996),"Close Shave, A (1995)",Alice in Wonderland (1951),Snow White and the Seven Dwarfs (1937),Balto (1995),...,James and the Giant Peach (1996),Alice in Wonderland (1951),"Wrong Trousers, The (1993)",Beavis and Butt-head Do America (1996),"Lion King, The (1994)","Lion King, The (1994)","Wrong Trousers, The (1993)",Dumbo (1941),Fantasia (1940),James and the Giant Peach (1996)
11,Wallace & Gromit: The Best of Aardman Animatio...,"Close Shave, A (1995)",Fantasia (1940),James and the Giant Peach (1996),Pinocchio (1940),Fantasia (1940),Cinderella (1950),Cinderella (1950),Heavy Metal (1981),Pocahontas (1995),...,Aladdin (1992),Cinderella (1950),Dumbo (1941),Cinderella (1950),Fantasia (1940),Fantasia (1940),"Close Shave, A (1995)",Pinocchio (1940),"Close Shave, A (1995)","Hunchback of Notre Dame, The (1996)"
12,Alice in Wonderland (1951),"Aristocats, The (1970)",James and the Giant Peach (1996),"Close Shave, A (1995)",James and the Giant Peach (1996),"Grand Day Out, A (1992)",Snow White and the Seven Dwarfs (1937),Beavis and Butt-head Do America (1996),"Aristocats, The (1970)",Anastasia (1997),...,Pinocchio (1940),Pinocchio (1940),Pinocchio (1940),Space Jam (1996),Cats Don't Dance (1997),Cats Don't Dance (1997),Cinderella (1950),Alice in Wonderland (1951),Akira (1988),Hercules (1997)
13,Winnie the Pooh and the Blustery Day (1968),Heavy Metal (1981),Dumbo (1941),Winnie the Pooh and the Blustery Day (1968),Winnie the Pooh and the Blustery Day (1968),"Wrong Trousers, The (1993)",Cats Don't Dance (1997),"Hunchback of Notre Dame, The (1996)",All Dogs Go to Heaven 2 (1996),Cinderella (1950),...,Pocahontas (1995),Beavis and Butt-head Do America (1996),James and the Giant Peach (1996),"Hunchback of Notre Dame, The (1996)","Sword in the Stone, The (1963)","Sword in the Stone, The (1963)",Aladdin (1992),"Sword in the Stone, The (1963)","Fox and the Hound, The (1981)",Space Jam (1996)
14,"Hunchback of Notre Dame, The (1996)",Hercules (1997),Anastasia (1997),"Sword in the Stone, The (1963)","Hunchback of Notre Dame, The (1996)",Wallace & Gromit: The Best of Aardman Animatio...,"Grand Day Out, A (1992)",Balto (1995),Wallace & Gromit: The Best of Aardman Animatio...,"Transformers: The Movie, The (1986)",...,Balto (1995),"Transformers: The Movie, The (1986)","Close Shave, A (1995)","Sword in the Stone, The (1963)",Cinderella (1950),Cinderella (1950),James and the Giant Peach (1996),James and the Giant Peach (1996),Cinderella (1950),Pinocchio (1940)
15,"Close Shave, A (1995)",Space Jam (1996),Beauty and the Beast (1991),"Aristocats, The (1970)",Cinderella (1950),"Aristocats, The (1970)","Wrong Trousers, The (1993)","Sword in the Stone, The (1963)","Wrong Trousers, The (1993)",Alice in Wonderland (1951),...,Hercules (1997),Fantasia (1940),Alice in Wonderland (1951),James and the Giant Peach (1996),Alice in Wonderland (1951),Alice in Wonderland (1951),"Hunchback of Notre Dame, The (1996)",Space Jam (1996),"Grand Day Out, A (1992)",Cinderella (1950)
16,"Wrong Trousers, The (1993)","Sword in the Stone, The (1963)","Hunchback of Notre Dame, The (1996)",Heavy Metal (1981),Heavy Metal (1981),Snow White and the Seven Dwarfs (1937),Dumbo (1941),"Pagemaster, The (1994)","Grand Day Out, A (1992)","Lion King, The (1994)",...,Winnie the Pooh and the Blustery Day (1968),Pocahontas (1995),"Sword in the Stone, The (1963)","Grand Day Out, A (1992)","Close Shave, A (1995)","Close Shave, A (1995)",Cats Don't Dance (1997),"Wrong Trousers, The (1993)",Wallace & Gromit: The Best of Aardman Animatio...,Dumbo (1941)
17,"Aristocats, The (1970)","Grand Day Out, A (1992)",Space Jam (1996),Alice in Wonderland (1951),Akira (1988),Heavy Metal (1981),Anastasia (1997),Hercules (1997),Akira (1988),"Close Shave, A (1995)",...,Space Jam (1996),"Hunchback of Notre Dame, The (1996)","Fox and the Hound, The (1981)",Pocahontas (1995),Akira (1988),Akira (1988),Winnie the Pooh and the Blustery Day (1968),"Close Shave, A (1995)",James and the Giant Peach (1996),Cats Don't Dance (1997)
18,"Sword in the Stone, The (1963)","Wrong Trousers, The (1993)",Cats Don't Dance (1997),Pinocchio (1940),"Grand Day Out, A (1992)",Pinocchio (1940),Winnie the Pooh and the Blustery Day (1968),Winnie the Pooh and the Blustery Day (1968),Beavis and Butt-head Do America (1996),Beavis and Butt-head Do America (1996),...,"Sword in the Stone, The (1963)","Sword in the Stone, The (1963)","Grand Day Out, A (1992)",Pinocchio (1940),Wallace & Gromit: The Best of Aardman Animatio...,Wallace & Gromit: The Best of Aardman Animatio...,"Sword in the Stone, The (1963)",Hercules (1997),Anastasia (1997),Winnie the Pooh and the Blustery Day (1968)
19,Beavis and Butt-head Do America (1996),Anastasia (1997),"Aristocats, The (1970)",Beavis and Butt-head Do America (1996),"Sword in the Stone, The (1963)",Winnie the Pooh and the Blustery Day (1968),Hercules (1997),Oliver & Company (1988),Pinocchio (1940),"Wrong Trousers, The (1993)",...,Beavis and Butt-head Do America (1996),Akira (1988),Wallace & Gromit: The Best of Aardman Animatio...,Wallace & Gromit: The Best of Aardman Animatio...,"Aristocats, The (1970)","Aristocats, The (1970)",Alice in Wonderland (1951),Winnie the Pooh and the Blustery Day (1968),Pocahontas (1995),Anastasia (1997)
20,Pete's Dragon (1977),Cats Don't Dance (1997),All Dogs Go to Heaven 2 (1996),Wallace & Gromit: The Best of Aardman Animatio...,"Fox and the Hound, The (1981)",Pete's Dragon (1977),Pinocchio (1940),Pete's Dragon (1977),"Close Shave, A (1995)","Aristocats, The (1970)",...,"Hunchback of Notre Dame, The (1996)","Fox and the Hound, The (1981)",Heavy Metal (1981),Hercules (1997),Oliver & Company (1988),Oliver & Company (1988),Pocahontas (1995),Heavy Metal (1981),"Hunchback of Notre Dame, The (1996)",Akira (1988)
21,Anastasia (1997),Ghost in the Shell (Kokaku kidotai) (1995),"Grand Day Out, A (1992)","Three Caballeros, The (1945)",Space Jam (1996),Oliver & Company (1988),All Dogs Go to Heaven 2 (1996),"Swan Princess, The (1994)",Cinderella (1950),Ghost in the Shell (Kokaku kidotai) (1995),...,Alice in Wonderland (1951),Cats Don't Dance (1997),Cats Don't Dance (1997),Heavy Metal (1981),Heavy Metal (1981),Heavy Metal (1981),Anastasia (1997),"Fox and the Hound, The (1981)",Space Jam (1996),Wallace & Gromit: The Best of Aardman Animatio...
22,Akira (1988),"Fox and the Hound, The (1981)",Akira (1988),Anastasia (1997),Wallace & Gromit: The Best of Aardman Animatio...,Cats Don't Dance (1997),Heavy Metal (1981),"Fox and the Hound, The (1981)",Alice in Wonderland (1951),All Dogs Go to Heaven 2 (1996),...,Heavy Metal (1981),Hercules (1997),Winnie the Pooh and the Blustery Day (1968),"Fox and the Hound, The (1981)",All Dogs Go to Heaven 2 (1996),All Dogs Go to Heaven 2 (1996),Dumbo (1941),Anastasia (1997),Pinocchio (1940),"Fox and the Hound, The (1981)"
23,"Three Caballeros, The (1945)","Transformers: The Movie, The (1986)",Pinocchio (1940),Hercules (1997),Hercules (1997),"Sword in the Stone, The (1963)","Sword in the Stone, The (1963)",Space Jam (1996),Aladdin and the King of Thieves (1996),Wallace & Gromit: The Best of Aardman Animatio...,...,"Aristocats, The (1970)",Ghost in the Shell (Kokaku kidotai) (1995),Space Jam (1996),Ghost in the Shell (Kokaku kidotai) (1995),"Grand Day Out, A (1992)","Grand Day Out, A (1992)",Pinocchio (1940),Pocahontas (1995),"Transformers: The Movie, The (1986)",Balto (1995)
24,"Fox and the Hound, The (1981)",Pinocchio (1940),Alice in Wonderland (1951),"Fox and the Hound, The (1981)",Alice in Wonderland (1951),"Fox and the Hound, The (1981)","Fox and the Hound, The (1981)",Heavy Metal (1981),"Transformers: The Movie, The (1986)","Grand Day Out, A (1992)",...,"Three Caballeros, The (1945)",Heavy Metal (1981),"Aristocats, The (1970)","Goofy Movie, A (1995)",Beavis and Butt-head Do America (1996),Beavis and Butt-head Do America (1996),"Grand Day Out, A (1992)",Pete's Dragon (1977),Hercules (1997),"Grand Day Out, A (1992)"
25,Heavy Metal (1981),Beavis and Butt-head Do America (1996),Aladdin and the King of Thieves (1996),Space Jam (1996),Pete's Dragon (1977),Akira (1988),Faust (1994),"Three Caballeros, The (1945)",Fantasia (1940),Akira (1988),...,All Dogs Go to Heaven 2 (1996),"Aristocats, The (1970)",Anastasia (1997),Anastasia (1997),Aladdin and the King of Thieves (1996),Aladdin and the King of Thieves (1996),"Aristocats, The (1970)","Grand Day Out, A (1992)",Pete's Dragon (1977),"Wrong Trousers, The (1993)"
26,Pocahontas (1995),Wallace & Gromit: The Best of Aardman Animatio...,"Transformers: The Movie, The (1986)",Aladdin and the King of Thieves (1996),Pocahontas (1995),"Hunchback of Notre Dame, The (1996)","Aristocats, The (1970)","Aristocats, The (1970)",Dumbo (1941),Aladdin and the King of Thieves (1996),...,Wallace & Gromit: The Best of Aardman Animatio...,All Dogs Go to Heaven 2 (1996),Aladdin and the King of Thieves (1996),Winnie the Pooh and the Blustery Day (1968),"Transformers: The Movie, The (1986)","Transformers: The Movie, The (1986)",Ghost in the Shell (Kokaku kidotai) (1995),Wallace & Gromit: The Best of Aardman Animatio...,"Aristocats, The (1970)","Pagemaster, The (1994)"
27,"Grand Day Out, A (1992)","Three Caballeros, The (1945)",Pocahontas (1995),Akira (1988),"Aristocats, The (1970)",Beauty and the Beast (1991),Wallace & Gromit: The Best of Aardman Animatio...,Pocahontas (1995),Pocahontas (1995),Dumbo (1941),...,"Fox and the Hound, The (1981)",Wallace & Gromit: The Best of Aardman Animatio...,Hercules (1997),Oliver & Company (1988),Anastasia (1997),Anastasia (1997),All Dogs Go to Heaven 2 (1996),Akira (1988),Alice in Wonderland (1951),Aladdin and the King of Thieves (1996)
28,Space Jam (1996),Aladdin and the King of Thieves (1996),"Three Caballeros, The (1945)","Grand Day Out, A (1992)","Transformers: The Movie, The (1986)",Anastasia (1997),Akira (1988),Aladdin and the King of Thieves (1996),"Three Caballeros, The (1945)","Hunchback of Notre Dame, The (1996)",...,Aladdin and the King of Thieves (1996),"Wrong Trousers, The (1993)",Oliver & Company (1988),Alice in Wonderland (1951),Pocahontas (1995),Pocahontas (1995),Akira (1988),"Transformers: The Movie, The (1986)","Sword in the Stone, The (1963)","Aristocats, The (1970)"
29,All Dogs Go to Heaven 2 (1996),Alice in Wonderland (1951),"Sword in the Stone, The (1963)",Cats Don't Dance (1997),"Three Caballeros, The (1945)",Ghost in the Shell (Kokaku kidotai) (1995),Alice in Wonderland (1951),Akira (1988),"Sword in the Stone, The (1963)","Three Caballeros, The (1945)",...,Cats Don't Dance (1997),"Grand Day Out, A (1992)",Pocahontas (1995),Aladdin and the King of Thieves (1996),"Three Caballeros, The (1945)","Three Caballeros, The (1945)",Aladdin and the King of Thieves (1996),Ghost in the Shell (Kokaku kidotai) (1995),Dumbo (1941),"Transformers: The Movie, The (1986)"
30,Aladdin and the King of Thieves (1996),Akira (1988),"Fox and the Hound, The (1981)",Pocahontas (1995),Ghost in the Shell (Kokaku kidotai) (1995),All Dogs Go to Heaven 2 (1996),Aladdin and the King of Thieves (1996),"Transformers: The Movie, The (1986)","Fox and the Hound, The (1981)","Sword in the Stone, The (1963)",...,"Wrong Trousers, The (1993)","Close Shave, A (1995)",Akira (1988),"Aristocats, The (1970)",Space Jam (1996),Space Jam (1996),"Transformers: The Movie, The (1986)","Aristocats, The (1970)",All Dogs Go to Heaven 2 (1996),"Sword in the Stone, The (1963)"
31,Cats Don't Dance (1997),Pete's Dragon (1977),Winnie the Pooh and the Blustery Day (1968),Pete's Dragon (1977),All Dogs Go to Heaven 2 (1996),Alice in Wonderland (1951),"Transformers: The Movie, The (1986)","Close Shave, A (1995)",Winnie the Pooh and the Blustery Day (1968),Space Jam (1996),...,Oliver & Company (1988),Aladdin and the King of Thieves (1996),Pete's Dragon (1977),All Dogs Go to Heaven 2 (1996),"Fox and the Hound, The (1981)","Fox and the Hound, The (1981)","Three Caballeros, The (1945)","Goofy Movie, A (1995)",Ghost in the Shell (Kokaku kidotai) (1995),Heavy Metal (1981)
32,Balto (1995),"Goofy Movie, A (1995)",Hercules (1997),Gumby: The Movie (1995),Balto (1995),Aladdin and the King of Thieves (1996),Pocahontas (1995),"Grand Day Out, A (1992)",Cats Don't Dance (1997),"Fox and the Hound, The (1981)",...,Pete's Dragon (1977),"Three Caballeros, The (1945)","Goofy Movie, A (1995)",Akira (1988),Winnie the Pooh and the Blustery Day (1968),Winnie the Pooh and the Blustery Day (1968),"Fox and the Hound, The (1981)",Oliver & Company (1988),Aladdin and the King of Thieves (1996),Pocahontas (1995)
33,"Goofy Movie, A (1995)","Swan Princess, The (1994)",Balto (1995),All Dogs Go to Heaven 2 (1996),Anastasia (1997),"Transformers: The Movie, The (1986)","Three Caballeros, The (1945)","Wrong Trousers, The (1993)",Balto (1995),Winnie the Pooh and the Blustery Day (1968),...,Gumby: The Movie (1995),Winnie the Pooh and the Blustery Day (1968),"Transformers: The Movie, The (1986)","Transformers: The Movie, The (1986)",Hercules (1997),Hercules (1997),Hercules (1997),Aladdin and the King of Thieves (1996),"Three Caballeros, The (1945)",All Dogs Go to Heaven 2 (1996)
34,"Swan Princess, The (1994)",All Dogs Go to Heaven 2 (1996),"Pagemaster, The (1994)","Pagemaster, The (1994)","Goofy Movie, A (1995)",Pocahontas (1995),Balto (1995),"Goofy Movie, A (1995)","Pagemaster, The (1994)",Cats Don't Dance (1997),...,"Grand Day Out, A (1992)",Balto (1995),Balto (1995),"Three Caballeros, The (1945)",Balto (1995),Balto (1995),Balto (1995),"Three Caballeros, The (1945)",Cats Don't Dance (1997),Oliver & Company (1988)
35,Land Before Time III: The Time of the Great Gi...,Pocahontas (1995),Oliver & Company (1988),"Transformers: The Movie, The (1986)",Land Before Time III: The Time of the Great Gi...,"Three Caballeros, The (1945)","Pagemaster, The (1994)",Ghost in the Shell (Kokaku kidotai) (1995),Oliver & Company (1988),Hercules (1997),...,Akira (1988),"Pagemaster, The (1994)",Ghost in the Shell (Kokaku kidotai) (1995),"Pagemaster, The (1994)","Pagemaster, The (1994)","Pagemaster, The (1994)","Pagemaster, The (1994)","Pagemaster, The (1994)",Balto (1995),Pete's Dragon (1977)
36,"Transformers: The Movie, The (1986)",Winnie the Pooh and the Blustery Day (1968),Pete's Dragon (1977),Balto (1995),Aladdin and the King of Thieves (1996),Balto (1995),Oliver & Company (1988),All Dogs Go to Heaven 2 (1996),Pete's Dragon (1977),"Pagemaster, The (1994)",...,"Transformers: The Movie, The (1986)",Oliver & Company (1988),Faust (1994),Pete's Dragon (1977),Pete's Dragon (1977),Pete's Dragon (1977),Oliver & Company (1988),Cats Don't Dance (1997),"Pagemaster, The (1994)","Goofy Movie, A (1995)"
37,Hercules (1997),Balto (1995),"Goofy Movie, A (1995)",Oliver & Company (1988),Cats Don't Dance (1997),"Pagemaster, The (1994)",Pete's Dragon (1977),Land Before Time III: The Time of the Great Gi...,"Goofy Movie, A (1995)",Pete's Dragon (1977),...,"Pagemaster, The (1994)",Pete's Dragon (1977),"Swan Princess, The (1994)",Cats Don't Dance (1997),"Goofy Movie, A (1995)","Goofy Movie, A (1995)",Pete's Dragon (1977),Balto (1995),Oliver & Company (1988),Ghost in the Shell (Kokaku kidotai) (1995)

In [366]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Children, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [367]:
#administrator

In [368]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Children, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [369]:
#artist

In [370]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Children, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [371]:
#doctor

In [372]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Children, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [373]:
#educator

In [374]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Children, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [375]:
#engineer

In [376]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Children, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [377]:
#entertainment

In [378]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Children, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [379]:
#executive

In [380]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Children, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [381]:
#healthcare

In [382]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Children, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [383]:
#homemaker

In [384]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Children, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [385]:
#lawyer

In [386]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Children, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [387]:
#librarian

In [388]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Children, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [389]:
#marketing

In [390]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Children, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [391]:
#none

In [392]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Children, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [393]:
#other

In [394]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Children, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [395]:
#programmer

In [396]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Children, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [397]:
#retired

In [398]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Children, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [399]:
#salesman

In [400]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Children, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [401]:
#scientist

In [402]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Children, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [403]:
#student

In [404]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Children, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [405]:
#technician

In [406]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Children, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [407]:
#writer

In [408]:
Children_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Children_occupation_rank = Children_occupation_rank.reset_index(drop=True)
Children_occupation_rank.index += 1
Children_occupation_rank = Children_occupation_rank.rename_axis("Rank")
Children_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Willy Wonka and the Chocolate Factory (1971),Toy Story (1995),...,Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),Babe (1995),Babe (1995),Willy Wonka and the Chocolate Factory (1971),Toy Story (1995),Toy Story (1995),E.T. the Extra-Terrestrial (1982)
2,E.T. the Extra-Terrestrial (1982),Willy Wonka and the Chocolate Factory (1971),Willy Wonka and the Chocolate Factory (1971),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),Fly Away Home (1996),Willy Wonka and the Chocolate Factory (1971),"Lion King, The (1994)",Jungle2Jungle (1997),"Wizard of Oz, The (1939)",...,Anastasia (1997),Willy Wonka and the Chocolate Factory (1971),Willy Wonka and the Chocolate Factory (1971),Willy Wonka and the Chocolate Factory (1971),George of the Jungle (1997),George of the Jungle (1997),Toy Story (1995),Willy Wonka and the Chocolate Factory (1971),"Lion King, The (1994)",Willy Wonka and the Chocolate Factory (1971)
3,Willy Wonka and the Chocolate Factory (1971),Babe (1995),Cinderella (1950),Babe (1995),Willy Wonka and the Chocolate Factory (1971),Willy Wonka and the Chocolate Factory (1971),Matilda (1996),E.T. the Extra-Terrestrial (1982),Toy Story (1995),Jungle2Jungle (1997),...,Fly Away Home (1996),James and the Giant Peach (1996),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),"Wizard of Oz, The (1939)",E.T. the Extra-Terrestrial (1982),"Wizard of Oz, The (1939)",Toy Story (1995)
4,"Wizard of Oz, The (1939)","Wizard of Oz, The (1939)",Home Alone (1990),"Wizard of Oz, The (1939)",Aladdin (1992),Babe (1995),George of the Jungle (1997),"Wizard of Oz, The (1939)",Free Willy 3: The Rescue (1997),Willy Wonka and the Chocolate Factory (1971),...,E.T. the Extra-Terrestrial (1982),Jungle2Jungle (1997),"Lion King, The (1994)","Wizard of Oz, The (1939)",Toy Story (1995),Toy Story (1995),E.T. the Extra-Terrestrial (1982),Aladdin (1992),Aladdin (1992),Babe (1995)
5,George of the Jungle (1997),"Nightmare Before Christmas, The (1993)",Fantasia (1940),Willy Wonka and the Chocolate Factory (1971),"Wizard of Oz, The (1939)",E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),Fly Away Home (1996),Flubber (1997),Home Alone (1990),...,George of the Jungle (1997),Beauty and the Beast (1991),Aladdin (1992),Aladdin (1992),"Secret Garden, The (1993)","Secret Garden, The (1993)",Babe (1995),Beauty and the Beast (1991),Willy Wonka and the Chocolate Factory (1971),"Wizard of Oz, The (1939)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Gold Diggers: The Secret of Bear Mountain (1995),"Little Princess, The (1939)",Far From Home: The Adventures of Yellow Dog (1...,"Swan Princess, The (1994)",Far From Home: The Adventures of Yellow Dog (1...,Far From Home: The Adventures of Yellow Dog (1...,Far From Home: The Adventures of Yellow Dog (1...,Wild America (1997),Far From Home: The Adventures of Yellow Dog (1...,Gold Diggers: The Secret of Bear Mountain (1995),...,Gold Diggers: The Secret of Bear Mountain (1995),Far From Home: The Adventures of Yellow Dog (1...,Gumby: The Movie (1995),Tom and Huck (1995),Far From Home: The Adventures of Yellow Dog (1...,Far From Home: The Adventures of Yellow Dog (1...,Herbie Rides Again (1974),So Dear to My Heart (1949),Far From Home: The Adventures of Yellow Dog (1...,"Little Princess, The (1939)"
119,Far From Home: The Adventures of Yellow Dog (1...,Herbie Rides Again (1974),"Amazing Panda Adventure, The (1995)",Land Before Time III: The Time of the Great Gi...,"Amazing Panda Adventure, The (1995)","Amazing Panda Adventure, The (1995)","Amazing Panda Adventure, The (1995)","Simple Wish, A (1997)","Amazing Panda Adventure, The (1995)",Far From Home: The Adventures of Yellow Dog (1...,...,Far From Home: The Adventures of Yellow Dog (1...,"Amazing Panda Adventure, The (1995)","Little Princess, The (1939)",Gumby: The Movie (1995),"Amazing Panda Adventure, The (1995)","Amazing Panda Adventure, The (1995)",Gold Diggers: The Secret of Bear Mountain (1995),Zeus and Roxanne (1997),"Amazing Panda Adventure, The (1995)",Far From Home: The Adventures of Yellow Dog (1...
120,"Amazing Panda Adventure, The (1995)",Gold Diggers: The Secret of Bear Mountain (1995),"Secret Adventures of Tom Thumb, The (1993)","Next Karate Kid, The (1994)","Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)",Star Kid (1997),"Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)",...,"Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)",Gold Diggers: The Secret of Bear Mountain (1995),Gold Diggers: The Secret of Bear Mountain (1995),"Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)",Far From Home: The Adventures of Yellow Dog (1...,Kim (1950),"Secret Adventures of Tom Thumb, The (1993)","Secret Adventures of Tom Thumb, The (1993)"
121,"Secret Adventures of Tom Thumb, The (1993)",Far From Home: The Adventures of Yellow Dog (1...,Buddy (1997),Far From Home: The Adventures of Yellow Dog (1...,Buddy (1997),Buddy (1997),Buddy (1997),Kazaam (1996),Buddy (1997),Buddy (1997),...,Buddy (1997),Buddy (1997),"Secret Adventures of Tom Thumb, The (1993)","Amazing Panda Adventure, The (1995)",Buddy (1997),Buddy (1997),"Amazing Panda Adventure, The (1995)",Star Kid (1997),Buddy (1997),Buddy (1997)
122,Buddy (1997),"Secret Adventures of Tom Thumb, The (1993)",Warriors of Virtue (1997),"Secret Adventures of Tom Thumb, The (1993)",Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Buddy (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),...,Warriors of Virtue (1997),Warriors of Virtue (1997),Buddy (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Buddy (1997),Warriors of Virtue (1997),Warriors of Virtue (1997)

In [409]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Comedy, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [410]:
#administrator

In [411]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Comedy, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [412]:
#artist

In [413]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Comedy, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [414]:
#doctor

In [415]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Comedy, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [416]:
#educator

In [417]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Comedy, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [418]:
#engineer

In [419]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Comedy, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [420]:
#entertainment

In [421]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Comedy, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [422]:
#executive

In [423]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Comedy, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [424]:
#healthcare

In [425]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Comedy, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [426]:
#homemaker

In [427]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Comedy, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [428]:
#lawyer

In [429]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Comedy, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [430]:
#librarian

In [431]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Comedy, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [432]:
#marketing

In [433]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Comedy, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [434]:
#none

In [435]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Comedy, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [436]:
#other

In [437]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Comedy, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [438]:
#programmer

In [439]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Comedy, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [440]:
#retired

In [441]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Comedy, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [442]:
#salesman

In [443]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Comedy, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [444]:
#scientist

In [445]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Comedy, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [446]:
#student

In [447]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Comedy, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [448]:
#technician

In [449]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Comedy, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [450]:
#writer

In [451]:
Comedy_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Comedy_occupation_rank = Comedy_occupation_rank.reset_index(drop=True)
Comedy_occupation_rank.index += 1
Comedy_occupation_rank = Comedy_occupation_rank.rename_axis("Rank")
Comedy_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Liar Liar (1997),Liar Liar (1997),Toy Story (1995),"Full Monty, The (1997)",Toy Story (1995),Toy Story (1995),Liar Liar (1997),"Birdcage, The (1996)",Liar Liar (1997),"Full Monty, The (1997)",...,Liar Liar (1997),Toy Story (1995),Liar Liar (1997),Liar Liar (1997),Liar Liar (1997),Liar Liar (1997),Willy Wonka and the Chocolate Factory (1971),Liar Liar (1997),Toy Story (1995),Liar Liar (1997)
2,"Full Monty, The (1997)",Toy Story (1995),Eat Drink Man Woman (1994),Toy Story (1995),Forrest Gump (1994),Liar Liar (1997),Toy Story (1995),Toy Story (1995),Wag the Dog (1997),Liar Liar (1997),...,"Full Monty, The (1997)",Liar Liar (1997),Toy Story (1995),Toy Story (1995),M*A*S*H (1970),M*A*S*H (1970),Toy Story (1995),Toy Story (1995),Liar Liar (1997),Back to the Future (1985)
3,Toy Story (1995),Willy Wonka and the Chocolate Factory (1971),Willy Wonka and the Chocolate Factory (1971),Liar Liar (1997),Back to the Future (1985),Mother (1996),Willy Wonka and the Chocolate Factory (1971),M*A*S*H (1970),Willy Wonka and the Chocolate Factory (1971),Toy Story (1995),...,Toy Story (1995),Willy Wonka and the Chocolate Factory (1971),"Truth About Cats & Dogs, The (1996)",Monty Python and the Holy Grail (1974),When Harry Met Sally... (1989),When Harry Met Sally... (1989),Liar Liar (1997),"Princess Bride, The (1987)",Monty Python and the Holy Grail (1974),Men in Black (1997)
4,Back to the Future (1985),Raising Arizona (1987),Men in Black (1997),In & Out (1997),Monty Python and the Holy Grail (1974),Kingpin (1996),Men in Black (1997),Men in Black (1997),Michael (1996),Forrest Gump (1994),...,When Harry Met Sally... (1989),Jungle2Jungle (1997),Willy Wonka and the Chocolate Factory (1971),Back to the Future (1985),Men in Black (1997),Men in Black (1997),Forrest Gump (1994),Back to the Future (1985),Forrest Gump (1994),"Princess Bride, The (1987)"
5,In & Out (1997),Babe (1995),"Truth About Cats & Dogs, The (1996)","Princess Bride, The (1987)",Willy Wonka and the Chocolate Factory (1971),"Full Monty, The (1997)","Truth About Cats & Dogs, The (1996)",Forrest Gump (1994),Midnight in the Garden of Good and Evil (1997),Monty Python and the Holy Grail (1974),...,Forrest Gump (1994),"Princess Bride, The (1987)",Back to the Future (1985),"Princess Bride, The (1987)",Babe (1995),Babe (1995),Back to the Future (1985),Willy Wonka and the Chocolate Factory (1971),Young Frankenstein (1974),Willy Wonka and the Chocolate Factory (1971)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,Getting Away With Murder (1996),Chairman of the Board (1998),Getting Away With Murder (1996),Getting Away With Murder (1996),Getting Away With Murder (1996),Little City (1998),Getting Away With Murder (1996),Getting Away With Murder (1996),Getting Away With Murder (1996),Getting Away With Murder (1996),...,Getting Away With Murder (1996),Getting Away With Murder (1996),"Favor, The (1994)",Getting Away With Murder (1996),Getting Away With Murder (1996),Getting Away With Murder (1996),Getting Away With Murder (1996),Little City (1998),Getting Away With Murder (1996),Little City (1998)
502,8 Heads in a Duffel Bag (1997),"Favor, The (1994)",8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),Getting Away With Murder (1996),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),...,8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),8 Heads in a Duffel Bag (1997),Getting Away With Murder (1996),8 Heads in a Duffel Bag (1997),Getting Away With Murder (1996)
503,Wedding Bell Blues (1996),Little City (1998),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),...,Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),Wedding Bell Blues (1996),8 Heads in a Duffel Bag (1997)
504,Tainted (1998),Getting Away With Murder (1996),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),...,Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Wedding Bell Blues (1996)
505,You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),...,You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),You So Crazy (1994),Tainted (1998)

In [452]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Crime, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [453]:
#administrator

In [454]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Crime, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [455]:
#artist

In [456]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Crime, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [457]:
#doctor

In [458]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Crime, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [459]:
#educator

In [460]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Crime, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [461]:
#engineer

In [462]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Crime, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [463]:
#entertainment

In [464]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Crime, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [465]:
#executive

In [466]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Crime, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [467]:
#healthcare

In [468]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Crime, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [469]:
#homemaker

In [470]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Crime, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [471]:
#lawyer

In [472]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Crime, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [473]:
#librarian

In [474]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Crime, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [475]:
#marketing

In [476]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Crime, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [477]:
#none

In [478]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Crime, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [479]:
#other

In [480]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Crime, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [481]:
#programmer

In [482]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Crime, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [483]:
#retired

In [484]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Crime, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [485]:
#salesman

In [486]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Crime, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [487]:
#scientist

In [488]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Crime, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [489]:
#student

In [490]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Crime, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [491]:
#technician

In [492]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Crime, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [493]:
#writer

In [494]:
Crime_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Crime_occupation_rank = Crime_occupation_rank.reset_index(drop=True)
Crime_occupation_rank.index += 1
Crime_occupation_rank = Crime_occupation_rank.rename_axis("Rank")
Crime_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Fargo (1996),Fargo (1996),L.A. Confidential (1997),Fargo (1996),Fargo (1996),L.A. Confidential (1997),Fargo (1996),"Godfather, The (1972)",Midnight in the Garden of Good and Evil (1997),Fargo (1996),...,"Godfather, The (1972)",Fargo (1996),"Godfather, The (1972)",Fargo (1996),Fargo (1996),Fargo (1996),Fargo (1996),Fargo (1996),Fargo (1996),Fargo (1996)
2,"Godfather, The (1972)","Godfather, The (1972)",Fargo (1996),"Godfather, The (1972)",Pulp Fiction (1994),Fargo (1996),"Godfather, The (1972)",Fargo (1996),Cop Land (1997),Pulp Fiction (1994),...,L.A. Confidential (1997),Jackie Brown (1997),Fargo (1996),Pulp Fiction (1994),"Godfather, The (1972)","Godfather, The (1972)","Godfather, The (1972)",Pulp Fiction (1994),Pulp Fiction (1994),L.A. Confidential (1997)
3,Pulp Fiction (1994),Pulp Fiction (1994),"Usual Suspects, The (1995)",L.A. Confidential (1997),"Godfather, The (1972)",Pulp Fiction (1994),Pulp Fiction (1994),Pulp Fiction (1994),Sleepers (1996),"Sting, The (1973)",...,"Devil's Advocate, The (1997)",Batman (1989),Pulp Fiction (1994),"Godfather, The (1972)","Usual Suspects, The (1995)","Usual Suspects, The (1995)",Pulp Fiction (1994),"Godfather, The (1972)","Godfather, The (1972)","Godfather, The (1972)"
4,"Sting, The (1973)",L.A. Confidential (1997),"Godfather, The (1972)",Pulp Fiction (1994),"Usual Suspects, The (1995)",Heat (1995),"Usual Suspects, The (1995)","Usual Suspects, The (1995)",Playing God (1997),"Godfather, The (1972)",...,Fargo (1996),Rumble in the Bronx (1995),L.A. Confidential (1997),Seven (Se7en) (1995),"Devil's Advocate, The (1997)","Devil's Advocate, The (1997)",L.A. Confidential (1997),Seven (Se7en) (1995),Batman Returns (1992),"Usual Suspects, The (1995)"
5,L.A. Confidential (1997),"Sting, The (1973)",Jackie Brown (1997),"Sting, The (1973)",L.A. Confidential (1997),GoodFellas (1990),L.A. Confidential (1997),Seven (Se7en) (1995),L.A. Confidential (1997),L.A. Confidential (1997),...,GoodFellas (1990),L.A. Confidential (1997),Seven (Se7en) (1995),"Usual Suspects, The (1995)",L.A. Confidential (1997),L.A. Confidential (1997),"Usual Suspects, The (1995)","Usual Suspects, The (1995)","Godfather: Part II, The (1974)",Pulp Fiction (1994)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,"Truth or Consequences, N.M. (1997)",He Walked by Night (1948),"Truth or Consequences, N.M. (1997)",Deceiver (1997),"Truth or Consequences, N.M. (1997)","Truth or Consequences, N.M. (1997)","Truth or Consequences, N.M. (1997)",City of Industry (1997),"Truth or Consequences, N.M. (1997)","Truth or Consequences, N.M. (1997)",...,"Truth or Consequences, N.M. (1997)","Truth or Consequences, N.M. (1997)","Truth or Consequences, N.M. (1997)","Truth or Consequences, N.M. (1997)",Deceiver (1997),Deceiver (1997),"Truth or Consequences, N.M. (1997)",Deceiver (1997),"Truth or Consequences, N.M. (1997)","Truth or Consequences, N.M. (1997)"
106,King of New York (1990),Deceiver (1997),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),He Walked by Night (1948),King of New York (1990),King of New York (1990),...,King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),King of New York (1990),"Truth or Consequences, N.M. (1997)",King of New York (1990),King of New York (1990)
107,Normal Life (1996),King of New York (1990),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),"Truth or Consequences, N.M. (1997)",Normal Life (1996),Normal Life (1996),...,Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996),Normal Life (1996)
108,Hana-bi (1997),Normal Life (1996),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),King of New York (1990),Hana-bi (1997),Hana-bi (1997),...,Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997),Hana-bi (1997)
109,MURDER and murder (1996),Hana-bi (1997),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),...,MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996)

In [495]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Documentary, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [496]:
#administrator

In [497]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Documentary, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [498]:
#artist

In [499]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Documentary, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [500]:
#doctor

In [501]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Documentary, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [502]:
#educator

In [503]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Documentary, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [504]:
#engineer

In [505]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Documentary, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [506]:
#entertainment

In [507]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Documentary, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [508]:
#executive

In [509]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Documentary, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [510]:
#healthcare

In [511]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Documentary, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [512]:
#homemaker

In [513]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Documentary, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [514]:
#lawyer

In [515]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Documentary, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [516]:
#librarian

In [517]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Documentary, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [518]:
#marketing

In [519]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Documentary, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [520]:
#none

In [521]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Documentary, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [522]:
#other

In [523]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Documentary, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [524]:
#programmer

In [525]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Documentary, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [526]:
#retired

In [527]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Documentary, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [528]:
#salesman

In [529]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Documentary, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [530]:
#scientist

In [531]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Documentary, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [532]:
#student

In [533]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Documentary, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [534]:
#technician

In [535]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Documentary, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [536]:
#writer

In [537]:
Documentary_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Documentary_occupation_rank = Documentary_occupation_rank.reset_index(drop=True)
Documentary_occupation_rank.index += 1
Documentary_occupation_rank = Documentary_occupation_rank.rename_axis("Rank")
Documentary_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Hoop Dreams (1994),Looking for Richard (1996),"Celluloid Closet, The (1995)",Hoop Dreams (1994),Hoop Dreams (1994),Crumb (1994),"Celluloid Closet, The (1995)",Madonna: Truth or Dare (1991),Looking for Richard (1996),Hoop Dreams (1994),...,"Haunted World of Edward D. Wood Jr., The (1995)",When We Were Kings (1996),Hoop Dreams (1994),Hoop Dreams (1994),Hoop Dreams (1994),Hoop Dreams (1994),Crumb (1994),Hoop Dreams (1994),Crumb (1994),Paradise Lost: The Child Murders at Robin Hood...
2,"Celluloid Closet, The (1995)",Crumb (1994),Crumb (1994),Koyaanisqatsi (1983),Koyaanisqatsi (1983),Hoop Dreams (1994),Hoop Dreams (1994),Hoop Dreams (1994),Ayn Rand: A Sense of Life (1997),Crumb (1994),...,Anne Frank Remembered (1995),Crumb (1994),Crumb (1994),Crumb (1994),Crumb (1994),Crumb (1994),Koyaanisqatsi (1983),Crumb (1994),Hoop Dreams (1994),Hoop Dreams (1994)
3,Crumb (1994),Koyaanisqatsi (1983),Hoop Dreams (1994),Crumb (1994),"Thin Blue Line, The (1988)",Thirty-Two Short Films About Glenn Gould (1993),Wonderland (1997),"Celluloid Closet, The (1995)",Crumb (1994),"Celluloid Closet, The (1995)",...,Hoop Dreams (1994),Hoop Dreams (1994),"Celluloid Closet, The (1995)",When We Were Kings (1996),Microcosmos: Le peuple de l'herbe (1996),Microcosmos: Le peuple de l'herbe (1996),Hoop Dreams (1994),"Celluloid Closet, The (1995)","Haunted World of Edward D. Wood Jr., The (1995)",Looking for Richard (1996)
4,"Thin Blue Line, The (1988)",Microcosmos: Le peuple de l'herbe (1996),"Haunted World of Edward D. Wood Jr., The (1995)","Celluloid Closet, The (1995)",Crumb (1994),Looking for Richard (1996),"Fast, Cheap & Out of Control (1997)",Across the Sea of Time (1995),Hoop Dreams (1994),"Thin Blue Line, The (1988)",...,"Celluloid Closet, The (1995)",Brother Minister: The Assassination of Malcolm...,When We Were Kings (1996),Anne Frank Remembered (1995),Looking for Richard (1996),Looking for Richard (1996),Anne Frank Remembered (1995),"Fast, Cheap & Out of Control (1997)","Thin Blue Line, The (1988)",Crumb (1994)
5,Paris Is Burning (1990),Paris Is Burning (1990),Microcosmos: Le peuple de l'herbe (1996),When We Were Kings (1996),When We Were Kings (1996),"Fast, Cheap & Out of Control (1997)",Crumb (1994),When We Were Kings (1996),Brother Minister: The Assassination of Malcolm...,"Wonderful, Horrible Life of Leni Riefenstahl, ...",...,Looking for Richard (1996),"Haunted World of Edward D. Wood Jr., The (1995)",Looking for Richard (1996),"Celluloid Closet, The (1995)",Maya Lin: A Strong Clear Vision (1994),Maya Lin: A Strong Clear Vision (1994),"Thin Blue Line, The (1988)",Looking for Richard (1996),Looking for Richard (1996),"Thin Blue Line, The (1988)"
6,Koyaanisqatsi (1983),Hoop Dreams (1994),Paris Is Burning (1990),Looking for Richard (1996),Looking for Richard (1996),"Haunted World of Edward D. Wood Jr., The (1995)",Heidi Fleiss: Hollywood Madam (1995),Anne Frank Remembered (1995),"Haunted World of Edward D. Wood Jr., The (1995)",Year of the Horse (1997),...,"Fast, Cheap & Out of Control (1997)",Maya Lin: A Strong Clear Vision (1994),Madonna: Truth or Dare (1991),"Thin Blue Line, The (1988)",Thirty-Two Short Films About Glenn Gould (1993),Thirty-Two Short Films About Glenn Gould (1993),Paris Is Burning (1990),Microcosmos: Le peuple de l'herbe (1996),Madonna: Truth or Dare (1991),"Celluloid Closet, The (1995)"
7,"Fast, Cheap & Out of Control (1997)","Fast, Cheap & Out of Control (1997)",Thirty-Two Short Films About Glenn Gould (1993),"Endless Summer 2, The (1994)",Anne Frank Remembered (1995),Paradise Lost: The Child Murders at Robin Hood...,JLG/JLG - autoportrait de dÃ©cembre (1994),Unzipped (1995),Maya Lin: A Strong Clear Vision (1994),Brother Minister: The Assassination of Malcolm...,...,Koyaanisqatsi (1983),Paradise Lost: The Child Murders at Robin Hood...,Paradise Lost: The Child Murders at Robin Hood...,Paris Is Burning (1990),"Perfect Candidate, A (1996)","Perfect Candidate, A (1996)","Celluloid Closet, The (1995)",When We Were Kings (1996),Brother Minister: The Assassination of Malcolm...,Paris Is Burning (1990)
8,When We Were Kings (1996),Ayn Rand: A Sense of Life (1997),Looking for Richard (1996),"Fast, Cheap & Out of Control (1997)","Haunted World of Edward D. Wood Jr., The (1995)",Wonderland (1997),"Leopard Son, The (1996)",Crumb (1994),Paradise Lost: The Child Murders at Robin Hood...,"Haunted World of Edward D. Wood Jr., The (1995)",...,"War Room, The (1993)",Wonderland (1997),"Thin Blue Line, The (1988)",Looking for Richard (1996),Koyaanisqatsi (1983),Koyaanisqatsi (1983),Heidi Fleiss: Hollywood Madam (1995),Koyaanisqatsi (1983),Maya Lin: A Strong Clear Vision (1994),Unzipped (1995)
9,Microcosmos: Le peuple de l'herbe (1996),Madonna: Truth or Dare (1991),Unzipped (1995),Paris Is Burning (1990),Thirty-Two Short Films About Glenn Gould (1993),Microcosmos: Le peuple de l'herbe (1996),"Last Klezmer: Leopold Kozlowski, His Life and ...",Paris Is Burning (1990),Wonderland (1997),Maya Lin: A Strong Clear Vision (1994),...,"Last Klezmer: Leopold Kozlowski, His Life and ...",Microcosmos: Le peuple de l'herbe (1996),Paris Is Burning (1990),Koyaanisqatsi (1983),Heidi Fleiss: Hollywood Madam (1995),Heidi Fleiss: Hollywood Madam (1995),Brother Minister: The Assassination of Malcolm...,Madonna: Truth or Dare (1991),Wonderland (1997),"Fast, Cheap & Out of Control (1997)"
10,Looking for Richard (1996),When We Were Kings (1996),"Fast, Cheap & Out of Control (1997)","Thin Blue Line, The (1988)",Paris Is Burning (1990),"Celluloid Closet, The (1995)",Catwalk (1995),"Thin Blue Line, The (1988)",Microcosmos: Le peuple de l'herbe (1996),Paradise Lost: The Child Murders at Robin Hood...,...,Rhyme & Reason (1997),"Thin Blue Line, The (1988)",Koyaanisqatsi (1983),Wonderland (1997),"Endless Summer 2, The (1994)","Endless Summer 2, The (1994)","Haunted World of Edward D. Wood Jr., The (1995)","Thin Blue Line, The (1988)",Paris Is Burning (1990),Koyaanisqatsi (1983)
11,Jupiter's Wife (1994),Heidi Fleiss: Hollywood Madam (1995),"War Room, The (1993)",Man of the Year (1995),"Wonderful, Horrible Life of Leni Riefenstahl, ...",Year of the Horse (1997),When We Were Kings (1996),American Dream (1990),"Thin Blue Line, The (1988)",Wonderland (1997),...,Crumb (1994),Paris Is Burning (1990),"Line King: Al Hirschfeld, The (1996)","Wonderful, Horrible Life of Leni Riefenstahl, ...",Ayn Rand: A Sense of Life (1997),Ayn Rand: A Sense of Life (1997),Maya Lin: A Strong Clear Vision (1994),Paris Is Burning (1990),"Fast, Cheap & Out of Control (1997)",Anne Frank Remembered (1995)
12,Heidi Fleiss: Hollywood Madam (1995),Anne Frank Remembered (1995),Ayn Rand: A Sense of Life (1997),Thirty-Two Short Films About Glenn Gould (1993),Grateful Dead (1995),Koyaanisqatsi (1983),"War Room, The (1993)",Looking for Richard (1996),Paris Is Burning (1990),Microcosmos: Le peuple de l'herbe (1996),...,Brother Minister: The Assassination of Malcolm...,Fire on the Mountain (1996),Carmen Miranda: Bananas Is My Business (1994),Paradise Lost: The Child Murders at Robin Hood...,Brother Minister: The Assassination of Malcolm...,Brother Minister: The Assassination of Malcolm...,Paradise Lost: The Child Murders at Robin Hood...,Paradise Lost: The Child Murders at Robin Hood...,Koyaanisqatsi (1983),Heidi Fleiss: Hollywood Madam (1995)
13,Thirty-Two Short Films About Glenn Gould (1993),Year of the Horse (1997),Brother Minister: The Assassination of Malcolm...,Anne Frank Remembered (1995),"Fast, Cheap & Out of Control (1997)",Heidi Fleiss: Hollywood Madam (1995),Koyaanisqatsi (1983),"Eye of Vichy, The (Oeil de Vichy, L') (1993)",Fire on the Mountain (1996),Paris Is Burning (1990),...,Maya Lin: A Strong Clear Vision (1994),"Wonderful, Horrible Life of Leni Riefenstahl, ...","Endless Summer 2, The (1994)","Perfect Candidate, A (1996)","Haunted World of Edward D. Wood Jr., The (1995)","Haunted World of Edward D. Wood Jr., The (1995)",Wonderland (1997),Thirty-Two Short Films About Glenn Gould (1993),When We Were Kings (1996),When We Were Kings (1996)
14,Unzipped (1995),Unzipped (1995),Maya Lin: A Strong Clear Vision (1994),Unzipped (1995),Heidi Fleiss: Hollywood Madam (1995),"War Room, The (1993)",Anne Frank Remembered (1995),Carmen Miranda: Bananas Is My Business (1994),"Wonderful, Horrible Life of Leni Riefenstahl, ...",Fire on the Mountain (1996),...,Paradise Lost: The Child Murders at Robin Hood...,Across the Sea of Time (1995),Heidi Fleiss: Hollywood Madam (1995),"Fast, Cheap & Out of Control (1997)",Paradise Lost: The Child Murders at Robin Hood...,Paradise Lost: The Child Murders at Robin Hood...,Microcosmos: Le peuple de l'herbe (1996),Wonderland (1997),"Show, The (1995)",Thirty-Two Short Films About Glenn Gould (1993)
15,"Wonderful, Horrible Life of Leni Riefenstahl, ...",Thirty-Two Short Films About Glenn Gould (1993),Paradise Lost: The Child Murders at Robin Hood...,"Last Klezmer: Leopold Kozlowski, His Life and ...",Ayn Rand: A Sense of Life (1997),When We Were Kings (1996),Grateful Dead (1995),Tigrero: A Film That Was Never Made (1994),Across the Sea of Time (1995),Across the Sea of Time (1995),...,Wonderland (1997),Man of the Year (1995),Anne Frank Remembered (1995),"Haunted World of Edward D. Wood Jr., The (1995)",Wonderland (1997),Wonderland (1997),Fire on the Mountain (1996),"War Room, The (1993)",Paradise Lost: The Child Murders at Robin Hood...,Brother Minister: The Assassination of Malcolm...
16,Fire on the Mountain (1996),"Wonderful, Horrible Life of Leni Riefenstahl, ...",Wonderland (1997),"Wonderful, Horrible Life of Leni Riefenstahl, ...",Brother Minister: The Assassination of Malcolm...,Ayn Rand: A Sense of Life (1997),Year of the Horse (1997),"Show, The (1995)",Man of the Year (1995),Man of the Year (1995),...,Microcosmos: Le peuple de l'herbe (1996),Thirty-Two Short Films About Glenn Gould (1993),"Perfect Candidate, A (1996)",Heidi Fleiss: Hollywood Madam (1995),"Thin Blue Line, The (1988)","Thin Blue Line, The (1988)","Wonderful, Horrible Life of Leni Riefenstahl, ...","Endless Summer 2, The (1994)",Microcosmos: Le peuple de l'herbe (1996),Grateful Dead (1995)
17,Paradise Lost: The Child Murders at Robin Hood...,"Thin Blue Line, The (1988)","Thin Blue Line, The (1988)",Microcosmos: Le peuple de l'herbe (1996),Maya Lin: A Strong Clear Vision (1994),Brother Minister: The Assassination of Malcolm...,Looking for Richard (1996),Nico Icon (1995),Thirty-Two Short Films About Glenn Gould (1993),Thirty-Two Short Films About Glenn Gould (1993),...,"Thin Blue Line, The (1988)","Celluloid Closet, The (1995)","Fast, Cheap & Out of Control (1997)",Brother Minister: The Assassination of Malcolm...,Paris Is Burning (1990),Paris Is Burning (1990),Across the Sea of Time (1995),Everest (1998),Fire on the Mountain (1996),Rhyme & Reason (1997)
18,"Haunted World of Edward D. Wood Jr., The (1995)","Haunted World of Edward D. Wood Jr., The (1995)",Fire on the Mountain (1996),Paradise Lost: The Child Murders at Robin Hood...,Paradise Lost: The Child Murders at Robin Hood...,Maya Lin: A Strong Clear Vision (1994),Man of the Year (1995),Rhyme & Reason (1997),"Celluloid Closet, The (1995)","Great Day in Harlem, A (1994)",...,Paris Is Burning (1990),"Great Day in Harlem, A (1994)",Grateful Dead (1995),Madonna: Truth or Dare (1991),Fire on the Mountain (1996),Fire on the Mountain (1996),Man of the Year (1995),Anne Frank Remembered (1995),"Wonderful, Horrible Life of Leni Riefenstahl, ...","Haunted World of Edward D. Wood Jr., The (1995)"
19,"Endless Summer 2, The (1994)",Rhyme & Reason (1997),"Wonderful, Horrible Life of Leni Riefenstahl, ...","Haunted World of Edward D. Wood Jr., The (1995)",Wonderland (1997),"Thin Blue Line, The (1988)",Microcosmos: Le peuple de l'herbe (1996),Dadetown (1995),"Great Day in Harlem, A (1994)",Looking for Richard (1996),...,Fire on the Mountain (1996),Looking for Richard (1996),Unzipped (1995),"Line King: Al Hirschfeld, The (1996)","Wonderful, Horrible Life of Leni Riefenstahl, ...","Wonderful, Horrible Life of Leni Riefenstahl, ...",Thirty-Two Short Films About Glenn Gould (1993),Year of the Horse (1997),Across the Sea of Time (1995),Maya Lin: A Strong Clear Vision (1994)
20,Brother Minister: The Assassination of Malcolm...,Brother Minister: The Assassination of Malcolm...,Across the Sea of Time (1995),Across the Sea of Time (1995),Microcosmos: Le peuple de l'herbe (1996),Paris Is Burning (1990),Rhyme & Reason (1997),Catwalk (1995),"Perfect Candidate, A (1996)","Perfect Candidate, A (1996)",...,"Wonderful, Horrible Life of Leni Riefenstahl, ...","Perfect Candidate, A (1996)",Thirty-Two Short Films About Glenn Gould (1993),Maya Lin: A Strong Clear Vision (1994),Across the Sea of Time (1995),Across the Sea of Time (1995),"Great Day in Harlem, A (1994)",Man of the Year (1995),Man of the Year (1995),Wonderland (1997)
21,Maya Lin: A Strong Clear Vision (1994),Maya Lin: A Strong Clear Vision (1994),Man of the Year (1995),"Perfect Candidate, A (1996)",Fire on the Mountain (1996),Fire on the Mountain (1996),Brother Minister: The Assassination of Malcolm...,Heidi Fleiss: Hollywood Madam (1995),Paris Was a Woman (1995),Paris Was a Woman (1995),...,Across the Sea of Time (1995),Paris Was a Woman (1995),Man of the Year (1995),Microcosmos: Le peuple de l'herbe (1996),Man of the Year (1995),Man of the Year (1995),Looking for Richard (1996),Across the Sea of Time (1995),Thirty-Two Short Films About Glenn Gould (1993),Microcosmos: Le peuple de l'herbe (1996)
22,Wonderland (1997),Paradise Lost: The Child Murders at Robin Hood...,"Great Day in Harlem, A (1994)",Paris Was a Woman (1995),Across the Sea of Time (1995),"Wonderful, Horrible Life of Leni Riefenstahl, ...","Haunted World of Edward D. Wood Jr., The (1995)","Endless Summer 2, The (1994)",Year of the Horse (1997),Unzipped (1995),...,Man of the Year (1995),Year of the Horse (1997),"Wonderful, Horrible Life of Leni Riefenstahl, ...",Fire on the Mountain (1996),"Celluloid Closet, The (1995)","Celluloid Closet, The (1995)","Perfect Candidate, A (1996)",Ayn Rand: A Sense of Life (1997),"Celluloid Closet, The (1995)",Fire on the Mountain (1996)
23,Across the Sea of Time (1995),Wonderland (1997),"Perfect Candidate, A (1996)",Year of the Horse (1997),Man of the Year (1995),Across the Sea of Time (1995),Maya Lin: A Strong Clear Vision (1994),"War Room, The (1993)",Unzipped (1995),Grateful Dead (1995),...,Thirty-Two Short Films About Glenn Gould (1993),Unzipped (1995),Microcosmos: Le peuple de l'herbe (1996),Across the Sea of Time (1995),"Great Day in Harlem, A (1994)","Great Day in Harlem, A (1994)",Paris Was a Woman (1995),"Gate of Heavenly Peace, The (1995)","Great Day in Harlem, A (1994)","Wonderful, Horrible Life of Leni Riefenstahl, ..."
24,Man of the Year (1995),Fire on the Mountain (1996),Paris Was a Woman (1995),Wonderland (1997),"Celluloid Closet, The (1995)",Man of the Year (1995),Paradise Lost: The Child Murders at Robin Hood...,Koyaanisqatsi (1983),Grateful Dead (1995),"Fast, Cheap & Out of Control (1997)",...,"Great Day in Harlem, A (1994)",Grateful Dead (1995),Wonderland (1997),Man of the Year (1995),Paris Was a Woman (1995),Paris Was a Woman (1995),Year of the Horse (1997),"Haunted World of Edward D. Wood Jr., The (1995)","Perfect Candidate, A (1996)",Across the Sea of Time (1995)
25,"Great Day in Harlem, A (1994)",Across the Sea of Time (1995),Year of the Horse (1997),Maya Lin: A Strong Clear Vision (1994),"Great Day in Harlem, A (1994)","Great Day in Harlem, A (1994)","Thin Blue Line, The (1988)","Fast, Cheap & Out of Control (1997)","Fast, Cheap & Out of Control (1997)",Koyaanisqatsi (1983),...,"Perfect Candidate, A (1996)","Fast, Cheap & Out of Control (1997)",Nico Icon (1995),Thirty-Two Short Films About Glenn Gould (1993),Year of the Horse (1997),Year of the Horse (1997),Unzipped (1995),Brother Minister: The Assassination of Malcolm...,Paris Was a Woman (1995),Man of the Year (1995)
26,"Perfect Candidate, A (1996)",Man of the Year (1995),Grateful Dead (1995),Heidi Fleiss: Hollywood Madam (1995),"Perfect Candidate, A (1996)","Perfect Candidate, A (1996)",Paris Is Burning (1990),Man of the Year (1995),Koyaanisqatsi (1983),Anne Frank Remembered (1995),...,Paris Was a Woman (1995),Koyaanisqatsi (1983),Brother Minister: The Assassination of Malcolm...,"Great Day in Harlem, A (1994)",Unzipped (1995),Unzipped (1995),Grateful Dead (1995),Maya Lin: A Strong Clear Vision (1994),Year of the Horse (1997),"Great Day in Harlem, A (1994)"
27,Paris Was a Woman (1995),"Celluloid Closet, The (1995)",Koyaanisqatsi (1983),"War Room, The (1993)",Paris Was a Woman (1995),Paris Was a Woman (1995),Fire on the Mountain (1996),Microcosmos: Le peuple de l'herbe (1996),Anne Frank Remembered (1995),Heidi Fleiss: Hollywood Madam (1995),...,Year of the Horse (1997),Anne Frank Remembered (1995),"Haunted World of Edward D. Wood Jr., The (1995)",Paris Was a Woman (1995),Grateful Dead (1995),Grateful Dead (1995),"Fast, Cheap & Out of Control (1997)",Fire on the Mountain (1996),Unzipped (1995),"Perfect Candidate, A (1996)"
28,Year of the Horse (1997),"Great Day in Harlem, A (1994)",Anne Frank Remembered (1995),Brother Minister: The Assassination of Malcolm...,Year of the Horse (1997),Unzipped (1995),"Wonderful, Horrible Life of Leni Riefenstahl, ...",Paradise Lost: The Child Murders at Robin Hood...,Heidi Fleiss: Hollywood Madam (1995),Jupiter's Wife (1994),...,Unzipped (1995),Heidi Fleiss: Hollywood Madam (1995),Maya Lin: A Strong Clear Vision (1994),Year of the Horse (1997),"Fast, Cheap & Out of Control (1997)","Fast, Cheap & Out of Control (1997)",Jupiter's Wife (1994),"Wonderful, Horrible Life of Leni Riefenstahl, ...",Grateful Dead (1995),Paris Was a Woman (1995)
29,Grateful Dead (1995),"Perfect Candidate, A (1996)",Heidi Fleiss: Hollywood Madam (1995),Marlene Dietrich: Shadow and Light (1996),Unzipped (1995),Grateful Dead (1995),Across the Sea of Time (1995),Brother Minister: The Assassination of Malcolm...,Jupiter's Wife (1994),"War Room, The (1993)",...,Grateful Dead (1995),Jupiter's Wife (1994),Fire on the Mountain (1996),Unzipped (1995),Anne Frank Remembered (1995),Anne Frank Remembered (1995),"War Room, The (1993)","Great Day in Harlem, A (1994)",Anne Frank Remembered (1995),Year of the Horse (1997)
30,Anne Frank Remembered (1995),Paris Was a Woman (1995),Jupiter's Wife (1994),"Great Day in Harlem, A (1994)",Jupiter's Wife (1994),Anne Frank Remembered (1995),Thirty-Two Short Films About Glenn Gould (1993),"Big One, The (1997)","War Room, The (1993)",When We Were Kings (1996),...,Heidi Fleiss: Hollywood Madam (1995),"War Room, The (1993)",Across the Sea of Time (1995),Grateful Dead (1995),Jupiter's Wife (1994),Jupiter's Wife (1994),When We Were Kings (1996),"Perfect Candidate, A (1996)",Heidi Fleiss: Hollywood Madam (1995),Jupiter's Wife (1994)
31,"War Room, The (1993)",Grateful Dead (1995),When We Were Kings (1996),Fire on the Mountain (1996),"War Room, The (1993)",Jupiter's Wife (1994),"Great Day in Harlem, A (1994)","Haunted World of Edward D. Wood Jr., The (1995)",When We Were Kings (1996),"Endless Summer 2, The (1994)",...,Jupiter's Wife (1994),"Endless Summer 2, The (1994)","Great Day in Harlem, A (1994)",Jupiter's Wife (1994),"War Room, The (1993)","War Room, The (1993)","Endless Summer 2, The (1994)",Paris Was a Woman (1995),Jupiter's Wife (1994),"War Room, The (1993)"

In [538]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Drama, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [539]:
#administrator

In [540]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Drama, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [541]:
#artist

In [542]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Drama, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [543]:
#doctor

In [544]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Drama, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [545]:
#educator

In [546]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Drama, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [547]:
#engineer

In [548]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Drama, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [549]:
#entertainment

In [550]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Drama, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [551]:
#executive

In [552]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Drama, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [553]:
#healthcare

In [554]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Drama, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [555]:
#homemaker

In [556]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Drama, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [557]:
#lawyer

In [558]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Drama, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [559]:
#librarian

In [560]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Drama, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [561]:
#marketing

In [562]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Drama, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [563]:
#none

In [564]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Drama, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [565]:
#other

In [566]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Drama, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [567]:
#programmer

In [568]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Drama, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [569]:
#retired

In [570]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Drama, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [571]:
#salesman

In [572]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Drama, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [573]:
#scientist

In [574]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Drama, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [575]:
#student

In [576]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Drama, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [577]:
#technician

In [578]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Drama, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [579]:
#writer

In [580]:
Drama_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Drama_occupation_rank = Drama_occupation_rank.reset_index(drop=True)
Drama_occupation_rank.index += 1
Drama_occupation_rank = Drama_occupation_rank.rename_axis("Rank")
Drama_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,"English Patient, The (1996)",Contact (1997),"English Patient, The (1996)","English Patient, The (1996)",Fargo (1996),Contact (1997),Contact (1997),"Godfather, The (1972)",Contact (1997),"English Patient, The (1996)",...,Contact (1997),Contact (1997),"English Patient, The (1996)",Fargo (1996),Fargo (1996),Fargo (1996),Fargo (1996),Contact (1997),Fargo (1996),Fargo (1996)
2,Contact (1997),Fargo (1996),Titanic (1997),Fargo (1996),"Silence of the Lambs, The (1991)",Fargo (1996),Jerry Maguire (1996),Titanic (1997),Volcano (1997),Contact (1997),...,"English Patient, The (1996)",Twelve Monkeys (1995),Contact (1997),"Empire Strikes Back, The (1980)","Godfather, The (1972)","Godfather, The (1972)",Contact (1997),Twelve Monkeys (1995),Contact (1997),"English Patient, The (1996)"
3,Jerry Maguire (1996),"English Patient, The (1996)",Fargo (1996),Contact (1997),Pulp Fiction (1994),Twelve Monkeys (1995),"English Patient, The (1996)",Fargo (1996),Titanic (1997),Evita (1996),...,"Godfather, The (1972)","Time to Kill, A (1996)","Godfather, The (1972)",Pulp Fiction (1994),Jerry Maguire (1996),Jerry Maguire (1996),"English Patient, The (1996)",Fargo (1996),"Empire Strikes Back, The (1980)",Contact (1997)
4,Fargo (1996),"Godfather, The (1972)",Ransom (1996),"Godfather, The (1972)","Empire Strikes Back, The (1980)","English Patient, The (1996)",Fargo (1996),"English Patient, The (1996)",Wag the Dog (1997),Fargo (1996),...,Seven Years in Tibet (1997),Fargo (1996),Fargo (1996),Twelve Monkeys (1995),Titanic (1997),Titanic (1997),"Godfather, The (1972)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Silence of the Lambs, The (1991)"
5,"Silence of the Lambs, The (1991)",Chasing Amy (1997),Eat Drink Man Woman (1994),Sense and Sensibility (1995),E.T. the Extra-Terrestrial (1982),Jerry Maguire (1996),Twelve Monkeys (1995),Contact (1997),"English Patient, The (1996)",Amadeus (1984),...,Evita (1996),Phenomenon (1996),Jerry Maguire (1996),Contact (1997),"English Patient, The (1996)","English Patient, The (1996)",Leaving Las Vegas (1995),"Empire Strikes Back, The (1980)",Pulp Fiction (1994),"Godfather, The (1972)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,"War at Home, The (1996)","War at Home, The (1996)","War at Home, The (1996)","War at Home, The (1996)","Sunchaser, The (1996)","War at Home, The (1996)","War at Home, The (1996)","War at Home, The (1996)","War at Home, The (1996)","War at Home, The (1996)",...,"War at Home, The (1996)","War at Home, The (1996)",Mamma Roma (1962),"War at Home, The (1996)","War at Home, The (1996)","War at Home, The (1996)","War at Home, The (1996)",Kika (1993),"War at Home, The (1996)","War at Home, The (1996)"
722,Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),"War at Home, The (1996)",Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),...,Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Sweet Nothing (1995),Mamma Roma (1962),Sweet Nothing (1995),Sweet Nothing (1995)
723,Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Sweet Nothing (1995),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),...,Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),Mat' i syn (1997),"Sunchaser, The (1996)",Mat' i syn (1997),Mat' i syn (1997)
724,Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Mat' i syn (1997),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),...,Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),"War at Home, The (1996)",Sliding Doors (1998),Sliding Doors (1998)
725,Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Sliding Doors (1998),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),...,Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991),Scream of Stone (Schrei aus Stein) (1991)

In [581]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Fantasy, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [582]:
#administrator

In [583]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Fantasy, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [584]:
#artist

In [585]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Fantasy, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [586]:
#doctor

In [587]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Fantasy, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [588]:
#educator

In [589]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Fantasy, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [590]:
#engineer

In [591]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Fantasy, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [592]:
#entertainment

In [593]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Fantasy, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [594]:
#executive

In [595]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Fantasy, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [596]:
#healthcare

In [597]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Fantasy, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [598]:
#homemaker

In [599]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Fantasy, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [600]:
#lawyer

In [601]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Fantasy, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [602]:
#librarian

In [603]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Fantasy, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [604]:
#marketing

In [605]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Fantasy, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [606]:
#none

In [607]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Fantasy, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [608]:
#other

In [609]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Fantasy, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [610]:
#programmer

In [611]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Fantasy, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [612]:
#retired

In [613]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Fantasy, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [614]:
#salesman

In [615]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Fantasy, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [616]:
#scientist

In [617]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Fantasy, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [618]:
#student

In [619]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Fantasy, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [620]:
#technician

In [621]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Fantasy, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [622]:
#writer

In [623]:
Fantasy_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Fantasy_occupation_rank = Fantasy_occupation_rank.reset_index(drop=True)
Fantasy_occupation_rank.index += 1
Fantasy_occupation_rank = Fantasy_occupation_rank.rename_axis("Rank")
Fantasy_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),"Mask, The (1994)",E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),"Nutty Professor, The (1996)",E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),"Mask, The (1994)",...,E.T. the Extra-Terrestrial (1982),Dragonheart (1996),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982),E.T. the Extra-Terrestrial (1982)
2,"Mask, The (1994)",Dragonheart (1996),FairyTale: A True Story (1997),Dragonheart (1996),Dragonheart (1996),"Nutty Professor, The (1996)",E.T. the Extra-Terrestrial (1982),Dragonheart (1996),Space Jam (1996),"Nutty Professor, The (1996)",...,"20,000 Leagues Under the Sea (1954)","Nutty Professor, The (1996)",Dragonheart (1996),Dragonheart (1996),"Mask, The (1994)","Mask, The (1994)","Nutty Professor, The (1996)","Nutty Professor, The (1996)","Mask, The (1994)",Heavenly Creatures (1994)
3,Dragonheart (1996),Space Jam (1996),E.T. the Extra-Terrestrial (1982),"Mask, The (1994)","Nutty Professor, The (1996)",Heavenly Creatures (1994),Space Jam (1996),"Nutty Professor, The (1996)",Flubber (1997),E.T. the Extra-Terrestrial (1982),...,FairyTale: A True Story (1997),E.T. the Extra-Terrestrial (1982),"Nutty Professor, The (1996)","Mask, The (1994)",Dragonheart (1996),Dragonheart (1996),Space Jam (1996),Dragonheart (1996),Jumanji (1995),"Nutty Professor, The (1996)"
4,"Nutty Professor, The (1996)","20,000 Leagues Under the Sea (1954)",Dragonheart (1996),Heavenly Creatures (1994),"Mask, The (1994)",Dragonheart (1996),Dragonheart (1996),Heavenly Creatures (1994),"Mask, The (1994)",Heavenly Creatures (1994),...,"Nutty Professor, The (1996)",Space Jam (1996),"Mask, The (1994)",Space Jam (1996),"20,000 Leagues Under the Sea (1954)","20,000 Leagues Under the Sea (1954)","Mask, The (1994)","Mask, The (1994)","Nutty Professor, The (1996)",Space Jam (1996)
5,"20,000 Leagues Under the Sea (1954)","Nutty Professor, The (1996)",Space Jam (1996),"20,000 Leagues Under the Sea (1954)","20,000 Leagues Under the Sea (1954)",Space Jam (1996),FairyTale: A True Story (1997),"20,000 Leagues Under the Sea (1954)","20,000 Leagues Under the Sea (1954)","20,000 Leagues Under the Sea (1954)",...,Space Jam (1996),"20,000 Leagues Under the Sea (1954)",Jumanji (1995),Jumanji (1995),"Nutty Professor, The (1996)","Nutty Professor, The (1996)",Dragonheart (1996),Jumanji (1995),Dragonheart (1996),"Mask, The (1994)"
6,Jumanji (1995),Warriors of Virtue (1997),Flubber (1997),"Nutty Professor, The (1996)",Jumanji (1995),Jumanji (1995),"20,000 Leagues Under the Sea (1954)",Jumanji (1995),FairyTale: A True Story (1997),"Kid in King Arthur's Court, A (1995)",...,"Mask, The (1994)",Jumanji (1995),"Indian in the Cupboard, The (1995)","Nutty Professor, The (1996)",Heavenly Creatures (1994),Heavenly Creatures (1994),Heavenly Creatures (1994),Space Jam (1996),"20,000 Leagues Under the Sea (1954)",Jumanji (1995)
7,Flubber (1997),FairyTale: A True Story (1997),Drop Dead Fred (1991),Jumanji (1995),Space Jam (1996),"Mask, The (1994)",Heavenly Creatures (1994),"Pagemaster, The (1994)","Nutty Professor, The (1996)",Jumanji (1995),...,Dragonheart (1996),Flubber (1997),Space Jam (1996),Flubber (1997),FairyTale: A True Story (1997),FairyTale: A True Story (1997),"Indian in the Cupboard, The (1995)","20,000 Leagues Under the Sea (1954)",Space Jam (1996),Dragonheart (1996)
8,Space Jam (1996),Heavenly Creatures (1994),"20,000 Leagues Under the Sea (1954)",Flubber (1997),Escape to Witch Mountain (1975),FairyTale: A True Story (1997),Bogus (1996),Space Jam (1996),Dragonheart (1996),Flubber (1997),...,Jumanji (1995),"Mask, The (1994)",Heavenly Creatures (1994),Heavenly Creatures (1994),Jumanji (1995),Jumanji (1995),Escape to Witch Mountain (1975),Flubber (1997),"Indian in the Cupboard, The (1995)","NeverEnding Story III, The (1994)"
9,Escape to Witch Mountain (1975),"Simple Wish, A (1997)","Nutty Professor, The (1996)","Indian in the Cupboard, The (1995)",Heavenly Creatures (1994),Flubber (1997),Flubber (1997),Flubber (1997),"NeverEnding Story III, The (1994)",Drop Dead Fred (1991),...,Bogus (1996),FairyTale: A True Story (1997),"20,000 Leagues Under the Sea (1954)","20,000 Leagues Under the Sea (1954)",Bogus (1996),Bogus (1996),"20,000 Leagues Under the Sea (1954)",Heavenly Creatures (1994),"NeverEnding Story III, The (1994)",Flubber (1997)
10,"Indian in the Cupboard, The (1995)",Star Kid (1997),"NeverEnding Story III, The (1994)",Space Jam (1996),Bogus (1996),"Simple Wish, A (1997)",Kazaam (1996),"Indian in the Cupboard, The (1995)",Heavenly Creatures (1994),Escape to Witch Mountain (1975),...,Flubber (1997),"NeverEnding Story III, The (1994)",Flubber (1997),"Indian in the Cupboard, The (1995)",Flubber (1997),Flubber (1997),FairyTale: A True Story (1997),Drop Dead Fred (1991),FairyTale: A True Story (1997),Drop Dead Fred (1991)
11,"Kid in King Arthur's Court, A (1995)","Mask, The (1994)",Heavenly Creatures (1994),FairyTale: A True Story (1997),"Indian in the Cupboard, The (1995)","20,000 Leagues Under the Sea (1954)","Mask, The (1994)","Hungarian Fairy Tale, A (1987)","Kid in King Arthur's Court, A (1995)",FairyTale: A True Story (1997),...,Escape to Witch Mountain (1975),Heavenly Creatures (1994),FairyTale: A True Story (1997),"Kid in King Arthur's Court, A (1995)","Indian in the Cupboard, The (1995)","Indian in the Cupboard, The (1995)","NeverEnding Story III, The (1994)","Kid in King Arthur's Court, A (1995)",Heavenly Creatures (1994),"20,000 Leagues Under the Sea (1954)"
12,Heavenly Creatures (1994),"NeverEnding Story III, The (1994)","Kid in King Arthur's Court, A (1995)",Bogus (1996),Kazaam (1996),"NeverEnding Story III, The (1994)","Kid in King Arthur's Court, A (1995)",Escape to Witch Mountain (1975),Jumanji (1995),Dragonheart (1996),...,"NeverEnding Story III, The (1994)","Kid in King Arthur's Court, A (1995)",Drop Dead Fred (1991),Bogus (1996),Escape to Witch Mountain (1975),Escape to Witch Mountain (1975),"Kid in King Arthur's Court, A (1995)","Indian in the Cupboard, The (1995)","Kid in King Arthur's Court, A (1995)","Kid in King Arthur's Court, A (1995)"
13,Bogus (1996),"Kid in King Arthur's Court, A (1995)",Jumanji (1995),Escape to Witch Mountain (1975),FairyTale: A True Story (1997),"Kid in King Arthur's Court, A (1995)",Jumanji (1995),Drop Dead Fred (1991),Bogus (1996),"NeverEnding Story III, The (1994)",...,Heavenly Creatures (1994),Bogus (1996),Escape to Witch Mountain (1975),"Pagemaster, The (1994)","NeverEnding Story III, The (1994)","NeverEnding Story III, The (1994)",Jumanji (1995),Escape to Witch Mountain (1975),Bogus (1996),"Indian in the Cupboard, The (1995)"
14,"NeverEnding Story III, The (1994)",Jumanji (1995),Bogus (1996),"NeverEnding Story III, The (1994)","Kid in King Arthur's Court, A (1995)",Bogus (1996),"Indian in the Cupboard, The (1995)","Mask, The (1994)","Indian in the Cupboard, The (1995)",Space Jam (1996),...,"Kid in King Arthur's Court, A (1995)","Indian in the Cupboard, The (1995)",Bogus (1996),Kazaam (1996),"Kid in King Arthur's Court, A (1995)","Kid in King Arthur's Court, A (1995)",Bogus (1996),FairyTale: A True Story (1997),Flubber (1997),"Pagemaster, The (1994)"
15,Drop Dead Fred (1991),Bogus (1996),"Indian in the Cupboard, The (1995)","Kid in King Arthur's Court, A (1995)","NeverEnding Story III, The (1994)","Indian in the Cupboard, The (1995)",Escape to Witch Mountain (1975),Bogus (1996),Drop Dead Fred (1991),Bogus (1996),...,"Indian in the Cupboard, The (1995)",Drop Dead Fred (1991),Star Kid (1997),"NeverEnding Story III, The (1994)",Space Jam (1996),Space Jam (1996),Flubber (1997),Bogus (1996),Drop Dead Fred (1991),Bogus (1996)
16,FairyTale: A True Story (1997),Flubber (1997),"Pagemaster, The (1994)",Drop Dead Fred (1991),Flubber (1997),Drop Dead Fred (1991),"NeverEnding Story III, The (1994)","Kid in King Arthur's Court, A (1995)","Pagemaster, The (1994)","Indian in the Cupboard, The (1995)",...,Drop Dead Fred (1991),"Pagemaster, The (1994)",Warriors of Virtue (1997),FairyTale: A True Story (1997),Drop Dead Fred (1991),Drop Dead Fred (1991),Drop Dead Fred (1991),"Pagemaster, The (1994)","Pagemaster, The (1994)",Escape to Witch Mountain (1975)
17,Warriors of Virtue (1997),"Indian in the Cupboard, The (1995)",Escape to Witch Mountain (1975),"Pagemaster, The (1994)",Drop Dead Fred (1991),"Pagemaster, The (1994)",Drop Dead Fred (1991),"NeverEnding Story III, The (1994)",Escape to Witch Mountain (1975),"Pagemaster, The (1994)",...,"Pagemaster, The (1994)",Escape to Witch Mountain (1975),"Kid in King Arthur's Court, A (1995)",Drop Dead Fred (1991),"Pagemaster, The (1994)","Pagemaster, The (1994)","Pagemaster, The (1994)","NeverEnding Story III, The (1994)",Escape to Witch Mountain (1975),FairyTale: A True Story (1997)
18,"Pagemaster, The (1994)",Drop Dead Fred (1991),"Simple Wish, A (1997)",Warriors of Virtue (1997),"Pagemaster, The (1994)",Escape to Witch Mountain (1975),"Pagemaster, The (1994)",FairyTale: A True Story (1997),"Simple Wish, A (1997)","Simple Wish, A (1997)",...,"Simple Wish, A (1997)","Simple Wish, A (1997)",Kazaam (1996),Escape to Witch Mountain (1975),"Simple Wish, A (1997)","Simple Wish, A (1997)","Simple Wish, A (1997)",Kazaam (1996),"Simple Wish, A (1997)","Simple Wish, A (1997)"
19,"Simple Wish, A (1997)","Pagemaster, The (1994)",Star Kid (1997),"Simple Wish, A (1997)","Simple Wish, A (1997)",Star Kid (1997),"Simple Wish, A (1997)",Warriors of Virtue (1997),Star Kid (1997),Star Kid (1997),...,Star Kid (1997),Star Kid (1997),"NeverEnding Story III, The (1994)","Simple Wish, A (1997)",Star Kid (1997),Star Kid (1997),Star Kid (1997),Warriors of Virtue (1997),Star Kid (1997),Star Kid (1997)
20,Star Kid (1997),Escape to Witch Mountain (1975),Kazaam (1996),Star Kid (1997),Star Kid (1997),Kazaam (1996),Star Kid (1997),"Simple Wish, A (1997)",Kazaam (1996),Kazaam (1996),...,Kazaam (1996),Kazaam (1996),"Pagemaster, The (1994)",Star Kid (1997),Kazaam (1996),Kazaam (1996),Kazaam (1996),"Simple Wish, A (1997)",Kazaam (1996),Kazaam (1996)
21,Kazaam (1996),Kazaam (1996),"Hungarian Fairy Tale, A (1987)",Kazaam (1996),"Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)",Star Kid (1997),"Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)",...,"Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)","Simple Wish, A (1997)","Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)",Star Kid (1997),"Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)"
22,"Hungarian Fairy Tale, A (1987)","Hungarian Fairy Tale, A (1987)",Warriors of Virtue (1997),"Hungarian Fairy Tale, A (1987)",Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Kazaam (1996),Warriors of Virtue (1997),Warriors of Virtue (1997),...,Warriors of Virtue (1997),Warriors of Virtue (1997),"Hungarian Fairy Tale, A (1987)",Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),Warriors of Virtue (1997),"Hungarian Fairy Tale, A (1987)",Warriors of Virtue (1997),Warriors of Virtue (1997)

In [624]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(FilmNoir, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [625]:
#administrator

In [626]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(FilmNoir, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [627]:
#artist

In [628]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(FilmNoir, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [629]:
#doctor

In [630]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(FilmNoir, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [631]:
#educator

In [632]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(FilmNoir, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [633]:
#engineer

In [634]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(FilmNoir, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [635]:
#entertainment

In [636]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(FilmNoir, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [637]:
#executive

In [638]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(FilmNoir, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [639]:
#healthcare

In [640]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(FilmNoir, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [641]:
#homemaker

In [642]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(FilmNoir, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [643]:
#lawyer

In [644]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(FilmNoir, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [645]:
#librarian

In [646]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(FilmNoir, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [647]:
#marketing

In [648]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(FilmNoir, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [649]:
#none

In [650]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(FilmNoir, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [651]:
#other

In [652]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(FilmNoir, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [653]:
#programmer

In [654]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(FilmNoir, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [655]:
#retired

In [656]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(FilmNoir, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [657]:
#salesman

In [658]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(FilmNoir, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [659]:
#scientist

In [660]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(FilmNoir, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [661]:
#student

In [662]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(FilmNoir, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [663]:
#technician

In [664]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(FilmNoir, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [665]:
#writer

In [666]:
FilmNoir_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
FilmNoir_occupation_rank = FilmNoir_occupation_rank.reset_index(drop=True)
FilmNoir_occupation_rank.index += 1
FilmNoir_occupation_rank = FilmNoir_occupation_rank.rename_axis("Rank")
FilmNoir_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Blade Runner (1982),Blade Runner (1982),L.A. Confidential (1997),L.A. Confidential (1997),Blade Runner (1982),L.A. Confidential (1997),L.A. Confidential (1997),L.A. Confidential (1997),L.A. Confidential (1997),L.A. Confidential (1997),...,L.A. Confidential (1997),Blade Runner (1982),L.A. Confidential (1997),Blade Runner (1982),L.A. Confidential (1997),L.A. Confidential (1997),L.A. Confidential (1997),Blade Runner (1982),Blade Runner (1982),L.A. Confidential (1997)
2,L.A. Confidential (1997),L.A. Confidential (1997),"Maltese Falcon, The (1941)",Blade Runner (1982),L.A. Confidential (1997),Blade Runner (1982),Blade Runner (1982),"Maltese Falcon, The (1941)",Hoodlum (1997),Sunset Blvd. (1950),...,Blade Runner (1982),L.A. Confidential (1997),Blade Runner (1982),L.A. Confidential (1997),Chinatown (1974),Chinatown (1974),Blade Runner (1982),L.A. Confidential (1997),"Maltese Falcon, The (1941)",Blade Runner (1982)
3,Chinatown (1974),"Maltese Falcon, The (1941)",Blade Runner (1982),"Manchurian Candidate, The (1962)","Maltese Falcon, The (1941)",Hoodlum (1997),Mulholland Falls (1996),Chinatown (1974),Mulholland Falls (1996),Chinatown (1974),...,"Maltese Falcon, The (1941)","Grifters, The (1990)","Maltese Falcon, The (1941)",Chinatown (1974),"Manchurian Candidate, The (1962)","Manchurian Candidate, The (1962)",Chinatown (1974),"Maltese Falcon, The (1941)",L.A. Confidential (1997),Chinatown (1974)
4,"Manchurian Candidate, The (1962)","Manchurian Candidate, The (1962)",Sunset Blvd. (1950),Chinatown (1974),"Grifters, The (1990)","Grifters, The (1990)","Maltese Falcon, The (1941)",Blade Runner (1982),Blade Runner (1982),"Manchurian Candidate, The (1962)",...,"Manchurian Candidate, The (1962)",Hoodlum (1997),Chinatown (1974),"Maltese Falcon, The (1941)",Blade Runner (1982),Blade Runner (1982),M (1931),"Manchurian Candidate, The (1962)",Chinatown (1974),"Maltese Falcon, The (1941)"
5,"Maltese Falcon, The (1941)",Chinatown (1974),"Grifters, The (1990)","Maltese Falcon, The (1941)",Chinatown (1974),Cape Fear (1962),Hoodlum (1997),Cape Fear (1962),"Maltese Falcon, The (1941)",Blade Runner (1982),...,"Grifters, The (1990)","Manchurian Candidate, The (1962)",Cape Fear (1962),"Manchurian Candidate, The (1962)","Maltese Falcon, The (1941)","Maltese Falcon, The (1941)","Maltese Falcon, The (1941)",Cape Fear (1962),Hoodlum (1997),"Manchurian Candidate, The (1962)"
6,"Grifters, The (1990)","Big Sleep, The (1946)",Hoodlum (1997),"Grifters, The (1990)","Manchurian Candidate, The (1962)",Devil in a Blue Dress (1995),Chinatown (1974),M (1931),Sunset Blvd. (1950),"Maltese Falcon, The (1941)",...,Chinatown (1974),Palmetto (1998),"Big Sleep, The (1946)",Devil in a Blue Dress (1995),"Grifters, The (1990)","Grifters, The (1990)","Grifters, The (1990)",Mulholland Falls (1996),Mulholland Falls (1996),"Big Sleep, The (1946)"
7,Sunset Blvd. (1950),Hoodlum (1997),Notorious (1946),Sunset Blvd. (1950),Cape Fear (1962),"Big Sleep, The (1946)","Manchurian Candidate, The (1962)","Big Sleep, The (1946)",Notorious (1946),"Big Sleep, The (1946)",...,Hoodlum (1997),"Maltese Falcon, The (1941)",Hoodlum (1997),Mulholland Falls (1996),"Murder, My Sweet (1944)","Murder, My Sweet (1944)",Devil in a Blue Dress (1995),Chinatown (1974),"Grifters, The (1990)",M (1931)
8,Notorious (1946),Notorious (1946),"Big Sleep, The (1946)",Laura (1944),Mulholland Falls (1996),Touch of Evil (1958),"Grifters, The (1990)","Manchurian Candidate, The (1962)","Big Sleep, The (1946)",Notorious (1946),...,Sunset Blvd. (1950),Sunset Blvd. (1950),Mulholland Falls (1996),Cape Fear (1962),Mulholland Falls (1996),Mulholland Falls (1996),Hoodlum (1997),Hoodlum (1997),"Manchurian Candidate, The (1962)",Cape Fear (1962)
9,"Big Sleep, The (1946)",Laura (1944),Laura (1944),"Big Sleep, The (1946)",Notorious (1946),Chinatown (1974),Sunset Blvd. (1950),Hoodlum (1997),Laura (1944),"Grifters, The (1990)",...,Devil in a Blue Dress (1995),Notorious (1946),"Grifters, The (1990)","Big Sleep, The (1946)",Devil in a Blue Dress (1995),Devil in a Blue Dress (1995),Sunset Blvd. (1950),Devil in a Blue Dress (1995),Cape Fear (1962),Sunset Blvd. (1950)
10,Mulholland Falls (1996),"Grifters, The (1990)",Touch of Evil (1958),Notorious (1946),"Big Sleep, The (1946)","Manchurian Candidate, The (1962)","Big Sleep, The (1946)",Mulholland Falls (1996),"Grifters, The (1990)",Cape Fear (1962),...,Notorious (1946),"Big Sleep, The (1946)","Manchurian Candidate, The (1962)",Sunset Blvd. (1950),Cape Fear (1962),Cape Fear (1962),"Big Sleep, The (1946)",Touch of Evil (1958),Sunset Blvd. (1950),Hoodlum (1997)
11,Devil in a Blue Dress (1995),M (1931),Chinatown (1974),Hoodlum (1997),Devil in a Blue Dress (1995),Dark City (1998),Notorious (1946),Devil in a Blue Dress (1995),Touch of Evil (1958),Devil in a Blue Dress (1995),...,"Big Sleep, The (1946)",Laura (1944),Sunset Blvd. (1950),Notorious (1946),Touch of Evil (1958),Touch of Evil (1958),"Manchurian Candidate, The (1962)","Grifters, The (1990)","Big Sleep, The (1946)","Grifters, The (1990)"
12,Laura (1944),Cape Fear (1962),M (1931),Mulholland Falls (1996),Sunset Blvd. (1950),Mulholland Falls (1996),Devil in a Blue Dress (1995),Touch of Evil (1958),Chinatown (1974),Laura (1944),...,Cape Fear (1962),Touch of Evil (1958),Laura (1944),"Grifters, The (1990)",M (1931),M (1931),Cape Fear (1962),Dark City (1998),Laura (1944),Notorious (1946)
13,Hoodlum (1997),Sunset Blvd. (1950),"Manchurian Candidate, The (1962)",Cape Fear (1962),Laura (1944),"Maltese Falcon, The (1941)",Laura (1944),"Grifters, The (1990)",M (1931),M (1931),...,Dark City (1998),Chinatown (1974),M (1931),Touch of Evil (1958),Laura (1944),Laura (1944),Mulholland Falls (1996),Notorious (1946),M (1931),Mulholland Falls (1996)
14,M (1931),Touch of Evil (1958),Cape Fear (1962),Devil in a Blue Dress (1995),Hoodlum (1997),Sunset Blvd. (1950),Touch of Evil (1958),Laura (1944),"Manchurian Candidate, The (1962)",Mulholland Falls (1996),...,Mulholland Falls (1996),M (1931),Touch of Evil (1958),Hoodlum (1997),"Big Sleep, The (1946)","Big Sleep, The (1946)",Palmetto (1998),Palmetto (1998),Devil in a Blue Dress (1995),Touch of Evil (1958)
15,Palmetto (1998),Dark City (1998),Dark City (1998),M (1931),M (1931),Notorious (1946),Cape Fear (1962),Notorious (1946),Cape Fear (1962),Hoodlum (1997),...,Laura (1944),Cape Fear (1962),Notorious (1946),M (1931),Sunset Blvd. (1950),Sunset Blvd. (1950),Notorious (1946),M (1931),He Walked by Night (1948),Devil in a Blue Dress (1995)
16,Cape Fear (1962),Devil in a Blue Dress (1995),Devil in a Blue Dress (1995),"Murder, My Sweet (1944)","Murder, My Sweet (1944)",Laura (1944),Dark City (1998),Sunset Blvd. (1950),Dark City (1998),Touch of Evil (1958),...,Touch of Evil (1958),Dark City (1998),Dark City (1998),Laura (1944),Notorious (1946),Notorious (1946),Laura (1944),"Big Sleep, The (1946)",Notorious (1946),Laura (1944)
17,Touch of Evil (1958),Mulholland Falls (1996),Mulholland Falls (1996),Touch of Evil (1958),Touch of Evil (1958),M (1931),"Murder, My Sweet (1944)",Suture (1993),Devil in a Blue Dress (1995),Dark City (1998),...,M (1931),Devil in a Blue Dress (1995),Devil in a Blue Dress (1995),Dark City (1998),Crossfire (1947),Crossfire (1947),Touch of Evil (1958),Sunset Blvd. (1950),Touch of Evil (1958),Suture (1993)
18,Crossfire (1947),"Murder, My Sweet (1944)","Murder, My Sweet (1944)",Dark City (1998),Raw Deal (1948),"Murder, My Sweet (1944)",M (1931),T-Men (1947),"Murder, My Sweet (1944)","Murder, My Sweet (1944)",...,"Murder, My Sweet (1944)",Mulholland Falls (1996),"Murder, My Sweet (1944)","Murder, My Sweet (1944)",Hoodlum (1997),Hoodlum (1997),Dark City (1998),Laura (1944),Dark City (1998),Dark City (1998)
19,Dark City (1998),Crossfire (1947),Crossfire (1947),Crossfire (1947),Dark City (1998),Crossfire (1947),Crossfire (1947),Dark City (1998),Crossfire (1947),Crossfire (1947),...,Crossfire (1947),"Murder, My Sweet (1944)",Crossfire (1947),Crossfire (1947),Dark City (1998),Dark City (1998),"Murder, My Sweet (1944)",Suture (1993),"Murder, My Sweet (1944)","Murder, My Sweet (1944)"
20,"Murder, My Sweet (1944)",Palmetto (1998),Palmetto (1998),Palmetto (1998),Crossfire (1947),Palmetto (1998),Palmetto (1998),"Murder, My Sweet (1944)",Palmetto (1998),Palmetto (1998),...,Palmetto (1998),Crossfire (1947),Palmetto (1998),Palmetto (1998),Palmetto (1998),Palmetto (1998),Crossfire (1947),"Murder, My Sweet (1944)",Crossfire (1947),Crossfire (1947)
21,Suture (1993),Suture (1993),Suture (1993),Suture (1993),Palmetto (1998),Suture (1993),Suture (1993),Crossfire (1947),Suture (1993),Suture (1993),...,Suture (1993),Suture (1993),Suture (1993),Suture (1993),Suture (1993),Suture (1993),Suture (1993),Crossfire (1947),Palmetto (1998),Palmetto (1998)
22,Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Suture (1993),Raw Deal (1948),Raw Deal (1948),Palmetto (1998),Raw Deal (1948),Raw Deal (1948),...,Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Raw Deal (1948),Suture (1993),Raw Deal (1948)
23,T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),Raw Deal (1948),T-Men (1947),T-Men (1947),...,T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),T-Men (1947),Raw Deal (1948),T-Men (1947)
24,He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),...,He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),He Walked by Night (1948),T-Men (1947),He Walked by Night (1948)

In [667]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Horror, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [668]:
#administrator

In [669]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Horror, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [670]:
#artist

In [671]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Horror, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [672]:
#doctor

In [673]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Horror, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [674]:
#educator

In [675]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Horror, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [676]:
#engineer

In [677]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Horror, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [678]:
#entertainment

In [679]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Horror, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [680]:
#executive

In [681]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Horror, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [682]:
#healthcare

In [683]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Horror, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [684]:
#homemaker

In [685]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Horror, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [686]:
#lawyer

In [687]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Horror, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [688]:
#librarian

In [689]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Horror, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [690]:
#marketing

In [691]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Horror, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [692]:
#none

In [693]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Horror, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [694]:
#other

In [695]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Horror, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [696]:
#programmer

In [697]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Horror, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [698]:
#retired

In [699]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Horror, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [700]:
#salesman

In [701]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Horror, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [702]:
#scientist

In [703]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Horror, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [704]:
#student

In [705]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Horror, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [706]:
#technician

In [707]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Horror, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [708]:
#writer

In [709]:
Horror_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Horror_occupation_rank = Horror_occupation_rank.reset_index(drop=True)
Horror_occupation_rank.index += 1
Horror_occupation_rank = Horror_occupation_rank.rename_axis("Rank")
Horror_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Scream (1996),Scream (1996),Psycho (1960),Scream (1996),Alien (1979),Scream (1996),Scream (1996),Scream (1996),Scream (1996),Scream (1996),...,"Devil's Advocate, The (1997)",Scream (1996),Scream (1996),Alien (1979),"Devil's Advocate, The (1997)","Devil's Advocate, The (1997)",Scream (1996),Scream (1996),Alien (1979),Scream (1996)
2,Alien (1979),Alien (1979),Scream (1996),Psycho (1960),Jaws (1975),Jaws (1975),"Shining, The (1980)",Psycho (1960),"Devil's Advocate, The (1997)",Psycho (1960),...,Scream (1996),"Frighteners, The (1996)",Jaws (1975),Scream (1996),Alien (1979),Alien (1979),Jaws (1975),Jaws (1975),Young Frankenstein (1974),"Birds, The (1963)"
3,Jaws (1975),Psycho (1960),From Dusk Till Dawn (1996),Jaws (1975),Young Frankenstein (1974),"Frighteners, The (1996)",Alien (1979),Jaws (1975),Young Frankenstein (1974),"Shining, The (1980)",...,Alien (1979),Jaws (1975),"Devil's Advocate, The (1997)",Jaws (1975),Scream (1996),Scream (1996),Alien (1979),Alien (1979),Scream (1996),Alien (1979)
4,Psycho (1960),Jaws (1975),Heavy Metal (1981),Alien (1979),Scream (1996),Alien (1979),Psycho (1960),Alien (1979),Alien: Resurrection (1997),Young Frankenstein (1974),...,Jaws (1975),Tales from the Crypt Presents: Bordello of Blo...,Psycho (1960),Young Frankenstein (1974),Young Frankenstein (1974),Young Frankenstein (1974),Alien: Resurrection (1997),Psycho (1960),Jaws (1975),Jaws (1975)
5,"Shining, The (1980)",I Know What You Did Last Summer (1997),Alien (1979),Young Frankenstein (1974),Psycho (1960),"Shining, The (1980)","Devil's Advocate, The (1997)",Scream 2 (1997),"Craft, The (1996)",Alien (1979),...,"Shining, The (1980)",Alien (1979),Alien (1979),"Shining, The (1980)",Psycho (1960),Psycho (1960),"Shining, The (1980)","Shining, The (1980)","Shining, The (1980)",Psycho (1960)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Night Flier (1997),Cemetery Man (Dellamorte Dellamore) (1994),"Machine, The (1994)",Night Flier (1997),Night Flier (1997),"Machine, The (1994)",Night Flier (1997),Night Flier (1997),"Machine, The (1994)","Machine, The (1994)",...,"Machine, The (1994)","Machine, The (1994)",Cronos (1992),"Machine, The (1994)","Machine, The (1994)","Machine, The (1994)","Machine, The (1994)",Nosferatu a Venezia (1986),"Machine, The (1994)","Machine, The (1994)"
89,Nightwatch (1997),"Machine, The (1994)",Nightwatch (1997),"Machine, The (1994)","Machine, The (1994)",Nightwatch (1997),Nightwatch (1997),"Machine, The (1994)",Nightwatch (1997),Nightwatch (1997),...,Nightwatch (1997),Nightwatch (1997),"Machine, The (1994)",Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),"Machine, The (1994)",Nightwatch (1997),Nightwatch (1997)
90,"Fear, The (1995)","Fear, The (1995)","Fear, The (1995)",Nightwatch (1997),"Fear, The (1995)","Fear, The (1995)","Fear, The (1995)",Nightwatch (1997),"Fear, The (1995)","Fear, The (1995)",...,"Fear, The (1995)","Fear, The (1995)",Nightwatch (1997),"Fear, The (1995)","Fear, The (1995)","Fear, The (1995)","Fear, The (1995)",Nightwatch (1997),"Fear, The (1995)","Fear, The (1995)"
91,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,"Fear, The (1995)",Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,"Fear, The (1995)",Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,"Fear, The (1995)",Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...,Spirits of the Dead (Tre passi nel delirio) (1...
92,Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),...,Nightwatch (1997),Nightwatch (1997),Spirits of the Dead (Tre passi nel delirio) (1...,Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997)

In [710]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Musical, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [711]:
#administrator

In [712]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Musical, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [713]:
#artist

In [714]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Musical, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [715]:
#doctor

In [716]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Musical, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [717]:
#educator

In [718]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Musical, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [719]:
#engineer

In [720]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Musical, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [721]:
#entertainment

In [722]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Musical, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [723]:
#executive

In [724]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Musical, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [725]:
#healthcare

In [726]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Musical, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [727]:
#homemaker

In [728]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Musical, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [729]:
#lawyer

In [730]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Musical, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [731]:
#librarian

In [732]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Musical, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [733]:
#marketing

In [734]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Musical, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [735]:
#none

In [736]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Musical, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [737]:
#other

In [738]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Musical, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [739]:
#programmer

In [740]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Musical, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [741]:
#retired

In [742]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Musical, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [743]:
#salesman

In [744]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Musical, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [745]:
#scientist

In [746]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Musical, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [747]:
#student

In [748]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Musical, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [749]:
#technician

In [750]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Musical, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [751]:
#writer

In [752]:
Musical_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Musical_occupation_rank = Musical_occupation_rank.reset_index(drop=True)
Musical_occupation_rank.index += 1
Musical_occupation_rank = Musical_occupation_rank.rename_axis("Rank")
Musical_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Evita (1996),Evita (1996),"American in Paris, An (1951)",Evita (1996),"Blues Brothers, The (1980)",This Is Spinal Tap (1984),Evita (1996),Evita (1996),Everyone Says I Love You (1996),Evita (1996),...,Evita (1996),James and the Giant Peach (1996),"Lion King, The (1994)","Wizard of Oz, The (1939)",Evita (1996),Evita (1996),Evita (1996),Aladdin (1992),"Lion King, The (1994)",This Is Spinal Tap (1984)
2,"Wizard of Oz, The (1939)","Nightmare Before Christmas, The (1993)",This Is Spinal Tap (1984),"Blues Brothers, The (1980)",Aladdin (1992),Evita (1996),"Sound of Music, The (1965)","Sound of Music, The (1965)",Muppet Treasure Island (1996),"Blues Brothers, The (1980)",...,Anastasia (1997),Beauty and the Beast (1991),Aladdin (1992),This Is Spinal Tap (1984),My Fair Lady (1964),My Fair Lady (1964),"Wizard of Oz, The (1939)","Blues Brothers, The (1980)",Aladdin (1992),"Blues Brothers, The (1980)"
3,"Blues Brothers, The (1980)","Wizard of Oz, The (1939)",Evita (1996),Everyone Says I Love You (1996),"Wizard of Oz, The (1939)",Everyone Says I Love You (1996),"Lion King, The (1994)","Blues Brothers, The (1980)",Aladdin (1992),"Wizard of Oz, The (1939)",...,"Blues Brothers, The (1980)",Mary Poppins (1964),Beauty and the Beast (1991),"Blues Brothers, The (1980)","Sound of Music, The (1965)","Sound of Music, The (1965)","Blues Brothers, The (1980)",Evita (1996),"Wizard of Oz, The (1939)",Evita (1996)
4,"Sound of Music, The (1965)",Fantasia (1940),Everyone Says I Love You (1996),"Wizard of Oz, The (1939)","Lion King, The (1994)","Lion King, The (1994)","Wizard of Oz, The (1939)","Lion King, The (1994)","Sound of Music, The (1965)","Sound of Music, The (1965)",...,"Wizard of Oz, The (1939)",Muppet Treasure Island (1996),"Wizard of Oz, The (1939)",Aladdin (1992),"Blues Brothers, The (1980)","Blues Brothers, The (1980)","Sound of Music, The (1965)",Beauty and the Beast (1991),"Blues Brothers, The (1980)",Singin' in the Rain (1952)
5,Grease (1978),Beauty and the Beast (1991),Cinderella (1950),This Is Spinal Tap (1984),"Sound of Music, The (1965)",Aladdin (1992),"Blues Brothers, The (1980)","Wizard of Oz, The (1939)","Blues Brothers, The (1980)",Singin' in the Rain (1952),...,"Sound of Music, The (1965)",Cinderella (1950),Evita (1996),Fantasia (1940),Victor/Victoria (1982),Victor/Victoria (1982),Fantasia (1940),"Lion King, The (1994)",This Is Spinal Tap (1984),Grease (1978)
6,Everyone Says I Love You (1996),"Lion King, The (1994)","Lion King, The (1994)","Sound of Music, The (1965)",Fantasia (1940),"Wizard of Oz, The (1939)",Aladdin (1992),Muppet Treasure Island (1996),Evita (1996),Everyone Says I Love You (1996),...,My Fair Lady (1964),Anastasia (1997),"Sound of Music, The (1965)",Beauty and the Beast (1991),"Hunchback of Notre Dame, The (1996)","Hunchback of Notre Dame, The (1996)",This Is Spinal Tap (1984),"Sound of Music, The (1965)","Sound of Music, The (1965)",Everyone Says I Love You (1996)
7,Fantasia (1940),Aladdin (1992),My Fair Lady (1964),Singin' in the Rain (1952),Beauty and the Beast (1991),Dirty Dancing (1987),My Fair Lady (1964),My Fair Lady (1964),Spice World (1997),My Fair Lady (1964),...,Mary Poppins (1964),Dumbo (1941),Mary Poppins (1964),"Lion King, The (1994)","American in Paris, An (1951)","American in Paris, An (1951)",Mary Poppins (1964),"Wizard of Oz, The (1939)","Nightmare Before Christmas, The (1993)","Wizard of Oz, The (1939)"
8,This Is Spinal Tap (1984),Snow White and the Seven Dwarfs (1937),Funny Face (1957),Grease (1978),Dumbo (1941),Pink Floyd - The Wall (1982),Everyone Says I Love You (1996),Grease (1978),Blues Brothers 2000 (1998),Snow White and the Seven Dwarfs (1937),...,Everyone Says I Love You (1996),"Lion King, The (1994)",Everyone Says I Love You (1996),Grease (1978),Meet Me in St. Louis (1944),Meet Me in St. Louis (1944),Snow White and the Seven Dwarfs (1937),Snow White and the Seven Dwarfs (1937),Evita (1996),"Sound of Music, The (1965)"
9,"Lion King, The (1994)",James and the Giant Peach (1996),"Hunchback of Notre Dame, The (1996)","Lion King, The (1994)",This Is Spinal Tap (1984),Singin' in the Rain (1952),James and the Giant Peach (1996),Mary Poppins (1964),James and the Giant Peach (1996),Grease (1978),...,This Is Spinal Tap (1984),Alice in Wonderland (1951),Snow White and the Seven Dwarfs (1937),Mary Poppins (1964),Gigi (1958),Gigi (1958),Everyone Says I Love You (1996),Mary Poppins (1964),My Fair Lady (1964),Fantasia (1940)
10,My Fair Lady (1964),Mary Poppins (1964),Beauty and the Beast (1991),Mary Poppins (1964),Snow White and the Seven Dwarfs (1937),Cinderella (1950),"Hunchback of Notre Dame, The (1996)",Everyone Says I Love You (1996),Anastasia (1997),This Is Spinal Tap (1984),...,Beauty and the Beast (1991),Snow White and the Seven Dwarfs (1937),"Blues Brothers, The (1980)",Pink Floyd - The Wall (1982),Mary Poppins (1964),Mary Poppins (1964),"Great Race, The (1965)",Grease (1978),Snow White and the Seven Dwarfs (1937),Beauty and the Beast (1991)
11,Singin' in the Rain (1952),Cinderella (1950),"MisÃ©rables, Les (1995)",Beauty and the Beast (1991),Mary Poppins (1964),Fantasia (1940),Fantasia (1940),Dumbo (1941),Beauty and the Beast (1991),Gigi (1958),...,Snow White and the Seven Dwarfs (1937),Evita (1996),Grease (1978),"Nightmare Before Christmas, The (1993)",Everyone Says I Love You (1996),Everyone Says I Love You (1996),"Lion King, The (1994)",Fantasia (1940),Mary Poppins (1964),Snow White and the Seven Dwarfs (1937)
12,Mary Poppins (1964),Singin' in the Rain (1952),Anastasia (1997),My Fair Lady (1964),Pink Floyd - The Wall (1982),Hercules (1997),Mary Poppins (1964),Snow White and the Seven Dwarfs (1937),"Hunchback of Notre Dame, The (1996)",James and the Giant Peach (1996),...,Grease (1978),"Sound of Music, The (1965)",Cinderella (1950),"Sound of Music, The (1965)",Dumbo (1941),Dumbo (1941),Victor/Victoria (1982),"Hunchback of Notre Dame, The (1996)",Dirty Dancing (1987),"Lion King, The (1994)"
13,Cinderella (1950),"Blues Brothers, The (1980)",Dumbo (1941),Fantasia (1940),"Nightmare Before Christmas, The (1993)",Dumbo (1941),Beauty and the Beast (1991),This Is Spinal Tap (1984),Hercules (1997),Fantasia (1940),...,Aladdin (1992),Aladdin (1992),Pink Floyd - The Wall (1982),Dumbo (1941),This Is Spinal Tap (1984),This Is Spinal Tap (1984),Beauty and the Beast (1991),Cinderella (1950),Beauty and the Beast (1991),Mary Poppins (1964)
14,Beauty and the Beast (1991),"Sound of Music, The (1965)",Fantasia (1940),Snow White and the Seven Dwarfs (1937),Evita (1996),James and the Giant Peach (1996),"Nightmare Before Christmas, The (1993)",Fantasia (1940),Joe's Apartment (1996),"American in Paris, An (1951)",...,Pink Floyd - The Wall (1982),Pocahontas (1995),"Hunchback of Notre Dame, The (1996)",Snow White and the Seven Dwarfs (1937),"Wizard of Oz, The (1939)","Wizard of Oz, The (1939)",Aladdin (1992),"Nightmare Before Christmas, The (1993)",Pink Floyd - The Wall (1982),Alice in Wonderland (1951)
15,Snow White and the Seven Dwarfs (1937),Everyone Says I Love You (1996),James and the Giant Peach (1996),Aladdin (1992),James and the Giant Peach (1996),"Nightmare Before Christmas, The (1993)",This Is Spinal Tap (1984),"Hunchback of Notre Dame, The (1996)","Lion King, The (1994)",Beauty and the Beast (1991),...,Singin' in the Rain (1952),Joe's Apartment (1996),Singin' in the Rain (1952),"Hunchback of Notre Dame, The (1996)","Umbrellas of Cherbourg, The (Parapluies de Che...","Umbrellas of Cherbourg, The (Parapluies de Che...",Singin' in the Rain (1952),Dumbo (1941),Grease (1978),Aladdin (1992)
16,"Nightmare Before Christmas, The (1993)",Dumbo (1941),"Nightmare Before Christmas, The (1993)",Victor/Victoria (1982),Grease (1978),Spice World (1997),Cinderella (1950),Beauty and the Beast (1991),"Nightmare Before Christmas, The (1993)",Tank Girl (1995),...,Victor/Victoria (1982),Hercules (1997),Fantasia (1940),Cinderella (1950),Singin' in the Rain (1952),Singin' in the Rain (1952),Cinderella (1950),This Is Spinal Tap (1984),Singin' in the Rain (1952),My Fair Lady (1964)
17,Victor/Victoria (1982),This Is Spinal Tap (1984),"Blues Brothers, The (1980)",Cinderella (1950),"Hunchback of Notre Dame, The (1996)","Blues Brothers, The (1980)",Cats Don't Dance (1997),"MisÃ©rables, Les (1995)",Snow White and the Seven Dwarfs (1937),Aladdin (1992),...,Cinderella (1950),Cats Don't Dance (1997),"Nightmare Before Christmas, The (1993)",Singin' in the Rain (1952),Beauty and the Beast (1991),Beauty and the Beast (1991),"Nightmare Before Christmas, The (1993)",Everyone Says I Love You (1996),Fantasia (1940),James and the Giant Peach (1996)
18,Aladdin (1992),"Hunchback of Notre Dame, The (1996)","Sound of Music, The (1965)",Dirty Dancing (1987),Cinderella (1950),"Sound of Music, The (1965)",Snow White and the Seven Dwarfs (1937),Aladdin (1992),All Dogs Go to Heaven 2 (1996),"Nightmare Before Christmas, The (1993)",...,Dumbo (1941),"Hunchback of Notre Dame, The (1996)",This Is Spinal Tap (1984),Muppet Treasure Island (1996),Funny Face (1957),Funny Face (1957),Grease (1978),Alice in Wonderland (1951),Muppet Treasure Island (1996),Hercules (1997)
19,Dirty Dancing (1987),Muppet Treasure Island (1996),"Wizard of Oz, The (1939)",Gigi (1958),Victor/Victoria (1982),Snow White and the Seven Dwarfs (1937),Pink Floyd - The Wall (1982),Gigi (1958),"Wizard of Oz, The (1939)",Grease 2 (1982),...,Fantasia (1940),"Nightmare Before Christmas, The (1993)",My Fair Lady (1964),James and the Giant Peach (1996),"Inspector General, The (1949)","Inspector General, The (1949)",James and the Giant Peach (1996),Dirty Dancing (1987),James and the Giant Peach (1996),"Hunchback of Notre Dame, The (1996)"
20,James and the Giant Peach (1996),Pink Floyd - The Wall (1982),Snow White and the Seven Dwarfs (1937),Dumbo (1941),Singin' in the Rain (1952),Tank Girl (1995),"MisÃ©rables, Les (1995)",James and the Giant Peach (1996),Bedknobs and Broomsticks (1971),"Great Race, The (1965)",...,"Lion King, The (1994)",Everyone Says I Love You (1996),Dumbo (1941),Evita (1996),"Band Wagon, The (1953)","Band Wagon, The (1953)",My Fair Lady (1964),James and the Giant Peach (1996),Anastasia (1997),Cinderella (1950)
21,Dumbo (1941),Anastasia (1997),Aladdin (1992),"Hunchback of Notre Dame, The (1996)",Muppet Treasure Island (1996),Pete's Dragon (1977),Victor/Victoria (1982),Alice in Wonderland (1951),Dirty Dancing (1987),Victor/Victoria (1982),...,James and the Giant Peach (1996),Blues Brothers 2000 (1998),James and the Giant Peach (1996),Everyone Says I Love You (1996),Muppet Treasure Island (1996),Muppet Treasure Island (1996),"Hunchback of Notre Dame, The (1996)",My Fair Lady (1964),Pocahontas (1995),Dirty Dancing (1987)
22,Alice in Wonderland (1951),Hercules (1997),Cats Don't Dance (1997),"American in Paris, An (1951)",Dirty Dancing (1987),Joe's Apartment (1996),Singin' in the Rain (1952),Cinderella (1950),This Is Spinal Tap (1984),"Doors, The (1991)",...,Pocahontas (1995),"Wizard of Oz, The (1939)",Dirty Dancing (1987),Joe's Apartment (1996),Bedknobs and Broomsticks (1971),Bedknobs and Broomsticks (1971),Funny Face (1957),Hercules (1997),"Hunchback of Notre Dame, The (1996)",Victor/Victoria (1982)
23,"Hunchback of Notre Dame, The (1996)",My Fair Lady (1964),Muppet Treasure Island (1996),Muppet Treasure Island (1996),Alice in Wonderland (1951),Grease 2 (1982),Gigi (1958),Meet Me in St. Louis (1944),Pink Floyd - The Wall (1982),Backbeat (1993),...,Dirty Dancing (1987),Grease (1978),Alice in Wonderland (1951),Pocahontas (1995),Aladdin (1992),Aladdin (1992),Pocahontas (1995),Pink Floyd - The Wall (1982),Cinderella (1950),"Doors, The (1991)"
24,Gigi (1958),"Doors, The (1991)",All Dogs Go to Heaven 2 (1996),James and the Giant Peach (1996),Hercules (1997),Cats Don't Dance (1997),Hercules (1997),Hercules (1997),Cinderella (1950),Muppet Treasure Island (1996),...,Hercules (1997),Fantasia (1940),"American in Paris, An (1951)",Hercules (1997),James and the Giant Peach (1996),James and the Giant Peach (1996),Muppet Treasure Island (1996),Muppet Treasure Island (1996),Joe's Apartment (1996),Dumbo (1941)
25,Muppet Treasure Island (1996),Spice World (1997),Bedknobs and Broomsticks (1971),Pink Floyd - The Wall (1982),"Great Race, The (1965)",Grease (1978),Muppet Treasure Island (1996),Singin' in the Rain (1952),Mary Poppins (1964),Alice in Wonderland (1951),...,"Hunchback of Notre Dame, The (1996)",Dirty Dancing (1987),Cats Don't Dance (1997),Tank Girl (1995),Grease (1978),Grease (1978),Anastasia (1997),Bedknobs and Broomsticks (1971),Victor/Victoria (1982),Anastasia (1997)
26,"Doors, The (1991)",Dirty Dancing (1987),Dirty Dancing (1987),"Nightmare Before Christmas, The (1993)",Tank Girl (1995),Victor/Victoria (1982),Anastasia (1997),"Great Race, The (1965)",Alice in Wonderland (1951),Pocahontas (1995),...,Alice in Wonderland (1951),Selena (1997),Anastasia (1997),My Fair Lady (1964),Fantasia (1940),Fantasia (1940),Dumbo (1941),Singin' in the Rain (1952),Blues Brothers 2000 (1998),Bedknobs and Broomsticks (1971)
27,Pink Floyd - The Wall (1982),Cats Don't Dance (1997),Pink Floyd - The Wall (1982),Alice in Wonderland (1951),Pocahontas (1995),"American in Paris, An (1951)",Dumbo (1941),Pete's Dragon (1977),Fantasia (1940),Anastasia (1997),...,Funny Face (1957),All Dogs Go to Heaven 2 (1996),Muppet Treasure Island (1996),"American in Paris, An (1951)","Nightmare Before Christmas, The (1993)","Nightmare Before Christmas, The (1993)",Alice in Wonderland (1951),Anastasia (1997),Everyone Says I Love You (1996),Shall We Dance? (1937)
28,Anastasia (1997),Tank Girl (1995),Spice World (1997),"Three Caballeros, The (1945)","Doors, The (1991)","Hunchback of Notre Dame, The (1996)",Grease (1978),Victor/Victoria (1982),Grease (1978),"Lion King, The (1994)",...,Cats Don't Dance (1997),Bedknobs and Broomsticks (1971),Bedknobs and Broomsticks (1971),Anastasia (1997),"Lion King, The (1994)","Lion King, The (1994)",Blues Brothers 2000 (1998),Pete's Dragon (1977),Bedknobs and Broomsticks (1971),"Nightmare Before Christmas, The (1993)"
29,Pete's Dragon (1977),Pete's Dragon (1977),Blues Brothers 2000 (1998),"Umbrellas of Cherbourg, The (Parapluies de Che...",Pete's Dragon (1977),Beauty and the Beast (1991),Spice World (1997),"Umbrellas of Cherbourg, The (Parapluies de Che...",My Fair Lady (1964),Mary Poppins (1964),...,Pete's Dragon (1977),"Blues Brothers, The (1980)","Doors, The (1991)",Dirty Dancing (1987),Snow White and the Seven Dwarfs (1937),Snow White and the Seven Dwarfs (1937),Pink Floyd - The Wall (1982),Pocahontas (1995),Pete's Dragon (1977),Cats Don't Dance (1997)
30,Meet Me in St. Louis (1944),Joe's Apartment (1996),Mary Poppins (1964),Top Hat (1935),Everyone Says I Love You (1996),Anastasia (1997),Bedknobs and Broomsticks (1971),"Doors, The (1991)",Dumbo (1941),Cinderella (1950),...,"Doors, The (1991)",This Is Spinal Tap (1984),Gigi (1958),Alice in Wonderland (1951),"Damsel in Distress, A (1937)","Damsel in Distress, A (1937)",Dirty Dancing (1987),Joe's Apartment (1996),Hercules (1997),"American in Paris, An (1951)"
31,Joe's Apartment (1996),Top Hat (1935),Alice in Wonderland (1951),Meet Me in St. Louis (1944),"American in Paris, An (1951)",Blues Brothers 2000 (1998),"American in Paris, An (1951)","Three Caballeros, The (1945)",Pocahontas (1995),Spice World (1997),...,"Great Race, The (1965)",Pink Floyd - The Wall (1982),"Inspector General, The (1949)","Doors, The (1991)",Shall We Dance? (1937),Shall We Dance? (1937),Cats Don't Dance (1997),Blues Brothers 2000 (1998),"Inspector General, The (1949)",Grease 2 (1982)
32,Bedknobs and Broomsticks (1971),Grease (1978),Grease (1978),"Great Race, The (1965)",Joe's Apartment (1996),"Band Wagon, The (1953)",Meet Me in St. Louis (1944),"American in Paris, An (1951)","MisÃ©rables, Les (1995)",Pink Floyd - The Wall (1982),...,Muppet Treasure Island (1996),Spice World (1997),Hercules (1997),All Dogs Go to Heaven 2 (1996),Top Hat (1935),Top Hat (1935),All Dogs Go to Heaven 2 (1996),"Doors, The (1991)",Backbeat (1993),Muppet Treasure Island (1996)
33,Pocahontas (1995),"Great Race, The (1965)",Pocahontas (1995),Hercules (1997),My Fair Lady (1964),Muppet Treasure Island (1996),"Great Race, The (1965)",Pink Floyd - The Wall (1982),Farinelli: il castrato (1994),Dirty Dancing (1987),...,"Three Caballeros, The (1945)",My Fair Lady (1964),Top Hat (1935),Bedknobs and Broomsticks (1971),"Doors, The (1991)","Doors, The (1991)",Bedknobs and Broomsticks (1971),Victor/Victoria (1982),Tank Girl (1995),"Umbrellas of Cherbourg, The (Parapluies de Che..."
34,Funny Face (1957),Victor/Victoria (1982),Farinelli: il castrato (1994),Funny Face (1957),Gigi (1958),All Dogs Go to Heaven 2 (1996),Dirty Dancing (1987),Pocahontas (1995),"American in Paris, An (1951)",Bedknobs and Broomsticks (1971),...,Meet Me in St. Louis (1944),"MisÃ©rables, Les (1995)",Pocahontas (1995),"Inspector General, The (1949)",Farinelli: il castrato (1994),Farinelli: il castrato (1994),Spice World (1997),Tank Girl (1995),Alice in Wonderland (1951),"Gay Divorcee, The (1934)"
35,Top Hat (1935),"Three Caballeros, The (1945)",Meet Me in St. Louis (1944),Joe's Apartment (1996),"Three Caballeros, The (1945)",Bedknobs and Broomsticks (1971),All Dogs Go to Heaven 2 (1996),"Nightmare Before Christmas, The (1993)",Meet Me in St. Louis (1944),Shall We Dance? (1937),...,"American in Paris, An (1951)",Farinelli: il castrato (1994),Pete's Dragon (1977),Top Hat (1935),Cats Don't Dance (1997),Cats Don't Dance (1997),"MisÃ©rables, Les (1995)",Spice World (1997),Funny Face (1957),Tank Girl (1995)
36,"Great Race, The (1965)",Meet Me in St. Louis (1944),Gigi (1958),Anastasia (1997),"MisÃ©rables, Les (1995)",Mary Poppins (1964),Joe's Apartment (1996),Bedknobs and Broomsticks (1971),Gigi (1958),All Dogs Go to Heaven 2 (1996),...,Blues Brothers 2000 (1998),"American in Paris, An (1951)",Meet Me in St. Louis (1944),Backbeat (1993),"Gay Divorcee, The (1934)","Gay Divorcee, The (1934)",Farinelli: il castrato (1994),Grease 2 (1982),"Gay Divorcee, The (1934)",Funny Face (1957)
37,"Three Caballeros, The (1945)",Alice in Wonderland (1951),"Three Caballeros, The (1945)",Bedknobs and Broomsticks (1971),Funny Face (1957),Alice in Wonderland (1951),Tank Girl (1995),Farinelli: il castrato (1994),"Three Caballeros, The (1945)",Blues Brothers 2000 (1998),...,Bedknobs and Broomsticks (1971),Meet Me in St. Louis (1944),Victor/Victoria (1982),Pete's Dragon (1977),Pink Floyd - The Wall (1982),Pink Floyd - The Wall (1982),"American in Paris, An (1951)",Selena (1997),All Dogs Go to Heaven 2 (1996),Top Hat (1935)
38,"American in Paris, An (1951)",Blues Brothers 2000 (1998),Victor/Victoria (1982),Backbeat (1993),"Inspector General, The (1949)",My Fair Lady (1964),"Doors, The (1991)","Gay Divorcee, The (1934)",Victor/Victoria (1982),Dumbo (1941),...,All Dogs Go to Heaven 2 (1996),Gigi (1958),Spice World (1997),Grease 2 (1982),"Great Race, The (1965)","Great Race, The (1965)",Meet Me in St. Louis (1944),"Three Caballeros, The (1945)","Great Race, The (1965)",Selena (1997)
39,Tank Girl (1995),Bedknobs and Broomsticks (1971),"Great Race, The (1965)","Gay Divorcee, The (1934)",Meet Me in St. Louis (1944),Pocahontas (1995),Backbeat (1993),"Inspector General, The (1949)","Great Race, The (1965)","MisÃ©rables, Les (1995)",...,"Nightmare Before Christmas, The (1993)","Three Caballeros, The (1945)","Gay Divorcee, The (1934)",Shall We Dance? (1937),Cinderella (1950),Cinderella (1950),Gigi (1958),Shall We Dance? (1937),Meet Me in St. Louis (1944),Pocahontas (1995)

In [753]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Mystery, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [754]:
#administrator

In [755]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Mystery, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [756]:
#artist

In [757]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Mystery, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [758]:
#doctor

In [759]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Mystery, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [760]:
#educator

In [761]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Mystery, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [762]:
#engineer

In [763]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Mystery, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [764]:
#entertainment

In [765]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Mystery, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [766]:
#executive

In [767]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Mystery, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [768]:
#healthcare

In [769]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Mystery, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [770]:
#homemaker

In [771]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Mystery, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [772]:
#lawyer

In [773]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Mystery, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [774]:
#librarian

In [775]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Mystery, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [776]:
#marketing

In [777]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Mystery, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [778]:
#none

In [779]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Mystery, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [780]:
#other

In [781]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Mystery, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [782]:
#programmer

In [783]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Mystery, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [784]:
#retired

In [785]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Mystery, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [786]:
#salesman

In [787]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Mystery, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [788]:
#scientist

In [789]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Mystery, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [790]:
#student

In [791]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Mystery, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [792]:
#technician

In [793]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Mystery, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [794]:
#writer

In [795]:
Mystery_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Mystery_occupation_rank = Mystery_occupation_rank.reset_index(drop=True)
Mystery_occupation_rank.index += 1
Mystery_occupation_rank = Mystery_occupation_rank.rename_axis("Rank")
Mystery_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Mission: Impossible (1996),Amadeus (1984),L.A. Confidential (1997),L.A. Confidential (1997),Mission: Impossible (1996),L.A. Confidential (1997),Murder at 1600 (1997),Amadeus (1984),Conspiracy Theory (1997),Amadeus (1984),...,Conspiracy Theory (1997),Mission: Impossible (1996),Conspiracy Theory (1997),Mission: Impossible (1996),Amadeus (1984),Amadeus (1984),L.A. Confidential (1997),Mission: Impossible (1996),Mission: Impossible (1996),L.A. Confidential (1997)
2,2001: A Space Odyssey (1968),Lone Star (1996),"Third Man, The (1949)",Amadeus (1984),2001: A Space Odyssey (1968),"Game, The (1997)",Mission: Impossible (1996),2001: A Space Odyssey (1968),Murder at 1600 (1997),Vertigo (1958),...,Murder at 1600 (1997),L.A. Confidential (1997),Mission: Impossible (1996),2001: A Space Odyssey (1968),Murder at 1600 (1997),Murder at 1600 (1997),Conspiracy Theory (1997),Conspiracy Theory (1997),Amadeus (1984),Conspiracy Theory (1997)
3,Amadeus (1984),L.A. Confidential (1997),Murder at 1600 (1997),Conspiracy Theory (1997),Amadeus (1984),2001: A Space Odyssey (1968),"Game, The (1997)",L.A. Confidential (1997),"Game, The (1997)",2001: A Space Odyssey (1968),...,L.A. Confidential (1997),"Game, The (1997)",Murder at 1600 (1997),Amadeus (1984),Vertigo (1958),Vertigo (1958),Amadeus (1984),"Game, The (1997)",2001: A Space Odyssey (1968),Rear Window (1954)
4,L.A. Confidential (1997),2001: A Space Odyssey (1968),"Game, The (1997)",Rear Window (1954),L.A. Confidential (1997),I Know What You Did Last Summer (1997),Conspiracy Theory (1997),Mission: Impossible (1996),Midnight in the Garden of Good and Evil (1997),Chinatown (1974),...,"Game, The (1997)",I Know What You Did Last Summer (1997),L.A. Confidential (1997),Conspiracy Theory (1997),Chinatown (1974),Chinatown (1974),2001: A Space Odyssey (1968),L.A. Confidential (1997),Conspiracy Theory (1997),Vertigo (1958)
5,Conspiracy Theory (1997),Conspiracy Theory (1997),Mission: Impossible (1996),2001: A Space Odyssey (1968),"Game, The (1997)","Devil's Advocate, The (1997)",L.A. Confidential (1997),"Game, The (1997)",Mission: Impossible (1996),L.A. Confidential (1997),...,"Devil's Advocate, The (1997)",Absolute Power (1997),"Game, The (1997)",L.A. Confidential (1997),L.A. Confidential (1997),L.A. Confidential (1997),Mission: Impossible (1996),Amadeus (1984),Event Horizon (1997),"Devil's Advocate, The (1997)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,That Darn Cat! (1965),Palmetto (1998),That Darn Cat! (1965),That Darn Cat! (1997),Palmetto (1998),That Darn Cat! (1965),Palmetto (1998),That Darn Cat! (1997),That Darn Cat! (1965),That Darn Cat! (1965),...,That Darn Cat! (1965),That Darn Cat! (1965),Palmetto (1998),Palmetto (1998),Palmetto (1998),Palmetto (1998),That Darn Cat! (1965),Power 98 (1995),Palmetto (1998),Palmetto (1998)
58,Lady of Burlesque (1943),That Darn Cat! (1965),Lady of Burlesque (1943),Just Cause (1995),Lady of Burlesque (1943),Lady of Burlesque (1943),Lady of Burlesque (1943),Flesh and Bone (1993),Lady of Burlesque (1943),Lady of Burlesque (1943),...,Lady of Burlesque (1943),Lady of Burlesque (1943),Lady of Burlesque (1943),Lady of Burlesque (1943),That Darn Cat! (1965),That Darn Cat! (1965),Lady of Burlesque (1943),Lady of Burlesque (1943),That Darn Cat! (1965),Lady of Burlesque (1943)
59,"Underneath, The (1995)",Lady of Burlesque (1943),"Underneath, The (1995)",Lady of Burlesque (1943),"Underneath, The (1995)","Underneath, The (1995)","Underneath, The (1995)",Palmetto (1998),"Underneath, The (1995)","Underneath, The (1995)",...,"Underneath, The (1995)","Underneath, The (1995)","Underneath, The (1995)","Underneath, The (1995)","Underneath, The (1995)","Underneath, The (1995)","Underneath, The (1995)","Underneath, The (1995)",Lady of Burlesque (1943),"Underneath, The (1995)"
60,"Woman in Question, The (1950)","Underneath, The (1995)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)",Lady of Burlesque (1943),"Woman in Question, The (1950)","Woman in Question, The (1950)",...,"Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)","Woman in Question, The (1950)"
61,MURDER and murder (1996),"Woman in Question, The (1950)",MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),...,MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996),MURDER and murder (1996)

In [796]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Romance, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [797]:
#administrator

In [798]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Romance, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [799]:
#artist

In [800]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Romance, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [801]:
#doctor

In [802]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Romance, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [803]:
#educator

In [804]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Romance, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [805]:
#engineer

In [806]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Romance, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [807]:
#entertainment

In [808]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Romance, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [809]:
#executive

In [810]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Romance, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [811]:
#healthcare

In [812]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Romance, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [813]:
#homemaker

In [814]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Romance, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [815]:
#lawyer

In [816]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Romance, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [817]:
#librarian

In [818]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Romance, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [819]:
#marketing

In [820]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Romance, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [821]:
#none

In [822]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Romance, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [823]:
#other

In [824]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Romance, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [825]:
#programmer

In [826]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Romance, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [827]:
#retired

In [828]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Romance, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [829]:
#salesman

In [830]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Romance, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [831]:
#scientist

In [832]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Romance, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [833]:
#student

In [834]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Romance, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [835]:
#technician

In [836]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Romance, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [837]:
#writer

In [838]:
Romance_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Romance_occupation_rank = Romance_occupation_rank.reset_index(drop=True)
Romance_occupation_rank.index += 1
Romance_occupation_rank = Romance_occupation_rank.rename_axis("Rank")
Romance_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,"English Patient, The (1996)",Star Wars (1977),Titanic (1997),"English Patient, The (1996)",Star Wars (1977),"English Patient, The (1996)",Jerry Maguire (1996),Return of the Jedi (1983),"Saint, The (1997)","English Patient, The (1996)",...,"English Patient, The (1996)",Star Wars (1977),Star Wars (1977),Star Wars (1977),Jerry Maguire (1996),Jerry Maguire (1996),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977)
2,Star Wars (1977),Return of the Jedi (1983),"English Patient, The (1996)",Star Wars (1977),Return of the Jedi (1983),Jerry Maguire (1996),"English Patient, The (1996)",Star Wars (1977),Conspiracy Theory (1997),Star Wars (1977),...,Star Wars (1977),Phenomenon (1996),"English Patient, The (1996)",Return of the Jedi (1983),Star Wars (1977),Star Wars (1977),"English Patient, The (1996)",Return of the Jedi (1983),Return of the Jedi (1983),"English Patient, The (1996)"
3,Return of the Jedi (1983),"English Patient, The (1996)",Psycho (1960),Sense and Sensibility (1995),Forrest Gump (1994),Star Wars (1977),Star Wars (1977),"English Patient, The (1996)",Titanic (1997),Forrest Gump (1994),...,Conspiracy Theory (1997),Return of the Jedi (1983),Return of the Jedi (1983),"Empire Strikes Back, The (1980)","English Patient, The (1996)","English Patient, The (1996)",Return of the Jedi (1983),"Empire Strikes Back, The (1980)","Empire Strikes Back, The (1980)",Return of the Jedi (1983)
4,Jerry Maguire (1996),Chasing Amy (1997),"Truth About Cats & Dogs, The (1996)",Return of the Jedi (1983),"Empire Strikes Back, The (1980)",Chasing Amy (1997),"Saint, The (1997)",Titanic (1997),Michael (1996),Casablanca (1942),...,"Saint, The (1997)","Princess Bride, The (1987)","Saint, The (1997)","Princess Bride, The (1987)",When Harry Met Sally... (1989),When Harry Met Sally... (1989),Leaving Las Vegas (1995),Jerry Maguire (1996),Forrest Gump (1994),Titanic (1997)
5,"Empire Strikes Back, The (1980)",Leaving Las Vegas (1995),Jerry Maguire (1996),Jerry Maguire (1996),"English Patient, The (1996)",Return of the Jedi (1983),Leaving Las Vegas (1995),Tomorrow Never Dies (1997),"English Patient, The (1996)","Philadelphia Story, The (1940)",...,Return of the Jedi (1983),"Saint, The (1997)",Jerry Maguire (1996),Jerry Maguire (1996),Titanic (1997),Titanic (1997),Jerry Maguire (1996),"Princess Bride, The (1987)",Conspiracy Theory (1997),Conspiracy Theory (1997)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Temptress Moon (Feng Yue) (1996),Hugo Pool (1997),"Favor, The (1994)","Favor, The (1994)","Favor, The (1994)","Favor, The (1994)","Favor, The (1994)","Favor, The (1994)","Favor, The (1994)","Favor, The (1994)",...,"Favor, The (1994)","Favor, The (1994)",Temptress Moon (Feng Yue) (1996),Temptress Moon (Feng Yue) (1996),"Favor, The (1994)","Favor, The (1994)","Favor, The (1994)",Hugo Pool (1997),"Favor, The (1994)","Favor, The (1994)"
244,"Favor, The (1994)","Favor, The (1994)",Little City (1998),Little City (1998),Little City (1998),Little City (1998),Little City (1998),Little City (1998),Little City (1998),Little City (1998),...,Little City (1998),Little City (1998),"Favor, The (1994)",Little City (1998),Little City (1998),Little City (1998),Little City (1998),Temptress Moon (Feng Yue) (1996),Little City (1998),Little City (1998)
245,Little City (1998),Little City (1998),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),...,Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),Rough Magic (1995),"Favor, The (1994)",Rough Magic (1995),Rough Magic (1995)
246,B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),...,B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),Little City (1998),B. Monkey (1998),B. Monkey (1998)
247,Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),...,Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Sliding Doors (1998),Rough Magic (1995),Sliding Doors (1998),Sliding Doors (1998)

In [839]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(SciFi, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [840]:
#administrator

In [841]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(SciFi, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [842]:
#artist

In [843]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(SciFi, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [844]:
#doctor

In [845]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(SciFi, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [846]:
#educator

In [847]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(SciFi, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [848]:
#engineer

In [849]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(SciFi, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [850]:
#entertainment

In [851]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(SciFi, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [852]:
#executive

In [853]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(SciFi, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [854]:
#healthcare

In [855]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(SciFi, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [856]:
#homemaker

In [857]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(SciFi, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [858]:
#lawyer

In [859]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(SciFi, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [860]:
#librarian

In [861]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(SciFi, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [862]:
#marketing

In [863]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(SciFi, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [864]:
#none

In [865]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(SciFi, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [866]:
#other

In [867]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(SciFi, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [868]:
#programmer

In [869]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(SciFi, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [870]:
#retired

In [871]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(SciFi, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [872]:
#salesman

In [873]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(SciFi, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [874]:
#scientist

In [875]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(SciFi, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [876]:
#student

In [877]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(SciFi, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [878]:
#technician

In [879]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(SciFi, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [880]:
#writer

In [881]:
SciFi_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
SciFi_occupation_rank = SciFi_occupation_rank.reset_index(drop=True)
SciFi_occupation_rank.index += 1
SciFi_occupation_rank = SciFi_occupation_rank.rename_axis("Rank")
SciFi_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Star Wars (1977),Star Wars (1977),Men in Black (1997),Star Wars (1977),Star Wars (1977),Contact (1997),Contact (1997),Star Wars (1977),Contact (1997),Contact (1997),...,Contact (1997),Contact (1997),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977)
2,Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983),Contact (1997),Return of the Jedi (1983),Twelve Monkeys (1995),Star Wars (1977),Return of the Jedi (1983),Independence Day (ID4) (1996),Star Wars (1977),...,Star Wars (1977),Star Trek: First Contact (1996),Return of the Jedi (1983),Return of the Jedi (1983),Contact (1997),Contact (1997),Contact (1997),Return of the Jedi (1983),Return of the Jedi (1983),Return of the Jedi (1983)
3,Contact (1997),Contact (1997),Contact (1997),Return of the Jedi (1983),Independence Day (ID4) (1996),Return of the Jedi (1983),Independence Day (ID4) (1996),Independence Day (ID4) (1996),Spawn (1997),"Terminator, The (1984)",...,Return of the Jedi (1983),Twelve Monkeys (1995),Contact (1997),Star Trek: First Contact (1996),Men in Black (1997),Men in Black (1997),Return of the Jedi (1983),Contact (1997),Independence Day (ID4) (1996),Contact (1997)
4,Independence Day (ID4) (1996),Twelve Monkeys (1995),Independence Day (ID4) (1996),Independence Day (ID4) (1996),Star Trek: First Contact (1996),Star Trek: First Contact (1996),Twelve Monkeys (1995),Contact (1997),Mimic (1997),Return of the Jedi (1983),...,Independence Day (ID4) (1996),Independence Day (ID4) (1996),Independence Day (ID4) (1996),"Empire Strikes Back, The (1980)",Independence Day (ID4) (1996),Independence Day (ID4) (1996),Independence Day (ID4) (1996),Independence Day (ID4) (1996),Contact (1997),Twelve Monkeys (1995)
5,Back to the Future (1985),Blade Runner (1982),Star Trek: First Contact (1996),Twelve Monkeys (1995),"Empire Strikes Back, The (1980)",Starship Troopers (1997),Men in Black (1997),Face/Off (1997),Return of the Jedi (1983),Brazil (1985),...,Aliens (1986),Star Wars (1977),"Empire Strikes Back, The (1980)",Twelve Monkeys (1995),Back to the Future (1985),Back to the Future (1985),Star Trek: First Contact (1996),Twelve Monkeys (1995),Star Trek: First Contact (1996),Men in Black (1997)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Star Kid (1997),Barbarella (1968),Barbarella (1968),Star Kid (1997),Star Kid (1997),Barbarella (1968),Barbarella (1968),Star Kid (1997),Barbarella (1968),Tetsuo II: Body Hammer (1992),...,Tetsuo II: Body Hammer (1992),Barbarella (1968),No Escape (1994),Star Kid (1997),Tetsuo II: Body Hammer (1992),Tetsuo II: Body Hammer (1992),Tetsuo II: Body Hammer (1992),Alphaville (1965),Star Kid (1997),Star Kid (1997)
98,Tetsuo II: Body Hammer (1992),No Escape (1994),No Escape (1994),No Escape (1994),Tetsuo II: Body Hammer (1992),No Escape (1994),No Escape (1994),Tetsuo II: Body Hammer (1992),No Escape (1994),No Escape (1994),...,No Escape (1994),No Escape (1994),Tetsuo II: Body Hammer (1992),Tetsuo II: Body Hammer (1992),No Escape (1994),No Escape (1994),Barbarella (1968),Nemesis 2: Nebula (1995),Tetsuo II: Body Hammer (1992),No Escape (1994)
99,No Escape (1994),Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),No Escape (1994),Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),No Escape (1994),Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),...,Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),No Escape (1994),Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),Highlander III: The Sorcerer (1994),Time Tracers (1995),No Escape (1994),Highlander III: The Sorcerer (1994)
100,Highlander III: The Sorcerer (1994),"Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)",...,"Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)",Star Kid (1997),"Visitors, The (Visiteurs, Les) (1993)","Visitors, The (Visiteurs, Les) (1993)"
101,Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),...,Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995),Tetsuo II: Body Hammer (1992),Nemesis 2: Nebula (1995),Nemesis 2: Nebula (1995)

In [882]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Thriller, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [883]:
#administrator

In [884]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Thriller, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [885]:
#artist

In [886]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Thriller, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [887]:
#doctor

In [888]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Thriller, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [889]:
#educator

In [890]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Thriller, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [891]:
#engineer

In [892]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Thriller, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [893]:
#entertainment

In [894]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Thriller, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [895]:
#executive

In [896]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Thriller, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [897]:
#healthcare

In [898]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Thriller, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [899]:
#homemaker

In [900]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Thriller, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [901]:
#lawyer

In [902]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Thriller, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [903]:
#librarian

In [904]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Thriller, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [905]:
#marketing

In [906]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Thriller, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [907]:
#none

In [908]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Thriller, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [909]:
#other

In [910]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Thriller, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [911]:
#programmer

In [912]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Thriller, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [913]:
#retired

In [914]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Thriller, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [915]:
#salesman

In [916]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Thriller, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [917]:
#scientist

In [918]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(Thriller, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [919]:
#student

In [920]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Thriller, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [921]:
#technician

In [922]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Thriller, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [923]:
#writer

In [924]:
Thriller_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Thriller_occupation_rank = Thriller_occupation_rank.reset_index(drop=True)
Thriller_occupation_rank.index += 1
Thriller_occupation_rank = Thriller_occupation_rank.rename_axis("Rank")
Thriller_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Air Force One (1997),Fargo (1996),Air Force One (1997),Fargo (1996),Fargo (1996),Scream (1996),Murder at 1600 (1997),Air Force One (1997),Conspiracy Theory (1997),Fargo (1996),...,Air Force One (1997),Air Force One (1997),Air Force One (1997),Fargo (1996),Fargo (1996),Fargo (1996),Fargo (1996),Scream (1996),Fargo (1996),Fargo (1996)
2,Fargo (1996),"Fugitive, The (1993)",Fargo (1996),Air Force One (1997),"Silence of the Lambs, The (1991)",L.A. Confidential (1997),Fargo (1996),Scream (1996),"Saint, The (1997)","Silence of the Lambs, The (1991)",...,Conspiracy Theory (1997),Scream (1996),Scream (1996),Terminator 2: Judgment Day (1991),Murder at 1600 (1997),Murder at 1600 (1997),"Silence of the Lambs, The (1991)","Rock, The (1996)","Silence of the Lambs, The (1991)",Scream (1996)
3,"Silence of the Lambs, The (1991)",Scream (1996),L.A. Confidential (1997),Scream (1996),"Rock, The (1996)",Fargo (1996),"Saint, The (1997)",Fargo (1996),Air Force One (1997),Air Force One (1997),...,"Saint, The (1997)","Rock, The (1996)",Fargo (1996),Alien (1979),Air Force One (1997),Air Force One (1997),Scream (1996),Fargo (1996),Terminator 2: Judgment Day (1991),"Silence of the Lambs, The (1991)"
4,Scream (1996),Air Force One (1997),Ransom (1996),L.A. Confidential (1997),Aliens (1986),Air Force One (1997),"Rock, The (1996)","Rock, The (1996)",Volcano (1997),Scream (1996),...,Dante's Peak (1997),"Terminator, The (1984)","Saint, The (1997)","Terminator, The (1984)",North by Northwest (1959),North by Northwest (1959),Air Force One (1997),"Silence of the Lambs, The (1991)",Alien (1979),L.A. Confidential (1997)
5,Alien (1979),Terminator 2: Judgment Day (1991),"Usual Suspects, The (1995)","Saint, The (1997)",Alien (1979),"Game, The (1997)",Scream (1996),Face/Off (1997),Murder at 1600 (1997),Volcano (1997),...,Murder at 1600 (1997),"Long Kiss Goodnight, The (1996)","Rock, The (1996)",Scream (1996),Scream (1996),Scream (1996),Conspiracy Theory (1997),Air Force One (1997),Scream (1996),Air Force One (1997)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,Nightwatch (1997),Hush (1998),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Hush (1998),Hush (1998),Nightwatch (1997),Nightwatch (1997),...,Nightwatch (1997),Nightwatch (1997),Butterfly Kiss (1995),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Nightwatch (1997),Hush (1998),Nightwatch (1997),Nightwatch (1997)
248,"Spanish Prisoner, The (1997)",Nightwatch (1997),"Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)",Nightwatch (1997),Nightwatch (1997),"Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)",...,"Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)",Nightwatch (1997),"Spanish Prisoner, The (1997)","Spanish Prisoner, The (1997)"
249,Tainted (1998),"Spanish Prisoner, The (1997)",Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),"Spanish Prisoner, The (1997)",Tainted (1998),Tainted (1998),Tainted (1998),...,Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),Tainted (1998),"Spanish Prisoner, The (1997)",Tainted (1998),Tainted (1998)
250,Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Tainted (1998),Mirage (1995),Mirage (1995),Mirage (1995),...,Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Mirage (1995),Tainted (1998),Mirage (1995),Mirage (1995)
251,B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),...,B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),B. Monkey (1998),Mirage (1995),B. Monkey (1998),B. Monkey (1998)

In [925]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(War, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [926]:
#administrator

In [927]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(War, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [928]:
#artist

In [929]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(War, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [930]:
#doctor

In [931]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(War, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [932]:
#educator

In [933]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(War, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [934]:
#engineer

In [935]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(War, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [936]:
#entertainment

In [937]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(War, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [938]:
#executive

In [939]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(War, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [940]:
#healthcare

In [941]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(War, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [942]:
#homemaker

In [943]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(War, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [944]:
#lawyer

In [945]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(War, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [946]:
#librarian

In [947]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(War, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [948]:
#marketing

In [949]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(War, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [950]:
#none

In [951]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(War, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [952]:
#other

In [953]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(War, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [954]:
#programmer

In [955]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(War, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [956]:
#retired

In [957]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(War, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [958]:
#salesman

In [959]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(War, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [960]:
#scientist

In [961]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(War, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [962]:
#student

In [963]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(War, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [964]:
#technician

In [965]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(War, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [966]:
#writer

In [967]:
War_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
War_occupation_rank = War_occupation_rank.reset_index(drop=True)
War_occupation_rank.index += 1
War_occupation_rank = War_occupation_rank.rename_axis("Rank")
War_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,"English Patient, The (1996)",Star Wars (1977),"English Patient, The (1996)","English Patient, The (1996)",Star Wars (1977),"English Patient, The (1996)","English Patient, The (1996)",Star Wars (1977),Independence Day (ID4) (1996),"English Patient, The (1996)",...,"English Patient, The (1996)",Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977),Star Wars (1977)
2,Star Wars (1977),Return of the Jedi (1983),Return of the Jedi (1983),Star Wars (1977),Return of the Jedi (1983),Star Wars (1977),Star Wars (1977),Return of the Jedi (1983),"English Patient, The (1996)",Star Wars (1977),...,Star Wars (1977),Independence Day (ID4) (1996),"English Patient, The (1996)",Return of the Jedi (1983),M*A*S*H (1970),M*A*S*H (1970),"English Patient, The (1996)",Return of the Jedi (1983),Return of the Jedi (1983),"English Patient, The (1996)"
3,Return of the Jedi (1983),"English Patient, The (1996)",Independence Day (ID4) (1996),Return of the Jedi (1983),Independence Day (ID4) (1996),Return of the Jedi (1983),Independence Day (ID4) (1996),Independence Day (ID4) (1996),G.I. Jane (1997),Forrest Gump (1994),...,Return of the Jedi (1983),"Devil's Own, The (1997)",Return of the Jedi (1983),"Empire Strikes Back, The (1980)","English Patient, The (1996)","English Patient, The (1996)",Return of the Jedi (1983),Independence Day (ID4) (1996),Independence Day (ID4) (1996),Return of the Jedi (1983)
4,Independence Day (ID4) (1996),Aliens (1986),Casablanca (1942),Independence Day (ID4) (1996),Forrest Gump (1994),Starship Troopers (1997),Return of the Jedi (1983),"English Patient, The (1996)",Starship Troopers (1997),Braveheart (1995),...,Seven Years in Tibet (1997),Courage Under Fire (1996),Independence Day (ID4) (1996),Aliens (1986),Schindler's List (1993),Schindler's List (1993),Independence Day (ID4) (1996),"Empire Strikes Back, The (1980)","Empire Strikes Back, The (1980)",Aliens (1986)
5,"Empire Strikes Back, The (1980)",Schindler's List (1993),Schindler's List (1993),Schindler's List (1993),"Empire Strikes Back, The (1980)",Independence Day (ID4) (1996),Courage Under Fire (1996),"Boot, Das (1981)",Courage Under Fire (1996),Casablanca (1942),...,Independence Day (ID4) (1996),Return of the Jedi (1983),"Empire Strikes Back, The (1980)",Independence Day (ID4) (1996),Independence Day (ID4) (1996),Independence Day (ID4) (1996),Forrest Gump (1994),Braveheart (1995),Forrest Gump (1994),Independence Day (ID4) (1996)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Prisoner of the Mountains (Kavkazsky Plennik) ...,"Colonel Chabert, Le (1994)",Prisoner of the Mountains (Kavkazsky Plennik) ...,"Walking Dead, The (1995)","Colonel Chabert, Le (1994)",Prisoner of the Mountains (Kavkazsky Plennik) ...,Prisoner of the Mountains (Kavkazsky Plennik) ...,In the Army Now (1994),Prisoner of the Mountains (Kavkazsky Plennik) ...,Prisoner of the Mountains (Kavkazsky Plennik) ...,...,Prisoner of the Mountains (Kavkazsky Plennik) ...,Prisoner of the Mountains (Kavkazsky Plennik) ...,Prisoner of the Mountains (Kavkazsky Plennik) ...,"Walking Dead, The (1995)",Prisoner of the Mountains (Kavkazsky Plennik) ...,Prisoner of the Mountains (Kavkazsky Plennik) ...,Prisoner of the Mountains (Kavkazsky Plennik) ...,Paradise Road (1997),Prisoner of the Mountains (Kavkazsky Plennik) ...,Prisoner of the Mountains (Kavkazsky Plennik) ...
68,Underground (1995),Prisoner of the Mountains (Kavkazsky Plennik) ...,Underground (1995),"Colonel Chabert, Le (1994)",Prisoner of the Mountains (Kavkazsky Plennik) ...,Underground (1995),Underground (1995),To Be or Not to Be (1942),Underground (1995),Underground (1995),...,Underground (1995),Underground (1995),Underground (1995),Underground (1995),Underground (1995),Underground (1995),Underground (1995),"Farewell to Arms, A (1932)",Underground (1995),Underground (1995)
69,Pharaoh's Army (1995),Underground (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),For the Moment (1994),Pharaoh's Army (1995),Pharaoh's Army (1995),...,Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995),Pharaoh's Army (1995)
70,Land and Freedom (Tierra y libertad) (1995),Pharaoh's Army (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),"Colonel Chabert, Le (1994)",Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),...,Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995),Land and Freedom (Tierra y libertad) (1995)
71,Nothing Personal (1995),Land and Freedom (Tierra y libertad) (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),...,Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995),Nothing Personal (1995)

In [968]:
administrator = occu_3.groupby("occupation").get_group("administrator")
administrator = pd.merge(Western, administrator, on="movie id", how="left")
administrator = administrator.sort_values(by="rating", ascending= False)
administrator = administrator.reset_index(drop=True)

In [969]:
#administrator

In [970]:
artist = occu_3.groupby("occupation").get_group("artist")
artist = pd.merge(Western, artist, on="movie id", how="left")
artist = artist.sort_values(by="rating", ascending= False)
artist = artist.reset_index(drop=True)

In [971]:
#artist

In [972]:
doctor = occu_3.groupby("occupation").get_group("doctor")
doctor = pd.merge(Western, doctor, on="movie id", how="left")
doctor = doctor.sort_values(by="rating", ascending= False)
doctor = doctor.reset_index(drop=True)

In [973]:
#doctor

In [974]:
educator = occu_3.groupby("occupation").get_group("educator")
educator = pd.merge(Western, educator, on="movie id", how="left")
educator = educator.sort_values(by="rating", ascending= False)
educator = educator.reset_index(drop=True)

In [975]:
#educator

In [976]:
engineer = occu_3.groupby("occupation").get_group("engineer")
engineer = pd.merge(Western, engineer, on="movie id", how="left")
engineer = engineer.sort_values(by="rating", ascending= False)
engineer = engineer.reset_index(drop=True)

In [977]:
#engineer

In [978]:
entertainment = occu_3.groupby("occupation").get_group("entertainment")
entertainment = pd.merge(Western, entertainment, on="movie id", how="left")
entertainment = entertainment.sort_values(by="rating", ascending= False)
entertainment = entertainment.reset_index(drop=True)

In [979]:
#entertainment

In [980]:
executive = occu_3.groupby("occupation").get_group("executive")
executive = pd.merge(Western, executive, on="movie id", how="left")
executive = executive.sort_values(by="rating", ascending= False)
executive = executive.reset_index(drop=True)

In [981]:
#executive

In [982]:
healthcare = occu_3.groupby("occupation").get_group("healthcare")
healthcare = pd.merge(Western, healthcare, on="movie id", how="left")
healthcare = healthcare.sort_values(by="rating", ascending= False)
healthcare = healthcare.reset_index(drop=True)

In [983]:
#healthcare

In [984]:
homemaker = occu_3.groupby("occupation").get_group("homemaker")
homemaker = pd.merge(Western, homemaker, on="movie id", how="left")
homemaker = homemaker.sort_values(by="rating", ascending= False)
homemaker = homemaker.reset_index(drop=True)

In [985]:
#homemaker

In [986]:
lawyer = occu_3.groupby("occupation").get_group("lawyer")
lawyer = pd.merge(Western, lawyer, on="movie id", how="left")
lawyer = lawyer.sort_values(by="rating", ascending= False)
lawyer = lawyer.reset_index(drop=True)

In [987]:
#lawyer

In [988]:
librarian = occu_3.groupby("occupation").get_group("librarian")
librarian = pd.merge(Western, librarian, on="movie id", how="left")
librarian = librarian.sort_values(by="rating", ascending= False)
librarian = librarian.reset_index(drop=True)

In [989]:
#librarian

In [990]:
marketing = occu_3.groupby("occupation").get_group("marketing")
marketing = pd.merge(Western, marketing, on="movie id", how="left")
marketing = marketing.sort_values(by="rating", ascending= False)
marketing = marketing.reset_index(drop=True)

In [991]:
#marketing

In [992]:
none = occu_3.groupby("occupation").get_group("none")
none = pd.merge(Western, none, on="movie id", how="left")
none = none.sort_values(by="rating", ascending= False)
none = none.reset_index(drop=True)

In [993]:
#none

In [994]:
other = occu_3.groupby("occupation").get_group("other")
other = pd.merge(Western, other, on="movie id", how="left")
other = other.sort_values(by="rating", ascending= False)
other = other.reset_index(drop=True)

In [995]:
#other

In [996]:
programmer = occu_3.groupby("occupation").get_group("programmer")
programmer = pd.merge(Western, programmer, on="movie id", how="left")
programmer = programmer.sort_values(by="rating", ascending= False)
programmer = programmer.reset_index(drop=True)

In [997]:
#programmer

In [998]:
retired = occu_3.groupby("occupation").get_group("retired")
retired = pd.merge(Western, retired, on="movie id", how="left")
retired = retired.sort_values(by="rating", ascending= False)
retired = retired.reset_index(drop=True)

In [999]:
#retired

In [1000]:
salesman = occu_3.groupby("occupation").get_group("retired")
salesman = pd.merge(Western, salesman, on="movie id", how="left")
salesman = salesman.sort_values(by="rating", ascending= False)
salesman = salesman.reset_index(drop=True)

In [1001]:
#salesman

In [1002]:
scientist = occu_3.groupby("occupation").get_group("scientist")
scientist = pd.merge(Western, scientist, on="movie id", how="left")
scientist = scientist.sort_values(by="rating", ascending= False)
scientist = scientist.reset_index(drop=True)

In [1003]:
#scientist

In [1004]:
student = occu_3.groupby("occupation").get_group("student")
student = pd.merge(FilmNoir, student, on="movie id", how="left")
student = student.sort_values(by="rating", ascending= False)
student = student.reset_index(drop=True)

In [1005]:
#student

In [1006]:
technician = occu_3.groupby("occupation").get_group("technician")
technician = pd.merge(Western, technician, on="movie id", how="left")
technician = technician.sort_values(by="rating", ascending= False)
technician = technician.reset_index(drop=True)

In [1007]:
#technician

In [1008]:
writer = occu_3.groupby("occupation").get_group("writer")
writer = pd.merge(Western, writer, on="movie id", how="left")
writer = writer.sort_values(by="rating", ascending= False)
writer = writer.reset_index(drop=True)

In [1009]:
#writer

In [1010]:
Western_occupation_rank = pd.DataFrame({"administrator":administrator["movie title"],
                               "artist":artist["movie title"],
                               "doctor":doctor["movie title"],
                               "educator":educator["movie title"],
                               "engineer":engineer["movie title"],
                               "entertainment":entertainment["movie title"],
                               "executive":executive["movie title"],
                               "healthcare":healthcare["movie title"],
                               "homemaker":homemaker["movie title"],
                               "lawyer":lawyer["movie title"],
                               "librarian":librarian["movie title"],
                               "marketing":marketing["movie title"],
                               "none":none["movie title"],
                               "other":other["movie title"],
                               "programmer":programmer["movie title"],
                               "retired":retired["movie title"],
                               "salesman":salesman["movie title"],
                               "scientist":scientist["movie title"],
                               "student":student["movie title"],
                               "technician":technician["movie title"],
                               "writer":writer["movie title"]})
Western_occupation_rank = Western_occupation_rank.reset_index(drop=True)
Western_occupation_rank.index += 1
Western_occupation_rank = Western_occupation_rank.rename_axis("Rank")
Western_occupation_rank

,administrator,artist,doctor,educator,engineer,entertainment,executive,healthcare,homemaker,lawyer,...,marketing,none,other,programmer,retired,salesman,scientist,student,technician,writer
Rank,,,,,,,,,,,,,,,,,,,,,
1,Dances with Wolves (1990),Dances with Wolves (1990),Butch Cassidy and the Sundance Kid (1969),Butch Cassidy and the Sundance Kid (1969),Dances with Wolves (1990),Legends of the Fall (1994),Butch Cassidy and the Sundance Kid (1969),Butch Cassidy and the Sundance Kid (1969),Legends of the Fall (1994),Butch Cassidy and the Sundance Kid (1969),...,Butch Cassidy and the Sundance Kid (1969),Dances with Wolves (1990),Dances with Wolves (1990),Dances with Wolves (1990),Butch Cassidy and the Sundance Kid (1969),Butch Cassidy and the Sundance Kid (1969),"Good, The Bad and The Ugly, The (1966)",Blade Runner (1982),Dances with Wolves (1990),Butch Cassidy and the Sundance Kid (1969)
2,Butch Cassidy and the Sundance Kid (1969),Butch Cassidy and the Sundance Kid (1969),Maverick (1994),Dances with Wolves (1990),Butch Cassidy and the Sundance Kid (1969),Unforgiven (1992),Dances with Wolves (1990),Dances with Wolves (1990),Maverick (1994),Unforgiven (1992),...,"Good, The Bad and The Ugly, The (1966)",Unforgiven (1992),Butch Cassidy and the Sundance Kid (1969),Unforgiven (1992),High Noon (1952),High Noon (1952),Dances with Wolves (1990),L.A. Confidential (1997),Young Guns (1988),Unforgiven (1992)
3,Unforgiven (1992),Unforgiven (1992),Dances with Wolves (1990),Unforgiven (1992),"Good, The Bad and The Ugly, The (1966)",Dances with Wolves (1990),Unforgiven (1992),High Noon (1952),Dances with Wolves (1990),Dances with Wolves (1990),...,Dances with Wolves (1990),Legends of the Fall (1994),Unforgiven (1992),"Good, The Bad and The Ugly, The (1966)","Wild Bunch, The (1969)","Wild Bunch, The (1969)",Unforgiven (1992),"Maltese Falcon, The (1941)","Good, The Bad and The Ugly, The (1966)",Dances with Wolves (1990)
4,"Good, The Bad and The Ugly, The (1966)",High Noon (1952),"Magnificent Seven, The (1954)",High Noon (1952),Unforgiven (1992),Butch Cassidy and the Sundance Kid (1969),"Good, The Bad and The Ugly, The (1966)",Unforgiven (1992),"Good, The Bad and The Ugly, The (1966)",Maverick (1994),...,Maverick (1994),Young Guns (1988),Maverick (1994),Butch Cassidy and the Sundance Kid (1969),Dances with Wolves (1990),Dances with Wolves (1990),Butch Cassidy and the Sundance Kid (1969),"Manchurian Candidate, The (1962)",Unforgiven (1992),"Magnificent Seven, The (1954)"
5,Maverick (1994),"Good, The Bad and The Ugly, The (1966)",Legends of the Fall (1994),"Good, The Bad and The Ugly, The (1966)",Tombstone (1993),Tombstone (1993),"Magnificent Seven, The (1954)","Good, The Bad and The Ugly, The (1966)",Unforgiven (1992),"Magnificent Seven, The (1954)",...,Unforgiven (1992),Butch Cassidy and the Sundance Kid (1969),"Magnificent Seven, The (1954)",Tombstone (1993),"Magnificent Seven, The (1954)","Magnificent Seven, The (1954)","Magnificent Seven, The (1954)",Cape Fear (1962),Maverick (1994),High Noon (1952)
6,"Magnificent Seven, The (1954)","Magnificent Seven, The (1954)","Good, The Bad and The Ugly, The (1966)","Magnificent Seven, The (1954)","Magnificent Seven, The (1954)","Magnificent Seven, The (1954)",Maverick (1994),"Magnificent Seven, The (1954)",Young Guns (1988),"Wild Bunch, The (1969)",...,Young Guns (1988),Tombstone (1993),High Noon (1952),Maverick (1994),Maverick (1994),Maverick (1994),"Quick and the Dead, The (1995)",Mulholland Falls (1996),Tombstone (1993),Legends of the Fall (1994)
7,High Noon (1952),Maverick (1994),Unforgiven (1992),Maverick (1994),Maverick (1994),Dead Man (1995),Tombstone (1993),Maverick (1994),"Apple Dumpling Gang, The (1975)","Good, The Bad and The Ugly, The (1966)",...,Last Man Standing (1996),"Wild Bunch, The (1969)","Good, The Bad and The Ugly, The (1966)","Magnificent Seven, The (1954)","Good, The Bad and The Ugly, The (1966)","Good, The Bad and The Ugly, The (1966)","Wild Bunch, The (1969)",Chinatown (1974),Young Guns II (1990),Last Man Standing (1996)
8,Legends of the Fall (1994),Young Guns (1988),Young Guns (1988),Legends of the Fall (1994),Young Guns (1988),Maverick (1994),City Slickers II: The Legend of Curly's Gold (...,Legends of the Fall (1994),Butch Cassidy and the Sundance Kid (1969),"Apple Dumpling Gang, The (1975)",...,Legends of the Fall (1994),Dead Man (1995),Young Guns (1988),"Quick and the Dead, The (1995)",Unforgiven (1992),Unforgiven (1992),Legends of the Fall (1994),Hoodlum (1997),"Magnificent Seven, The (1954)",Once Upon a Time in the West (1969)
9,Young Guns (1988),Wyatt Earp (1994),"Apple Dumpling Gang, The (1975)",Wyatt Earp (1994),High Noon (1952),"Good, The Bad and The Ugly, The (1966)",High Noon (1952),"Apple Dumpling Gang, The (1975)",Tombstone (1993),Tombstone (1993),...,"Apple Dumpling Gang, The (1975)",Maverick (1994),Tombstone (1993),High Noon (1952),Once Upon a Time in the West (1969),Once Upon a Time in the West (1969),Maverick (1994),Devil in a Blue Dress (1995),Butch Cassidy and the Sundance Kid (1969),"Wild Bunch, The (1969)"
10,Tombstone (1993),"Wild Bunch, The (1969)",Tombstone (1993),Tombstone (1993),Last Man Standing (1996),Young Guns (1988),Last Man Standing (1996),Tombstone (1993),"Magnificent Seven, The (1954)",High Noon (1952),...,Tombstone (1993),"Good, The Bad and The Ugly, The (1966)",Legends of the Fall (1994),Young Guns (1988),Tombstone (1993),Tombstone (1993),Tombstone (1993),Touch of Evil (1958),Legends of the Fall (1994),"Good, The Bad and The Ugly, The (1966)"
11,Once Upon a Time in the West (1969),Last Man Standing (1996),Wild Bill (1995),Once Upon a Time in the West (1969),Legends of the Fall (1994),City Slickers II: The Legend of Curly's Gold (...,Young Guns (1988),Wyatt Earp (1994),Wild Bill (1995),Geronimo: An American Legend (1993),...,"Magnificent Seven, The (1954)","Apple Dumpling Gang, The (1975)",Dead Man (1995),Wyatt Earp (1994),City Slickers II: The Legend of Curly's Gold (...,City Slickers II: The Legend of Curly's Gold (...,High Noon (1952),"Grifters, The (1990)",Wyatt Earp (1994),Young Guns (1988)
12,Wyatt Earp (1994),Geronimo: An American Legend (1993),"Quick and the Dead, The (1995)",Young Guns (1988),Wyatt Earp (1994),"Wild Bunch, The (1969)",Once Upon a Time in the West (1969),Bad Girls (1994),"Quick and the Dead, The (1995)",Lightning Jack (1994),...,"Quick and the Dead, The (1995)","Magnificent Seven, The (1954)",Young Guns II (1990),Dead Man (1995),"Davy Crockett, King of the Wild Frontier (1955)","Davy Crockett, King of the Wild Frontier (1955)",Dead Man (1995),Dark City (1998),City Slickers II: The Legend of Curly's Gold (...,Maverick (1994)
13,City Slickers II: The Legend of Curly's Gold (...,Legends of the Fall (1994),Wyatt Earp (1994),"Wild Bunch, The (1969)",Young Guns II (1990),Once Upon a Time in the West (1969),Dead Man (1995),Young Guns II (1990),Wyatt Earp (1994),Legends of the Fall (1994),...,City Slickers II: The Legend of Curly's Gold (...,Wild Bill (1995),Once Upon a Time in the West (1969),Once Upon a Time in the West (1969),Angel and the Badman (1947),Angel and the Badman (1947),Young Guns (1988),Notorious (1946),"Wild Bunch, The (1969)",Wyatt Earp (1994)
14,"Quick and the Dead, The (1995)","Apple Dumpling Gang, The (1975)",City Slickers II: The Legend of Curly's Gold (...,"Quick and the Dead, The (1995)",City Slickers II: The Legend of Curly's Gold (...,High Noon (1952),Young Guns II (1990),Geronimo: An American Legend (1993),City Slickers II: The Legend of Curly's Gold (...,City Slickers II: The Legend of Curly's Gold (...,...,High Noon (1952),"Quick and the Dead, The (1995)",Last Man Standing (1996),Young Guns II (1990),"Outlaw, The (1943)","Outlaw, The (1943)","Apple Dumpling Gang, The (1975)",Palmetto (1998),High Noon (1952),Dead Man (1995)
15,"Wild Bunch, The (1969)",Tombstone (1993),"Wild Bunch, The (1969)",City Slickers II: The Legend of Curly's Gold (...,"Quick and the Dead, The (1995)",Last Man Standing (1996),Legends of the Fall (1994),Last Man Standing (1996),"Wild Bunch, The (1969)",Wyatt Earp (1994),...,Wild Bill (1995),Wyatt Earp (1994),"Quick and the Dead, The (1995)",Last Man Standing (1996),Legends of the Fall (1994),Legends of the Fall (1994),Wild Bill (1995),M (1931),Last Man Standing (1996),Geronimo: An American Legend (1993)
16,Wild Bill (1995),Wild Bill (1995),"Davy Crockett, King of the Wild Frontier (1955)","Apple Dumpling Gang, The (1975)",Dead Man (1995),"Apple Dumpling Gang, The (1975)","Apple Dumpling Gang, The (1975)","Quick and the Dead, The (1995)","Davy Crockett, King of the Wild Frontier (1955)","Quick and the Dead, The (1995)",...,Wyatt Earp (1994),City Slickers II: The Legend of Curly's Gold (...,"Apple Dumpling Gang, The (1975)",Legends of the Fall (1994),Young Guns (1988),Young Guns (1988),Wyatt Earp (1994),"Big Sleep, The (1946)","Quick and the Dead, The (1995)",City Slickers II: The Legend of Curly's Gold (...
17,"Apple Dumpling Gang, The (1975)","Quick and the Dead, The (1995)",Once Upon a Time in the West (1969),"Davy Crockett, King of the Wild Frontier (1955)","Wild Bunch, The (1969)",Wild Bill (1995),Wild Bill (1995),Once Upon a Time in the West (1969),Once Upon a Time in the West (1969),Young Guns (1988),...,"Wild Bunch, The (1969)","Davy Crockett, King of the Wild Frontier (1955)","Wild Bunch, The (1969)","Wild Bunch, The (1969)","Apple Dumpling Gang, The (1975)","Apple Dumpling Gang, The (1975)",City Slickers II: The Legend of Curly's Gold (...,Sunset Blvd. (1950),"Apple Dumpling Gang, The (1975)",Tombstone (1993)
18,"Davy Crockett, King of the Wild Frontier (1955)",City Slickers II: The Legend of Curly's Gold (...,High Noon (1952),Last Man Standing (1996),Once Upon a Time in the West (1969),"Quick and the Dead, The (1995)","Quick and the Dead, The (1995)","Davy Crockett, King of the Wild Frontier (1955)",High Noon (1952),Young Guns II (1990),...,"Davy Crockett, King of the Wild Frontier (1955)",Once Upon a Time in the West (1969),City Slickers II: The Legend of Curly's Gold (...,Wild Bill (1995),Wild Bill (1995),Wild Bill (1995),"Davy Crockett, King of the Wild Frontier (1955)",Laura (1944),"Davy Crockett, King of the Wild Frontier (1955)","Quick and the Dead, The (1995)"
19,Last Man Standing (1996),"Davy Crockett, King of the Wild Frontier (1955)",Last Man Standing (1996),Young Guns II (1990),Geronimo: An American Legend (1993),Wyatt Earp (1994),Wyatt Earp (1994),City Slickers II: The Legend of Curly's Gold (...,Last Man Standing (1996),Wild Bill (1995),...,Once Upon a Time in the West (1969),High Noon (1952),Angel and the Badman (1947),"Davy Crockett, King of the Wild Frontier (1955)","Quick and the Dead, The (1995)","Quick and the Dead, The (1995)",Once Upon a Time in the West (1969),Suture (1993),Once Upon a Time in the West (1969),"Apple Dumpling Gang, The (1975)"
20,Young Guns II (1990),Once Upon a Time in the West (1969),Dead Man (1995),Angel and the Badman (1947),Bad Girls (1994),"Davy Crockett, King of the Wild Frontier (1955)","Wild Bunch, The (1969)",Wild Bill (1995),Dead Man (1995),"Davy Crockett, King of the Wild Frontier (1955)",...,Dead Man (1995),Last Man Standing (1996),"Davy Crockett, King of the Wild Frontier (1955)",City Slickers II: The Legend of Curly's Gold (...,Wyatt Earp (1994),Wyatt Earp (1994),Last Man Standing (1996),"Murder, My Sweet (1944)",Dead Man (1995),Lightning Jack (1994)
21,Dead Man (1995),Dead Man (1995),Lightning Jack (1994),Wild Bill (1995),"Apple Dumpling Gang, The (1975)",Lightning Jack (1994),"Davy Crockett, King of the Wild Frontier (1955)",Young Guns (1988),Lightning Jack (1994),Once Upon a Time in the West (1969),...,Lightning Jack (1994),Lightning Jack (1994),Lightning Jack (1994),"Apple Dumpling Gang, The (1975)",Last Man Standing (1996),Last Man Standing (1996),Lightning Jack (1994),Crossfire (1947),Wild Bill (1995),Wild Bill (1995)
22,Lightning Jack (1994),Lightning Jack (1994),Geronimo: An American Legend (1993),Dead Man (1995),Wild Bill (1995),Geronimo: An American Legend (1993),Lightning Jack (1994),Terror in a Texas Town (1958),Geronimo: An American Legend (1993),Last Man Standing (1996),...,Geronimo: An American Legend (1993),Geronimo: An American Legend (1993),Geronimo: An American Legend (1993),Lightning Jack (1994),Dead Man (1995),Dead Man (1995),Geronimo: An American Legend (1993),Raw Deal (1948),Lightning Jack (1994),"Davy Crockett, King of the Wild Frontier (1955)"
23,Geronimo: An American Legend (1993),Young Guns II (1990),Young Guns II (1990),Lightning Jack (1994),"Davy Crockett, King of the Wild Frontier (1955)",Young Guns II (1990),Geronimo: An American Legend (1993),"Wild Bunch, The (1969)",Young Guns II (1990),Dead Man (1995),...,Young Guns II (1990),Young Guns II (1990),Wyatt Earp (1994),Geronimo: An American Legend (1993),Lightning Jack (1994),Lightning Jack (1994),Young Guns II (1990),T-Men (1947),Geronimo: An American Legend (1993),Young Guns II (1990)
24,Bad Girls (1994),Bad Girls (1994),Bad Girls (1994),Geronimo: An American Legend (1993),Lightning Jack (1994),Bad Girls (1994),Bad Girls (1994),Dead Man (1995),Bad Girls (1994),Bad Girls (1994),...,Bad Girls (1994),Bad Girls (1994),Bad Girls (1994),Bad Girls (1994),Geronimo: An American Legend (1993),Geronimo: An American Legend (1993),Bad Girls (1994),He Walked by Night (1948),Bad Girls (1994),Bad Girls (1994)
25,Angel and the Badman (1947),Angel and the Badman (1947),Angel and the Badman (1947),Bad Girls (1994),Angel and the Badman (1947),Angel and the Badman (1947),Angel and the Badman (1947),Lightning Jack (1994),Angel and the Badman (1947),Angel and the Badman (1947),...,Angel and the Badman (1947),Angel and the Badman (1947),Wild Bill (1995),"Outlaw, The (1943)",Young Guns II (1990),Young Guns II (1990),Angel and the Badman (1947),NaN,Angel and the Badman (1947),Angel and the Badman (1947)
26,"Outlaw, The (1943)","Outlaw, The (1943)","Outlaw, The (1943)","Outlaw, The (1943)","Outlaw, The (1943)","Outlaw, The (1943)","Outlaw, The (1943)",Angel and the Badman (1947),"Outlaw, The (1943)","Outlaw, The (1943)",...,"Outlaw, The (1943)","Outlaw, The (1943)","Outlaw, The (1943)",Angel and the Badman (1947),Bad Girls (1994),Bad Girls (1994),"Outlaw, The (1943)",NaN,"Outlaw, The (1943)","Outlaw, The (1943)"
27,Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),"Outlaw, The (1943)",Terror in a Texas Town (1958),Terror in a Texas Town (1958),...,Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),Terror in a Texas Town (1958),NaN,Terror in a Texas Town (1958),Terror in a Texas Town (1958)

---